### ISSUE TITLE
entrypoint args

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#100]
currently the boot.ts passes an empty args array which is hard coded, please allow the html page to pass a string array via the script tag reference to the entrypoint

**Comment by SteveSandersonMS** [comment]
I'm not sure we'll do this, because it's unclear how you'd go about setting values on the script tag, given that it's auto-generated during the build. The .NET code can already contain custom logic in its main method to retrieve any information from the host page (via JS interop) so that would be a better approach in most cases.

**Comment by grahamehorner** [comment]
@SteveSandersonMS the current code base and design has the ability the read script tags as it injects the blazor script to the page, it could look for a script tag of the type=blazor-args that would contain that args to pass to the entrypoint?

**Comment by SteveSandersonMS** [comment]
Actually @ebekker's work in #101 might make this possible, so this might happen fairly soon even if it's not the approach you'd use every time.

**Comment by SteveSandersonMS** [comment]
Oh, we posted at the same time. Anyway, @ebekker's work in #93 makes it possible to have extra custom args on the `<script>` tag so it might be quite easy to do this.

**Comment by grahamehorner** [comment]
It would be good if the script/args could also be injected from a mvc page?

**Comment by SteveSandersonMS** [comment]
That's covered in #108. We'll focus on the build-time integration in the short term.
