### ISSUE TITLE
Server-Side Sample Code

### ISSUE THREAD

**Issue by zsvanderlaan** [aspnet/Blazor#1015]
I am absolutely in love with the server model for reasons outline in (https://github.com/aspnet/Blazor/issues/1004).

Is there any code I can run right now to test drive this idea, or any advice on the modifications needed to get started? It seems like it would be perfect for rapidly prototyping, and I'd like an excuse to dig into my next project this weekend.

**Comment by SteveSandersonMS** [comment]
Not right now, but we’ll be working on it over the next few weeks. Thanks for letting us know you’re interested!

**Comment by Terricide** [comment]
Me too I was working on a prototype like this called Revision over a year ago and I would help out.

**Comment by vanderstack** [comment]
Is it correct to say that what was shown in the demo didn't require presentation implementation changes, but rather more infrastructural or architectural changes?

I ask because I would like to begin writing my prototype presentation implementation. I would have my component model which would of course be my html and javascript and c# for the presentation. This would use a service to retrieve the data which the component needs. The service would have historically been an abstraction over the http request and other persistence details. If no changes are required for this to run server side, I could have this service skip the http request / controller endpoint and directly use my entity framework database context and its appropriate abstractions, cutting down an insane amount of boilerplate. Oh, I just realized, I could subscribe to the entity framework change tracking to have updates pushed to my component. This replaces my full need for SignalR as well then, and gives a far more intuitive usage.

**Comment by Suchiman** [comment]
@MuhammadJameelNazir there's nothing that stops you doing Http Requests from the Server to localhost.
That's how https://github.com/Suchiman/BlazorDualMode/ works
