### ISSUE TITLE
NavLink forgets its classes when set active?

### ISSUE THREAD

**Issue by ransagy** [aspnet/Blazor#1017]
I have a Blazor 0.3.0 standalone app i've been toying with for a while and i came across an issue.
This is based off the VS Blazor template, And my NavMenu.cshtml is almost the same in regards of structure. I retained the `<NavLink Class="nav-link" .. >` form, only changing the href and adding data attributes on it.

When the link is set to active, intead of adding 'active' to the class list - it overrides it, losing all the classes that were applied, including `nav-link`. This messes up with styling.

I didn't see anything applicable in 0.4.0 changes; I might have missed something, though.

Thoughts?

EDIT; setting `activeClass` doesn't seem to change the behavior much in this regard.

**Comment by vertonghenb** [comment]
I believe this is related to #905

**Comment by ransagy** [comment]
It is? It seems to discuss a different customization of navigation components/links, rather than possible buggy/odd behavior in the current one. Maybe i misunderstood it.

**Comment by SteveSandersonMS** [comment]
Since `class` is a DOM attribute rather than a component parameter, it needs to be given in lowercase as is the convention for DOM attributes. That is, use `class="some-class"` and *not* `Class="some-class"`.

I appreciate that this is an obscure detail and can easily seem confusing. If more people report this over time, we'll try to change `NavLink` so that it's specifically insensitive to the casing of that attribute name.

**Comment by ransagy** [comment]
Shouldn't this be a warning or at least documented, then? Maybe a syntax/linter check.

**Comment by SteveSandersonMS** [comment]
Maybe. We're building up information about what people trip up on as we go.
