### ISSUE TITLE
How to use BindMethods.GetEventHandlerValue <T> (Action)

### ISSUE THREAD

**Issue by libcitra** [aspnet/Blazor#1026]
I expected to run with the following syntax.
``` cs
<li onclick="@originalMethod(foo)">test</li>

@functions {
    void originalMethod(Bar bar){
        ...
    }
}
```
But the result was a build failure.

`Argument 1: can not convert from 'void' to 'string'`

So I changed and got the results I expected.
``` cs
<li onclick="@(e => originalMethod(foo))">test</li>
```

Is this the right way?

**Comment by chucker** [comment]
Yes, because the first way would try to _return_ the value of originalMethod(), when instead you only want to invoke the method and return void.

However, I'm not sure what `Bar` is. You may want to add `UIClickEventArgs e` as a parameter.

**Comment by danroth27** [comment]
If you don't need the event args you can also do this:

```html
<li onclick="@(() => originalMethod(foo))">test</li>
```

**Comment by Behnam-Emamian** [comment]
this method is gone in Preview8, How can I replace it?

**Comment by rynowak** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!

**can you please open a new issue and be specific about what you're trying to do?**
