### ISSUE TITLE
DllNotFoundException: libc on SignalR connection creation

### ISSUE THREAD

**Issue by tylerhartwig** [aspnet/Blazor#1078]
I'm attempting to use SignalR with Blazor (I know this might be unexplored territory).

I'm getting a `DllNotFoundException: libc` in trying to create a SignalR `HubConnection`.

it looks like this issue has already come up previously, and been solved in [#515](https://github.com/aspnet/Blazor/issues/515).

I have created a minimal example to display this as well: 
[TestSignalR.zip](https://github.com/aspnet/Blazor/files/2164330/TestSignalR.zip)

I have attempted to use the Blazor HttpMessageHandler in the example, previously I did not setup SignalR with that, and got the same exception.

I'm running 0.4.0 for Blazor, .NET Core 2.1.301, OS X High Sierra, and Chrome.

Happy to provide further details, I hope I've covered relevant information.

Edit: just noticed #20, which may be relevant to this as well, if this issue will be covered by that, I can simply close this

**Comment by galvesribeiro** [comment]
Hello @tylerhartwig as we talked on Gitter, I'm waiting @danroth27 to share with me the current work the team had with SignalR support for Blazor so I can move forward with it.

Regarding your message, it is because you are attempting to use the C# client on Blazor and is not going to work. The work we are doing is to make the TypeScript client to work on it.

Lets wait to hear from @danroth27.

**Comment by SteveSandersonMS** [comment]
Yes, this is known, and others are currently working on SignalR support.
