### ISSUE TITLE
Remove bind- prefix

### ISSUE THREAD

**Issue by danieldegtyarev** [aspnet/Blazor#1080]
The proposition is to change this ugly

``` html
   ...
   <Slider bind-Start=@From bind-End=@To />
   ...
```

To obvious and clear

``` html
   ...
   <Slider Start=@From End=@To />
   ...
```

Blazor should automaticaly bind / set it depending on existance `StartChanged` / `EndChanged` events and setters of `From` / `To` properties.

**Comment by SteveSandersonMS** [comment]
I definitely like the idea of making things more streamlined, but I'm not sure we can infer the developer's intentions that way.

If your expectation is that you're just passing a value into a child component, you wouldn't expect the child component to be able to write to that property. The fact that it has a public setter doesn't indicate the developer's intentions, since most people default to declaring `{ get; set; }` on properties.

Likewise, the presence or absence of a `StartChanged` event on the child component isn't something the developer even knows about (maybe some other developer or company wrote it). Maybe one day it doesn't have a `StartChanged`, but then in the future someone adds `StartChanged` - with this proposal, that would start changing the behavior of components that *consume* the edited component, which is highly surprising and undesirable.

I think there has to be something to indicate that the developer is opting into having their property written to, which is what the `bind-` prefix achieves.

I'm going to close this because I don't think the current proposal works, but if someone has alternative ideas please do post them and we can reopen if it looks viable. Hope that's OK!

**Comment by danieldegtyarev** [comment]
What if atleast make syntax nicer, like in [Angular](https://angular.io/guide/template-syntax#binding-syntax-an-overview), for example:

``` html
 <Slider Title="Foo" [Value]=@From />
```

Where square brackets means `binding`.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. I don't personally think that's nicer, but we'll have to see over time how many different special syntax variations we'd want for all Blazor features (not just binding), and what the most coherent and consistent form for them would be. Hope that's OK!

**Comment by danieldegtyarev** [comment]
Thank you for the attention, very exciting project!

**Comment by Andrzej-W** [comment]
Personally I prefer current syntax and I don't like solutions where we can use more than one syntax to achieve the same effect. This always creates problems when in one team you have programmers with different preferences.
