### ISSUE TITLE
Parent component

### ISSUE THREAD

**Issue by danieldegtyarev** [aspnet/Blazor#1093]
Please investigate introducing ability to access parent component.
It is slightly advanced, and it mostly required for UI controls developers.
I would suggest similar syntax as for `ChildContent`:

``` cs
...
[Parameter]
BlazorComponent Parent {get;set;}
...
```

**Comment by SteveSandersonMS** [comment]
You can put a `[Parameter] BlazorComponent Parent` on any component, and pass `Parent=this` into it. If you want to, you can define your own `BlazorComponent`-derived base class with a `[Parameter] BlazorComponent Parent` and use it for all your components.

In general we don't want to do this by default because it breaks encapsulation. A parent component doesn't necessarily want to expose itself for interactivity to child components. Developers opt into doing this by passing the parent object to the child if they want to.
