### ISSUE TITLE
Native Blazor?

### ISSUE THREAD

**Issue by Thaina** [aspnet/Blazor#1101]
This might be weird approach but I wish we could have blazor compile project as native mobile app like cordova and nativescript instead of using Xamarin

Actually I think it would be possible to have wasm build from from blazor to plug inside nativescript toolchain

Is it possible in anyway? or is it already in a future plan?

**Comment by Suchiman** [comment]
The current plan is AFAIK to eventually support PWA for an app feeling.

**Comment by SteveSandersonMS** [comment]
Yes, PWAs are one possible future direction. Another possibility would be making a native UI component renderer on top of Blazor's `Renderer` abstraction (instead of rendering DOM elements in a browser view), which would be equivalent to React Native.

We don't have ETAs or commitments for either at this stage though, as we're concentrating on the core scenario of browser-based apps.
