### ISSUE TITLE
Is there a way to use DOM elements in Blazor

### ISSUE THREAD

**Issue by doga6488** [aspnet/Blazor#1102]
Hi. Does Blazor provide to manipulate DOM elements ?(without js Interop).

Like the javascript code below :
var x = document.getElementById("myText");
document.getElementById("myText").value = "Johnny Bravo";
Thanks in advance.

**Comment by chrissainty** [comment]
Not currently. But in your example code you would just do this in your component using the bind syntax.

```
<input id="myText" bind="@Name" />

@functions {
    private string Name { get; set; } = "Johnny Bravo";
}
```

**Comment by doga6488** [comment]
Thanks @chrissainty

**Comment by SteveSandersonMS** [comment]
Blazor is specifically designed to provide a convenient and efficient way to update the UI without having to issue individual calls to mutate individual DOM elements. Blazor runs a diffing algorithm to work out the minimal set of changes to apply, and runs them in a batch. This will be far more performant than crossing the interop boundary separately for each element update, and potentially interleaving DOM mutations with repaints, etc. Most modern SPA frameworks are built around an architecture similar to this.

Blazor still does allow you to directly reach DOM elements if you want via its JS interop APIs (see `ref` https://github.com/aspnet/Blazor/pull/685 and the JS interop APIs: https://blazor.net/docs/javascript-interop.html) but you should only do that for exceptional custom things, not for routine UI rendering.

**Comment by McHeff** [comment]
I am having the same issue, please can you re-open this?

**Comment by justcallmeM** [comment]
I would love you (@SteveSandersonMS) to give us - baby devs an example :)

**Comment by danroth27** [comment]
@justcallmeM Take a look at https://docs.microsoft.com/aspnet/core/blazor/javascript-interop to get started with JS interop. But like Steve said, most of the time you just let your component render and the framework will do the rest.

**Comment by dazinator** [comment]
I have found a simple bread and butter, every day, routine, UI rendering concern, that I am struggling to solve with blazor, even with js interop.

I need to fade out an element before it gets removed from the DOM. Steve made this super simple with KnockoutJS, obvioulsy blazor is still a work in progress.

The reason I mention it here is because this ties back to being able to get the DOM elements associated for blazor components and here is why:

In `foo.razor` if I decide to stop rendering a `Component` to the DOM - say using a flag like so:
```
{
   if(IsVisible)
   {
    <SomeComponent></SomeComponent?
    }
}
```

When the IsVisible property is `false` and the component is no longer rendered - blazor removes that components HTML from the DOM - but doesn't give me any opportunity to apply a fade out transition.

So.. In order to work around this here is my thrilling idea.
I'll _defer_ setting "IsVisible" to false, until `after` I have applied some `Fade Out` transition to the DOM elements contained by <SomeComponent>.

I think this could work. How would I go about this:

1. I need to identify the Html Elements contained by <SomeComponent> (i.e the DOM elements that it rendered). Sure I could peek at the components source and get class names, id's and such and use those to find the elements through JsInterop - but it seems to me a much more efficient way would be if I can query blazor's Shadow Dom equivalent to get all the DOM elements it thinks are in play for a particular component.

2. Having identified the DOM elements, I need to a way to `addEventListener`'s to them. I need to add an event listener for the `ontransitioned` event - so that I know when my fade out transition has finished, and can then call back into .NET code - where I can handle that, and then set "IsVisible" to false - which will remove the components renderfragment from the DOM completely.

Both 1 and 2 seem not possible. For 1) I'd have to peek at the components output on the page and gather the id's or class names that it can produce based on different states it might render in. 

For 2) I can use JsInterop, but all the examples I have seen only allow you to invoke a method on the javascript side that immediately returns a result back. In my case I'd need to register an event listener against some elements on the javascript side that then returns, and then when those event listeners are fired, callback into .NET.

Is there anything I can use, should leverage to achieve the above?
Thanks!

**Comment by Arshia001** [comment]
@dazinator Maybe I'm missing something, but why doesn't this (or something similar) work?

```
<div style="opacity: 0.5">
    <SomeElement />
</div>
```

**Comment by dazinator** [comment]
@Arshia001 the fade effect I am applying is a transition which means it has a duration, I.e it goes from 1 opacity to 0 opacity over x seconds. I can easily start this transition off by toggling a css class when I am ready to start fading the element out. However I need to know when the transitions finished before I remove the element from the DOM. Your example above just sets an opacity it doesnt fade it out over time.. or perhaps I am missing something?

**Comment by justcallmeM** [comment]
@danroth27 I didn't want to use JS, thats why I chose Blazor. But thanks for the info!

**Comment by dazinator** [comment]
I settled on a solution that was a bit of a compromise for fading out elements before removing them from the DOM, i've shared it over here: https://github.com/aspnet/AspNetCore/issues/10389

**Comment by chendjouCaleb** [comment]
you can design an adapter between Blazor and DOM Js using the JsInterop

**Comment by Arshia001** [comment]
@dazinator you'll want to use css classes to create the fade animation. You can't really have an element just pop out of existence, you must also think of something as to how to rest of the page will realign itself, so that also goes in css. By the end of it, the element will be gone for good, you don't need to remove it. You can probably set a timer in C# code to remove the element from the render tree as well, but I don't see why it'll be necessary.

**Comment by dazinator** [comment]
> You can probably set a timer in C# code to remove the element from the render tree as well, but I don't see why it'll be necessary.

That's the approach I used. I dont like the idea of keeping irrelevant components as part of my render tree - I want to remove stuff from the render tree but fade them out as a consequence of removing them. You may not feel its necessary to remove hidden html from the blazor rendertree and strictly that is true, however adding and removing things from the render tree is  not a bad practice, in fact - this is just how blazor is designed to work. Having to keep all html that is removed from the DOM as part of the render tree is a code smell in my opinion and you have to ask why that is necessary. I know you suggest this as a workaround but I just want to iterate that this is not undesirable solution for a framework such as blazor imho. The timer based workaround / approach I'm happier with though - as you can see I already shared a solution based on that above.

**Comment by matthewpetch** [comment]
> Blazor still does allow you to directly reach DOM elements if you want via its JS interop APIs (see https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0) but you should only do that for exceptional custom things, not for routine UI rendering.

Exceptional circumstances like.... focusing an element? Because I cannot find a way to do this without JS interop

**Comment by chrissainty** [comment]
Currently yes, you do need JS interop to focus an element.

**Comment by matthewpetch** [comment]
> Currently yes, you do need JS interop to focus an element.

I figured, just not what I'd call exceptionally custom (escpecially when the focus html tag doesn't seem to work with blazor server side)

**Comment by chrissainty** [comment]
That's a fair point.

I wonder if the team are just trying to get people to not default to a JS solution. I've been really surprised with what I've been able to achieve without using JS just by thinking a bit differently about my solution. 

All that said, I appreciate for your example, JS is the only option.
