### ISSUE TITLE
What is Javascript Glue code and what does it do?

### ISSUE THREAD

**Issue by doga6488** [aspnet/Blazor#1104]
I am researching architecture of Blazor and web assembly.I have a question about following illustrations:
What is js glue code in this illustration(I guess it is a linker or something like that)
![wasm-chain](https://user-images.githubusercontent.com/26219239/42452060-b476b28c-8391-11e8-845f-995ec76816a2.png)

And where can we place it on this illustration, Does GlueCode correspond to blazor.js/mono.js ?
![blazor](https://user-images.githubusercontent.com/26219239/42452339-64b5f75c-8392-11e8-89bb-f69b93ad1064.png)

**Comment by Suchiman** [comment]
> Does GlueCode correspond to blazor.js/mono.js ?

yes, wasm for itself is completely isolated from the browser. To do anything useful, JavaScript code must provide functions to wasm that wasm can call in order to do something in the browser.
But this isn't only blazor.js/mono.js, you can provide your own JS code than can be called by blazor.
In the current 0.4 version, this is done via `Blazor.registerFunction("name", function(arg1) { ... })` and `RegisteredFunction.Invoke<object>("name", "arg1")` and in the upcomming 0.5 you can call anything defined on `window` via `JsRuntime.Current.InvokeAsync<object>("alert", "Hello World")`.
https://learn-blazor.com/architecture/interop/ Provides a detailed explanation including a sample of how the rendering works.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @Suchiman!

**Comment by doga6488** [comment]
Thanks @Suchiman
