### ISSUE TITLE
What about Clazor?

### ISSUE THREAD

**Issue by rxelizondo** [aspnet/Blazor#111]
Ok, so I am being 50% serious and 50% silly here… Basically, my thoughts are that web developers should have more than just one UI development framework option to choose from when developing web apps. I am talking about HTML/CSS being the only serious option (that I know about) to develop web apps today.

That said, I think it would be great to see other web development UI frameworks (something equivalent to WPF/Silverlight using XAML) available for developers to create web apps. If you think about it, WebAssembly opened the door for people to use languages other than JavaScript for browser front end development, so why can’t the same be true for web apps UI technology (offer more options).

Is this an option that Microsoft has thought about (as part of the ASP.NET stack)? If yes, is this the best place to talk about it? My apologies if I am off topic and aspnet/blazor turns out not the right place to post this.

Oh, by the way, the name Clazor comes from “Canvas + Razor = Clazor”. Basically, the idea of using the HTML Canvas control to take over the whole browser screen and use it to draw the custom UI…. I know, I know, it makes no sense and is not very original but hey,, hopefully it get the point across!

Thanks.

**Comment by danroth27** [comment]
For Blazor we are specifically targeting web developers using standardized web technologies. Hence the emphasis on HTML and CSS. It's totally reasonable to consider other UI options including XAML based models, but this is out of scope for Blazor. If you're interested in a XAML based model I would suggest reaching out to the [Xamarin Forms](https://github.com/xamarin/Xamarin.Forms) folks.

**Comment by rolfik** [comment]
I like this idea of making Universal UI which can run on Windows, Android, iOS, ... and web browser.
There is already such approach in JavaScript/TypeScript world called Angular/NativeScript or React/Native.
Why not extend Xamarin.Forms to browser?

I know there would be some schizofrenia whether to run such client application in browser or through native platform means...
But single UI tooling would be beneficial and effective.

**Comment by ericblankenburg** [comment]
Xamarin.Forms in browser = Silverlight.

Been there.  Done that.

Then Microsoft abandoned it after it was widely adopted.  No one will fall for that again.

Blazer is a better approach because it uses standards (WebAssembly) along with Html and CSS.

**Comment by Terricide** [comment]
Silverlight was awesome it just failed in my opinion because it required a plugin

**Comment by ericblankenburg** [comment]
I thought it was awesome too until Microsoft abandoned it and and all my customers that I recommended it to were mad at me.

I think Blazor is the right approach.  Keep HTML and CSS but get rid of the complicated JavaScript tool chain.

I want it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zezba9000** [comment]
You get compile time errors in XAML unlike HTML where you get runtime ones. The web world in my view is so far behind lessons learned years and years ago... its rather sad. To bad MS made so many bad choices on the business side with XAML.

**Comment by pmoorelegistek** [comment]
HTML canvas doesn't have enough performance to do what the OP is suggesting. But WebGL does. Check out Avalonia - which inevitably will move to web once they can figure out the best way to interop between C# and WebGL.

**Comment by AWulkan** [comment]
@zezba9000 HTML is such a simple thing that any "error" you might get will almost always be picked up by your syntax highlighter in your editor. Making a website viewable is of much higher priority to the web than having 100% correct syntax. If you want to make sure that your HTML is correctly structured then there are tools for it in most editors. There's even online services like this one: https://validator.w3.org/

**Comment by zezba9000** [comment]
@AWulkan How is having incorrect syntax not a bad thing? Thats the worst argument Iv'e every heard for this.

You still get run-time errors in both HTML and JS. Having an IDE is nice but it doesn't solve 90% of problems an actual compiler does unlike a JS interpreter. javaScript also doesn't even support header files (thus Angular, ect, ect). Its really only good as a bytecode modern langs can compile to. Thank god for WASM.

To even get close to doing JS/HTML right, you need an IDE like VS-Code, a linter, a build system like Angular (and TS for some type safety), Bable so you can use ES6 for service code and a minifier... so that means Angular has to transpile TS to JS, then the linter has basically recompile the generated JS and same for minifier... then if you want to run any of that on node.js you have to transpile that using Bable into ES5... by the time you're done, it takes way way longer than just using a modern lang like C# for the services and front end. That is called a hack...

**Comment by zezba9000** [comment]
I think I'm not being clear or you're missing some of what I'm trying to say.

> It's just how HTML works, don't blame me. Go read up on the reason of why it works that way. 

-- I know thats the problem, I'm not blaming you, I'm blaming the excuses for it.

> You're either exaggerating to make it sound super bad, or you don't know how to build web apps at all if you're having such difficulties.

> You don't need Angular or TS to write good JS code either

-- It is super bad vs modern alternatives. Thats what I'm getting at. If you don't use a build system in HTML/JS like Angular you probably shouldn't be writing large applications with HTML/JS/TS etc is part of the point. You also shouldn't be writing large applications without type safety, compile-time errors and mark-up that doesn't build out to the native lang you're using so it can in turn get compile-time / mark-up errors. What baffles me is these improved concepts have been around for a long time now and the web world still doesn't get why those points matter when making large applications.

This topic has to many moving parts for me to articulate everything and the fine details in context of why I don't like HTML / JS as a platform for application development (simple article pages work fine in HTML) ... I'm just coming off as a winning little b*tch. In any case there are better places to discus this topic.

**Comment by AWulkan** [comment]
@zezba9000 I agree that JS is not very pleasant always. I don't think it's as bad as you make it out to be though, and HTML/CSS is a godsend imo compared to XAML (but that's just my own opinion of course). I'm building very large and complicated applications with Vue right now and it's been pretty smooth sailing for the past 6 months.

As you said: 

> "In any case there are better places to discus this topic."

Which is right. We shouldn't be having a conversation like this in Blazor's Github thread. :)

I didn't intend to start an argument and I hope I didn't offend you in anyway. See you around!

**Comment by ericblankenburg** [comment]
WebAssembly is just another compilation target.  Not too different than Windows, Linux, or OSX. Since Blazor is based on WebAssembly and not a proprietary plug-in (like Silverlight), there wouldn’t be any reason for Microsoft to pull the plug on it if and when they decide to release it.

I don’t agree that a propriety markup language (XAML) is going to be an obvious success in today’s world.  Silverlight was created when Microsoft was still in full resistance mode against Internet standards.  No one is going to go back there.  What is the adoption of UWP/XAML?  Not good.

I also don’t agree that there is anything “easy” anymore about writing an application with JavaScript. Here is one of my favorite articles on the JavaScript toolchain that demonstrates this:

https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f

It seems to me that Progressive Web Apps (PWA) with WebAssembly, HTML, and CSS is probably where we are heading next as an industry, especially in the devices / mobile area.  PWA enables apps to be installed (and run offline) which makes any load time issue irrelevant.

My two cents…


________________________________

**Comment by JeffMushmo** [comment]
I went ahead and started building a Xaml engine that runs natively in the browser. You can check it out here: [https://github.com/XamlEngine/Samples](https://github.com/XamlEngine/Samples)

**Comment by vijaytanwar** [comment]
There will be no SEO if UI is through canvas. that will be the biggest failure.

**Comment by JeffMushmo** [comment]
Meh...there are plenty of ways of getting that information into web crawlers. So I'm not worried about it. BTW, have you seen how complicated it is to get a SPA to work with SEO? Hopefully the future holds a better way for site authors to define this information.

**Comment by AWulkan** [comment]
Canvas is a terrible idea for apps imo (they still have a use as a section of an app). It's slow, resource heavy, prone to errors, no SEO, no accessiblity for people who need it, hard to debug, not very responsive, and the list goes on.

**Comment by Terricide** [comment]
Zebkit has a full ui that uses the canvas of you want an example.

**Comment by peter0302** [comment]
Also @JeffMushmo substitute Canvas with WebGL and all those drawbacks fall away except SEO, which I don't really think is all that compelling when you're talking about applications that are typically gonna be behind an auth screen anyway.

**Comment by JeffMushmo** [comment]
@peter0302 It is using WebGL. WebGL graphics contexts are created from an [HTML canvas](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Getting_started_with_WebGL). In C++ I'm targeting OpenGL. [Emscripten](https://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html) translates those calls into WebGL calls.

So when I'm rendering a Rectangle, that's 2 triangles, 4 vertices (when using a triangle strip).

For those rectangles, it currently only supports SolidColorBrush. But because it's just rendering a texture, it can support any 2D image/brush. Same for rectangles with corner radius > 0.

A TextBlock is also just a Rectangle. During rendering each character gets blit'd to the texture of that rectangle based on how the text is supposed to layout.

Compared to 3D games, I've got to imagine the number of vertices for a UI will be much smaller. Because I'm dealing with such simple objects, any considerable overhead would be in the layout engine. I don't expect to have any more overhead than your typical WPF/UWP application.

**Comment by peter0302** [comment]
Nice!  

Sorry that was directed to @Awulkan. 

Wpf and UWP both render the entire UI using primitives and underlying drawing APIs. I agree with you there is no reason the browser shouldn't be able to handle drawing either provided it doesn't get bogged down too much with JS interop.

**Comment by JeffMushmo** [comment]
Yeah, I'm not exactly sure how they're doing it. Probably different for WPF than UWP considering the Projection property only exists in the latter. Also, I think that Projection property was introduced in Silverlight 5 when they added GPU rendering. So being that it carried over into UWP, I'm guessing they're doing something somewhat similar to what I'm doing. But I think you could be right for WPF. Because the only way you can do 3D in it is within a nested rectangular area. So it's probably initializing a DirectX context for that region in those cases.

**Comment by peter0302** [comment]
Oh WPF uses Direct3D 9 and UWP uses DirectComposition and Direct2D I believe.

**Comment by Thaina** [comment]
https://github.com/BlazorExtensions/Canvas

**Comment by BasieP** [comment]
> 
> 
> https://github.com/BlazorExtensions/Canvas

yeah was trying that, but it just has basic drawing functionality, and it uses the javascript canvas methods to draw on the canvas.
This whole thing is only gonne work if we can do memory copy from the c# code to the javascript/html canvas.
This will be pretty easy with the 2d canvas, but in 3d, i think it has some work...
on the other hand... i haven't seen a single demo, poc or Blazor component to use the memcopy functions described here:
https://stackoverflow.com/questions/42806037/modify-canvas-from-wasm#

but hey.. it's still young..

**Comment by ryios** [comment]
Alternative UI ideas are a cool concept.  However I think something that needs to be direly addressed in the web field right now is "SEO".

Single page apps are really cool, fast, responsive, effecient, etc and you can build some pretty awesome stuff.

But there's no real decent, standard way to get stuff into search results via SPA like designs.  You've got services like prerender.io (uh), and google does a somewhat ok job at crawling SPA content.... But it's all over the place across different search engines.

Any UI that get's built any way, there needs to be a way to instruct a crawler as to what it's crawling.

I think a really cool way to do this would be so that every single end point on a url have an associated search end point that surfaces json via a rest call.

You hit the end point in a browser with a live dom you get your SPA and it loads and renders.

You hit it via an HTTP get with some kind of special request header, like "isSearchRequest: true" then it returns json representing the data on the page, the url (to link to it) and sub areas and urls to link to that etc and that's what the crawler indexes.

But however it's done needs to be done the same way and standardized so that we can build amazing apps and stop worrying about how to index them.

**Comment by iAmBipinPaul** [comment]
@ryios  You can configure your blazor application to pre-render on server, isn't  what SEO needs?

https://github.com/danroth27/ClientSideBlazorWithPrerendering

https://chrissainty.com/prerendering-a-client-side-blazor-application/

**Comment by ryios** [comment]
Aye, that's cool, sorry still getting up to speed.

I still think Search Engines should have standards for calling rest api's to index content though.  They all need to get on the same page.

**Comment by iAmBipinPaul** [comment]
As mention here.  (I think  this does not work in the case of  Blazor as it uses c#, wasm)
https://github.com/aspnet/Blazor/issues/1311#issuecomment-413024248

> @Andrzej-W I don't think this is till the case as the big search engine bot now crawls SPA without problem
> 
> https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html
> 
> An article about the case of Bing/Yahoo : https://www.screamingfrog.co.uk/bing-javascript/
> 
> My opinion about SSR : it is a nice feature, but I don't think it should be a priority. And I would add that a SPA framework is mostly for application with high user interaction (an app that 15 years ago would have been a desktop app). For content centric application that needs SEO there is better choice like Aspnet core or razor page.
