### ISSUE TITLE
HttpClient for communication between client and server?

### ISSUE THREAD

**Issue by KlausEvenEnevoldsen** [aspnet/Blazor#1115]
Hi

What are your plans regarding communication between client and server in Blazor?

In the current template you use HttpClient which is pretty low-level. Maybe the shared project could be used for something. I think that in 2018 we should not spend time writing code that use HttpClient when we control the code on both the client and the server. There has to be a better way, do you agree? :-)

BR Klaus Even Enevoldsen

**Comment by danroth27** [comment]
A couple of thoughts on this:
- We will leverage the API client generation work planned for [ASP.NET Core 2.2](https://github.com/aspnet/Announcements/issues/307) to enable strongly typed API calls
- We are working to support running Blazor server-side in addition to client-side in the browser so that event handling  and component logic can be seamlessly executed on the server

**Comment by KlausEvenEnevoldsen** [comment]
Thanks! I will be waiting patiently for ASP.NET Core 2.2 then 👍
