### ISSUE TITLE
RenderFragment always refreshes if component or parent component calls StateHasChanged, even if there is no change to the fragment

### ISSUE THREAD

**Issue by Worble** [aspnet/Blazor#1127]
Is there any way to prevent or control this behaviour?

**Comment by SteveSandersonMS** [comment]
By "refreshes", you mean it executes? That can't be avoided because there's no way to know that its output wouldn't be different this time.

However if you have some expensive rendering logic that you need to ensure doesn't re-run except when some known set of input parameters change, then put that logic into a separate component that takes those parameters. Blazor won't re-run its render method until the parameters change.
