### ISSUE TITLE
Improve js interop with dynamic content execution

### ISSUE THREAD

**Issue by Lupusa87** [aspnet/Blazor#1134]
My experimental [project](http://lupusablazordemos.azurewebsites.net/) is working **very slow** right now.

So I think about optimization strategies and hope will achieve better performance. This strategies are different but I think this one is interesting not only for my project.

I am using **canvas** and manipulating it via js interop, it means I do heavy operations with interop, many calls, passing parameters, maintain large code etc.

Let's imagine I have **30 js registered function** (draw line, rect, arc etc) and mixing them (as will be required from projects logic) and let's say I **100 times** call, pass parameters, receive results from/to js. And it is repeating on every redraw (one second or less interval for smooth clock)!

This 30 js functions are like underlying level to access html5 canvas, it can be also referenced nuget package.

All this actions: call, passing params, return results have **time cost** and **probably is one reason for slow performance**.

So this question popups logically - can we reduce calls amount? For example collect all js functions and **call one time all this commands**.

I think it is possible, because js allows us (with many ways) to **evalute code** (execute string containing js script).

So I can use string builder, collect all necessary js logic and call it one time. Please note that in most case **I don't need results from js**, if I need only to pass in another js function.

As I mentioned there is **many ways** to execute dynamic js scripts, first option is **evil()** function but I don't want now to go in details with way is better.
I did **small research** and there can be found optimal way to do this (technique not matters for now).
There are security, debuging, preformance issues but let's forget about them for now.

I try to **model theoretical structure** to improve js interop, it to become more dynamic and interoperable. Because as it seems we can't escape from js for next months/years and we need to find ways to use it in efficient way.

We can make parallel to **sql queries**, where we can build any query and then server will execute it.

Ok, I think it sounds good, less js functions, less calls, more flexibility and custom approach.
No one denies me to do it myself, maybe not perfectly but to try :)

**Why I open this issue?**
 First I want to hear what people think about this;
 Second I think this improvement  (if it has sense) not should do all developers separately, we can say that someone will implement it and share as nuget package, but I think it's better to do blazor itself because we expect **more competentive people** in blazor team, **built-in feature** will be better and community always can contribute any improvement.

I will be happy if you think about this and measure does it have perspective or not, is this no sense or **real way for some improvement**.

Hope text is understandable, for now it is **only theoretical** but if there will be interes or I will do it myself I will share my code and results about performance.

Thank you, **waiting for your activity** :)

I know there are many open issues and many things to think and to do, but IMHO this issue can be useful too.

**Comment by chucker** [comment]
So, I take it your proposal is to have a `JavaScriptBuilder` in Blazor that you will use to dynamically prepare the JS code to execute, then pass it through interop?

Given your mention of `eval()` and SQL queries, the thing that came to mind several times reading this is that this sounds like a security hazard.

I cannot immediately think of an actual attack scenario, but you _would_ be passing arbitrary code from one source to another, opening the door for untrustworthy code to get executed as well..

**Comment by Suchiman** [comment]
the attack scenario is XSS

**Comment by Lupusa87** [comment]
Exactly, you understand correct, it was my point.
Sorry my English writing skills are bad, worse than reading :)

I have also mentioned about security and another problems and asked to forget about them for some time :)

So what I can say, **I am not security expert** but I think there is always way to minimize particular hazards or another hand hacker can find next open door for attack.

In my country we say - **because of wolves we don't stop keeping lambs :)**

We can do this dynamic execution with more safety manner or find better one, for example:
 ```
  var el = document.createElement('script');
  el.appendChild(document.createTextNode('1+1'));
  document.body.appendChild(el);
```
It will work like originally coded js script.

### **I not proof all following below are true, they are only my visions or understandings:**

We don't should reject good tool because of some hazard.
For example when we drive there is always accident risk, even we drive as safe as possible, but accidents always happen. So I prefer use car and am agree for some hazard (because I have airbags, insurance and etc). And actually whole world is doing that.
Hope you catch my point.

Hacker can find another way, for example change downloaded js file or attach some script and etc, they have lot of tricks in their arsenal.

Browser is executing everything in sandbox and this hazard can't go outside of it.

Blazor (in this case) is executing on client side and hazard can't arrive to server, database, we don't need problems in client side too but it is less dangerous than would be in server side.

We are not going to pass user input to js interop.

Hazard level depends of developers knowledge and how much he/she cares about security.
I can do this dynamic scripting now by myself and face to this hazard.
If there will be built-in feature more accurate, optimal and secure maybe it will reduce hazard and improve security better than me or another developer will do.

**Give me (to any developer) opportunity and I will decide use it or not.**
**As javascript has eval() and particular developer in particular case makes decision use it or no.**

SQL queries also contain this security problem but we are using them, I understand that we try to eliminate risk but it always stays.

**I asked to forget about this in fist step and decide will this tool be good or pointless.
In first case we can continue discussion about depending subjects.**

I think there is no programming language, library, tool and etc to be perfect, not to have disadvantages and "black sides", but they are in use and we are trying to improve them.

My conclusion will be - if we like idea we can realize it with best way and acceptable hazard level.


### **Another solution can be some VS add-on tool with will _analyze code_ or _on site use record_ this transferred dynamic scripts, from where and when they were called, what parameters are given, from with variables and offer us generated code changes for just to hard code it in js files in release.**

### It is like analyse code or record traffic to sql server and generate stored procedures and replace sql queries.

### **I know it sounds not real but IMHO it is absolutely possible.**

Let's say my button click is creating some dynalic script, tool can analyze or record and based on it generate release version code changes for both in .net side and js side.
### **Original code**
**index.cshtml**
```
void button_Click_Handle()
{
    string a = "alert(" + inputValue + ")";
    jsinterop.execute(a);
} 
```
### **Offered code**
**index.cshtml**
```
void button_Click_Handle()
{
    jsinterop.GeneratedJSFunction123( inputValue);
}
```
**jsinterop.cs file add**
```
 public static bool GeneratedJSFunction123(string param1)
        {
            return RegisteredFunction.Invoke<bool>(
                "BlazorApp.JsInterop.GeneratedJSFunction123",
                 param1);
        }
```
**js file add**
```
Blazor.registerFunction('BlazorApp.JsInterop.GeneratedJSFunction123', (param1) => {
    alert(param1);
    return true;
});
```

In result we will achieve almost same result, js calls will be collected in one call, difference will be more functions registered in js and .net and passing arguments. It will not as perfect as we need but will save some time and will be better than regular js interop.

Or maybe it can be done by blazor automatically on build, source code will contain dynamic generated script and compiled version hard coded.

**I guess this is dream but dreams sometimes become true!**

Another conclusion  - if we like idea we can find some way to realize it :)

**Comment by Andrzej-W** [comment]
@Lupusa87 I understand that you have a problem with performance - I have seen your clock demo. As you said above we will have to use JavaScript interoperability in coming months and probably years but I think your approach to build JavaScript code in C# as string is far from perfect. I think it is much better to write this code as pure JavaScript and create only C# component wrapper for it. In JS you can have at least basic intellisense and syntax highlighting. When you try to build JavaScript code as string you have nothing.
Also read this article, and especially **Do not ever use eval!** part:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval

**Comment by SteveSandersonMS** [comment]
Thanks for the interesting discussion.

At the moment I'd suggest you should experiment and figure out what approaches actually work in practice in your scenarios. For example, it's likely that instead of lots of fine-grained calls from .NET to low-level JS functions, it would work better to have a smaller number of high-level JS functions that combine a lot of the operations you're doing, so that you're not jumping between contexts so much. Alternatively you could try the unmarshalled interop, and see whether it's actually the marshalling that's expensive in your case.

For now I'll close this because it doesn't have any direct actions we can take, but I'll look forwards to hearing what you learn from your experiments.

**Comment by samuelGrahame** [comment]
@Lupusa87 if you have a look at mix HTMLElement's with Blazor: it seems to work find with moving elements with the mouse. aka forms. setting up ui elements.

https://github.com/samuelGrahame/ClassicFormsBlazor

It uses a GUID in each element, that gives it access to style of the element. also supports events that get pushed back to the c# source.

**Comment by galvesribeiro** [comment]
I think `eval()` is extremely **evil** no matter what usecase you have.

That said, out experience with Canvas and multiple renderings calls per second is okey performance wise. Someone posted on the main gitter channel that they were able to use our Canvas extensions to be a backend for their 2d game engine in Blazor.

One optimization that I thought would be good for our extension, was to make the context to batch multiple calls and then send the batch once with a Batch() call. The reason we didn't implemented that in the first place, was basically because we wanted to have (almost) the exactly same API surface as in the JS Canvas APIs. Now that we have it, it would worth to implement those optimizations. 

In all cases, I believe the interop calls are getting faster with Blazor (and mono-wasm) releases so we can expect performance improvements in the coming releases.

In all cases, _don't_ use `eval()`, ever! 💃

**Comment by Lupusa87** [comment]
just published new version.
#Implemented first solution for dynamic script execution in js interop.
Result is big improvement in performance :))))))
please test in firefox or edge, chrome is very slow :(
To test performance we can add new city in fast mode
http://lupusablazordemos.azurewebsites.net/
https://github.com/Lupusa87/LupusaBlazorProjects

I will write detailed and answer all previous comments later

**Comment by samuelGrahame** [comment]
The reason why chrome is really slow, is because you are basically getting chrome to compile code every iteration. Even tho I don't agree with using eval - dynamic Javascript. Pretty some browsers would disable this. Potentially instead of passing new functions to js. You could cache results. So all the objects you are changing. Store them in js. And in the eval script you use these variables. I can see the speed improvement as before I was unable to even view the ticks move. But because you are serving the client with code that could be injected. Aka you might store these clock names on the server. And then someone write a Javascript in the name. For this not to happen you would need to sanatize the output. Not sure if this is one the table, but if maybe gdi plus c library to get ported over, that way you could render a bitmap in blazor then send the bitmap to the canvas. Also another way. Which I have not tried. Is copy how Linux renders. You make a render server. So listen to a local port in Javascript. Then you connect to this render/graphics server. So that you can do draw calls.
