### ISSUE TITLE
Option to plug Azure SignalR in server side rendering.

### ISSUE THREAD

**Issue by iAmBipinPaul** [aspnet/Blazor#1227]

**Comment by SteveSandersonMS** [comment]
Thanks for suggesting this. Unfortunately it's not clear in what sense that is not already supported or what you'd want to be changed. I'll close due to lack of details, but if you could post an issue with specific suggestions about what feature is missing and how you'd want it to be added, we can definitely consider it. Thanks!

**Comment by iAmBipinPaul** [comment]
@SteveSandersonMS , Sorry for the unclear issue. So basically we are streaming html using SignalR in the case of Blazor server, so how can we use azure SignalR to stream html. Is it feasible and will it help as azure SignalR will balance load and all in the case of normal asp.net core web app.

**Comment by rynowak** [comment]
As I understand it, the Azure SignalR service requires a different call to `UseSignalR`. So there is some work inside of Blazor to enable this.

I think at a minimum we need to relayer what `UseServerSideBlazor` does. I'm reopening this because I'm pretty sure we want to make this easy.

**Comment by iAmBipinPaul** [comment]
@rynowak  Thank you! Looking forward.
