### ISSUE TITLE
Make BuildRenderTree async

### ISSUE THREAD

**Issue by RemiBou** [aspnet/Blazor#1240]
Hi,

Currently if we want to display values from async call inside the view we need to put it into a private field, it would be nice to be able to do "@(await myService.GetValue())". I think the only thing needed fror this would be to change the generated method BuilRenderTree to "async Task BuildRenderTree" and when called add await.

**Comment by SteveSandersonMS** [comment]
If really strong use cases emerge, and this becomes a common request, we can consider doing this.

I'd be concerned that the perf costs of doing it even for people who don't need the async may be quite high. It would force *everything* in the rendering pipeline to become async, forcing the system to track the completion of tasks and represent a lot more as delegates instead of plain method calls. We would additionally need more logic to consider what to do about queuing concurrent render calls and what effects this has on error handling and reporting. In total this may be quite expensive to develop, may destabilise the framework, and would take away focus from building more useful features.

In the short term I'd prefer not to go down this path, and instead have developers run their own async logic outside the rendering pipeline, populating fields than can be used during a synchronous render. Hope that's OK!

**Comment by RemiBou** [comment]
I have the following case : I try to implement i18n for having this kind of developer experience "@i18n.Get("MyKey") " because the translations are loaded from server with an http call I need to be in an async method. 

I have the following solutions 
- Create a component for displaying one trad key but that would mean instanciate a lot of component (I did that [here](https://github.com/RemiBou/Toss.Blazor/blob/master/Toss/Toss.Client/Shared/Trad.cshtml) )
- Init the translation synchronously (at startup or in a base component) with a .Result or .Wait(), but it causes the app to hang.

Maybe this case would be the only one interesting.
