### ISSUE TITLE
Many websocket frames send and received when using server side rendering

### ISSUE THREAD

**Issue by wanton7** [aspnet/Blazor#1248]
I used default Blazor 0.5.1 server side rendering solution template and used Chrome browsers network tab. When I clicked Counter tab 2 frames was sent and 6 received with websocket.
Does it really need to send and receive that many frames or is it a bug? I would have thought sending one and receiving one frame would have been enough.

**Comment by SteveSandersonMS** [comment]
It doesn't sound like a bug. As well as Blazor sending and receiving frames to represent events, SignalR itself is exchanging keep-alive frames another other housekeeping bits.

WebSocket traffic is designed to allow for much more chattiness than you might be used to with HTTP. The TCP connection is held open and not renegotiated for each frame. The size of the frames is very small (typically < 1KB, meaning that each fit in a single TCP frame). It's not like with HTTP requests where each one would typically span many TCP frames. Chrome's inspector is showing you the traffic at a much lower level of granularity than you'd see with HTTP, which is why it looks like more is going on when in fact less is going on.
