### ISSUE TITLE
Debugging StandaloneApp

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#127]
The StandaloneApp when running in debug is ignoring breakpoints and stop when running under vs2017 v15.5.6 the behaviour seems to have change as this did work currently when I initially ran the sample, unsure why VS isn’t attached to the process ?

**Comment by SteveSandersonMS** [comment]
We've never had debugging support yet (as in, debugging the .NET code while running in the browser). This is being tracked in #14.

Or if you're talking about debugging the Blazor server-side code (e.g., Microsoft.AspNetCore.Blazor.Server) then that is possible but I'm not sure exactly what steps are involved in making VS connect to the process. This isn't something we'd consider an aspect of Blazor, since it only applies when actually working on the Blazor libraries.
