### ISSUE TITLE
Compile time warning for unknown tags/components

### ISSUE THREAD

**Issue by MarkStega** [aspnet/Blazor#1270]
I missed putting
```
@addTagHelper *, BlazorStrap
```
in one of my cshtml source files. Of course, all of the BlazorStrap components in that source file failed to render. It would be helpful if the compilation process gave at least a warning if an opening element that doesn't match an html tag or component such as
```
<UnknownComponentOrTag...
```

**Comment by SteveSandersonMS** [comment]
It's an interesting point. If it becomes a common request we'll try to come up with some approach for that.

My preferred solution for this specific usability issue is to eliminate the need for `@addTagHelper` altogether, so you wouldn't have been in this situation in the first place.

As for warnings about unknown elements in general, one challenge is that there are obscure but technically legal use cases for emitting unknown PascalCased elements, e.g., if someone is integrating Blazor with polymer.js. In that case it would be a "warning" but with no obvious way to suppress it.

I'll close this because I hope we can avoid this entire situation in a different way. Like I mentioned, if this becomes frequently reported we can review it.

**Comment by floreseken** [comment]
I had the same issue after renaming a component.
