### ISSUE TITLE
Access sender object inside event

### ISSUE THREAD

**Issue by Lupusa87** [aspnet/Blazor#1277]
1. Is there way to get sender object inside event (for example onclick)?
Can element reference help somehow?

  For example I want to access sender Button and get it's content inside onclick.

2. How is possible  to access captured element reference inside onclick method for example to call some javascript function?

**Comment by SteveSandersonMS** [comment]
No. That would involve creating some new way to track the identity of a DOM element.

If you were able to describe at a more high level what sort of functionality you're trying to implement, it might be there's a more idiomatically Blazor-ish way to achieve what you want simply.

For example, let's say your goal is to have buttons that, when clicked, trigger some CSS animation on that same button. The Blazor way to achieve this would be to implement your special button as a component. The component would use an `ElementRef` to get a reference to its own rendered `<button>` element. It would also have an `onclick` handler that, when invoked, issues a call to some JS function passing the `ElementRef`. As such you wouldn't need any "sender" in the event handler, because you already know which button was clicked (the one whose `onclick` handler is running).

**Comment by Lupusa87** [comment]
Thank you for answer.

My use case was small calculator with input buttons provide their content as input parameter and it would be convenient to use one method and inside get senders content.

![a](https://user-images.githubusercontent.com/40779557/43901143-b73031ac-9bb4-11e8-9955-4bbb0ba36965.jpg)

[demo](https://lupusablazordemos.azurewebsites.net/CalculatorPage)
[guthub](https://github.com/Lupusa87/BlazorCalculator)

Now I am using lambda and not do separated methods for all of this buttons.
<button class="btn btn-primary b1" onclick="@(e => AddString("7"))">7</button>

Sure it is not big problem, but logically I had this question.

To have sender will be useful in another cases too.

Your recommended way to do custom component makes sense and I considered it too but for this sample case it was not necessary and would be longer way than using lambda.

I was looking inside blazor's event stuff and have this question:
Maybe it is not possible or hard to achieve but I wonder why can't we provide element or component reference as additional parameter when we invoke event.

I know that references are filled after render, is this problem?

Page itself is blazor component too and if I can implement this functional on top of component as you advised, why can we not do it on lower lever inside blazor?
