### ISSUE TITLE
Questions about security

### ISSUE THREAD

**Issue by vnvizitiu** [aspnet/Blazor#128]
I saw the stand-up presentation for this and in it, they presented a chrome-like tool used for debugging assemblies. 

My questions are:
* How would that be secure for the code in the application, would obfuscation be a way to approach it? Because I don't know how that would work from a debugging point of view then.
* Will there also be a way to check for signed assemblies? Since the assemblies and the runtime are delivered separately, how would you be sure that the downloaded assembly for the client is your own actual assembly and how would they be stored?

Thank you in advance,
Vlad V.

**Comment by wanton7** [comment]
Client-side is never secure, you always validate every request server-side gets.
Example if server is getting request to delete comment with id 7 then you have to validate that current user has rights to delete that comment. Never trust client!

**Comment by vnvizitiu** [comment]
I fully agree with requests, though we are talking about a rich stateful browser application, it can at one point contain from sensitive algorithms to proprietary ones, 

Consider the days of Silverlight, except for the requests via WCF (at least that was how we did it), they were full-blown applications that only communicated with the server for storage and workflows.

Here's a valid scenario, if I can debug how an authorization process is done in the application for several "modules", that might allow someone to bypass licensing restrictions in an application.

I know that javascript has the same issue by exposing the code, but that can be minified and uglyfied,

**Comment by wanton7** [comment]
Obfuscation is not security. If someone really wants to study your client-side code they can and nothing can stop them. Hackers can also build their own browser so nothing in browser is secure. Only data that is correctly encrypted in server side and only designed to send back to server in it's original form and client-side doesn't have way to decrypt it, is "secure". You really should design your authorization process so that nothing critical is in client-side.
It's like PC game copy protection and those are always cracked, but people still buy games. Do you really wan't to spend your company's resources on something that can't be secure?

**Comment by vnvizitiu** [comment]
Then again I wouldn't deliver a desktop application, without a signature and obfuscation. No going to the extreme of hacker that spends time on it. 

I'm going to the idea of having a set of functionalities, exposed, in a somewhat clear text (going how that tool even used the proper indenation showng the code), on the internet, which is also debuggable in real time.
Agreed that obfuscation is not security, but then again it does makes it harder, hence why uglifiers exist, except this time you're sending a full assembly with clear code. 

As for the authorisation, if the modules are present in the assemblie, and they are not ofuscated (which again i acknowledge it's not a silver bullet) i could in the debbuger just put a breakpoint, change a variable (this an extrapolation example, don't take it word for word) and not care about the server preventing me from using premium functionalities.

You are making valid points but a bit off topic :). And i agree there are designs that prevent that by splitting them in different assemblies, but the question still stands valid, the are protection mechanisms for normal desktop assemblie, how does that relate now to the web in the context of Blazor.

**Comment by wanton7** [comment]
Build two versions of the app. Another with premium functions and another without. Users that are authenticated as premium user will get different version of software binary (wasm) from server.

**Comment by vnvizitiu** [comment]
off topic, not about design, it's about capabilities :)

**Comment by SteveSandersonMS** [comment]
This is an interesting discussion but I'll mark it closed because it doesn't relate to a Blazor work item. Please feel free to continue discussing :)

**Comment by vnvizitiu** [comment]
Fair enough :D, curious if that will be taken into consideration

**Comment by SteveSandersonMS** [comment]
> How would that be secure for the code in the application, would obfuscation be a way to approach it?

There are various obfuscation tools available for .NET. They should work just the same for assemblies that you run in the browser.

> Will there also be a way to check for signed assemblies?

This is the sort of thing that is probably possible, but we'd probably try to disable as much as we can. Delivering all the crypto code involved in signature verification would make apps significantly larger. It really wouldn't achieve anything anyway - if your page and its resources have been transmitted via HTTPS, then a correctly-behaving client already knows they hasn't been tampered with since leaving the server.

> how would you be sure that the downloaded assembly for the client is your own actual assembly and how would they be stored?

Correctly-behaved clients know this because of HTTPS. But it someone wants to download your assemblies, patches them in some way, and then wants to run them, then they can. Having some kind of signature verification doesn't really work (besides slowing them down briefly) because if they are patching your assemblies, they can just change that logic so the verification is bypassed.

.NET on WebAssembly is the same as any other client scenario: the code you ship to the client is fully inspectable and modifyable by the client. This is the same for all existing web apps, plus all native mobile apps (I know some OSes have DRM-style capabilities, but jailbreaks exist).

**Comment by vnvizitiu** [comment]
Thanks for the answer :D

**Comment by vnvizitiu** [comment]
Realized what I was struggling with and wanted to reply here again in case someone has the same though,

Due to old Silverlight habits where the app was one object in the page with one or more XAPs, I got stuck more into the "monolithic" client-side application approach where the whole app would be sent to the client like with a desktop app.

Though I think it does help that we are talking HTML, in which such concerns can be handled serverside and each page only contains the C# bits and pieces relevant to that page only, so it's a mix match between SPA and normal web server requests.

**Comment by exyi** [comment]
By the way, I think that when the Ahead of Time compilation will be available, it will make the reverse engineering harder than decompiling .NET assemblies (especially if LLVM optimization will be enabled). Of course, it will never be impossible, so you really should not rely on the "client side security".

**Comment by wanton7** [comment]
You should use Blazor similar to any JavaScript SPA framework like Angular 2+. Monolithic app is good way to go. But you could split client-side to multiple applications if you really want to, like one app for admin area one for other areas. Having separate app per page is not wise, you'll lose application state on every page transfer and page load time would probably be slow. Remember to secure your server api not client app. You should create your server api by thinking that anything client sends to server might be some bad data that hacker created and how prepare for that.
