### ISSUE TITLE
AutoRest generation proxy does not work

### ISSUE THREAD

**Issue by kant2002** [aspnet/Blazor#1288]
Basically appears similar to #1122 and #634 , but not this one.

I have Blazor application with server API on http://localhost:50140 address.

In Chrome
```
Failed to load http://localhost/api/Dictionary/search?content=123&parseStructure=false: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:50140' is therefore not allowed access. The response had HTTP status code 502. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
16:42:00.172 


WASM: [System.Net.Http.HttpRequestException] TypeError: Failed to fetch
```
I have following code
```csharp
var api = new AutoRestAPI(Http, false);
this.result = await api.ApiDictionarySearchGetAsync(content, parseStructure);
// this.result = await Http.GetJsonAsync<SearchResult[]>($"api/Dictionary/search?content={content}&parseStructure=false");
```

If I uncomment line, and use standard injected client, then things start working.

The error appears because either AutoRest incorrectly get URL to which made calls, or BrowserHttpMessageHandler does not handle some corner case.

**Comment by SteveSandersonMS** [comment]
For now, AutoRest would need to use the injected client if it's going to work under WebAssembly. You'll need to check AutoRest docs to find out if there's any way of making it acquire the HttpClient from the service provider.

One of the items we're tracking is having the default HttpClient work the same way: https://github.com/mono/mono/issues/9941 So, when that is implemented, libraries such as AutoRest should work even if they do `new HttpClient` instead of acquiring the client from the service provider.
