### ISSUE TITLE
Make it easy to develop and debug using server-side Blazor and then switch to client-side Blazor

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#1318]
Now that we support running Blazor server-side some users are choosing to develop using server-side Blazor to take advantage of normal .NET debugging, and then switch to client-side Blazor to verify and then publish the app. Setting up an app to support this workflow is possible, but switching back and forth between the two hosting models requires a few manual steps. Could we make it as simple as setting a build property?

**Comment by SteveSandersonMS** [comment]
It is already a one-step process. If you have an app set up for server execution (i.e., `AddServerSideBlazor` and `UseServerSideBlazor` in your `Startup.cs`), then the only thing you have to switch is which JS file gets loaded to start it up.

That is, if you switch the `<script>` tag in `index.html` between `blazor.server.js` and `blazor.webassembly.js`, that will do it.

**Comment by MarkStega** [comment]
@SteveSandersonMS @danroth27 
In a "real" application there are more steps:
1) I register different classes as I switch back & forth; As an example I use the blazor client log extension if do client side rendering and NLog if using server side. I also toggle a data access service that uses REST when client side and direct service calls when server side.

2) I have to edit the 'main' csproj to properly set the BlazorLinkOnBuild as when building server side the link step fails so the build fails.

3) All -in-all I have to edit 3 csproj files & index.html each time I switch. I have all of the code changes driven by a defined symbol. It is easy to make a change in a particular environment but then forget to make that change in the other (which you then find after switching).

It would be nice if the index.html was generated as part of the build as well as suppressing the linker step when building server side.

Over time the need for switching will reduce as things like client side debugging become realities.

**Comment by SteveSandersonMS** [comment]
That's good info, @MarkStega!

I'm a bit reluctant to spend time making too much of a built-in feature out of this "fast switch" concept beyond what we already have, because it would be a leaky feature. In general developers who plan to ship a client-only app may rely on things that are only possible on the client (e.g., synchronous JS interop) so won't realistically be able to "fast switch" anyway. It would be disappointing to tell people this is a good way to work if in a lot of cases it will just trip them up in other ways.

Also I agree with you that this is only a temporary phase anyway, as it's only really for debugging, which is being worked on.

We'll have to see if people keep asking for this, and if so can consider dropping other work to design something for this instead.
