### ISSUE TITLE
Sending json without refreshing the page

### ISSUE THREAD

**Issue by iFredus** [aspnet/Blazor#1356]
**Issue**
There's no a natively way (without ajax) to send a POST request without refreshing the whole application.

**Context**
Imagine that you have a form in one of your pages, and you need to submit that form without refreshing any element. Using Http.SendJsonAsync doesn't work for this purpose because it refreshes the entire application, not even the current page.

If there's a way please tell me, I researched in all the few Blazor tutorials that currently exists and I found nothing.

**Comment by iFredus** [comment]
Yes, I'm using HttpClient. I think it's because the default behavior of the submit button, but using prevent default is the same as using jquery and js interop.

It would be amazing if Blazor came with a native mechanism to send a form in a stealthy way and without page refreshes. Otherwise, we will remain tied to javascript for this kind of subjects.

**Comment by SteveSandersonMS** [comment]
@iFredus The `HttpClient` already does make HTTP requests without refreshing the page. I think your issue is separate. If it's triggered by a `<button>` inside a `<form>` then please update to the latest version of Blazor which automatically calls `preventDefault` on `submit` events.

If you're still encountering issues please post minimal repro code and I'm sure we can spot what is wrong.
