### ISSUE TITLE
Router support for Multiple Libraries

### ISSUE THREAD

**Issue by DanielS4n** [aspnet/Blazor#1358]
The Blazor.Routing.Router can be extended with multi Assembly routing but you have set many methods private and also internal classes, this does not allow you to extend the Router and RouteTable but you need to rewrite them.
For example it could extend RouteTable with Append method (like Create) for add route entries for others libraries (Assembly), finally can change the parameter AppAssembly in array (AppAssemblies) for append all entries in Router.SetParameters() for multiple libraries.
Another good idea could be to activate the use of url prefixes related to the namespaces of each library (maybe through a parameter in the Router) to avoid conflicts between any components / pages with the same name in the various libraries.

Could I contribute to the project by applying these changes, is it possible?

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestions, @DanielS4n!

We have a tracking issue #293 where we're considering designs for scenarios like this, e.g., the ability to mount subapplications on a certain URL prefix.

Since we haven't confirmed any designs around this, it's better not to make any PRs about it right now as we wouldn't merge anything until we do get on to designing that aspect of the system. Hope that's OK!
