### ISSUE TITLE
warning BL9993: Component parameter 'any' is marked public, but component parameters should not be public

### ISSUE THREAD

**Issue by Lupusa87** [aspnet/Blazor#1388]
**This warning has no sense!**

1. If I want to access child **property or action** from parent using component reference I need public property (why should I add extra public method to modify private property) or action (especially).

2. I often access component's properties or actions from any place inside application, logically I need public properties or actions to have control of them.

I use public access level but VS is giving this warning.

I can use **internal** access level but I think it will be also against the logic based with blazor analyzer requires private.

My questions:
**1. What are arguments for requesting private?**

**2. Why can not be used public or internal?**

**3. If there is good reason then what can we do in above cases?**

@SteveSandersonMS

**Comment by Lupusa87** [comment]
This contains cases mentioned above https://github.com/aspnet/Blazor/issues/1355#issuecomment-418591770

**Comment by SteveSandersonMS** [comment]
The analyzer that tells you to use nonpublic (i.e., `private`, `protected`, or `internal`) only applies to component *parameters*, not to any other methods, properties, or fields. So if you want to have public methods on your components you absolutely can and should - that's a totally standard pattern.

The only thing we're recommending not to do is have public *parameters* (i.e., `[Parameter]`). That's because there's only one correct way to set them, which is using the attributes on components in markup. If you try to set them any other way (e.g., from procedural C# code), the effect won't be what you want, because the receiving component won't re-render automatically. If you *do* want it to re-render, then give it some public method that receives the new value, assigns its own property, and calls `StateHasChanged`.

Finally, this is only guidance. If you don't like this recommendation, you can turn it off in your own project: https://stackoverflow.com/questions/34720443/suppressing-issues-from-roslyn-code-analyzers

**Comment by SteveSandersonMS** [comment]
I agree we should do that. PRs welcome!

**Comment by kswoll** [comment]
@SteveSandersonMS alright, here's my stab at this! :)  https://github.com/aspnet/Blazor/pull/1702
