### ISSUE TITLE
ref attribute is null

### ISSUE THREAD

**Issue by stsrki** [aspnet/Blazor#1394]
I have a custom components for my _navbar_ and I want to control the collapse(BarMenu) using the reference attribute like this:

```
<Bar Expand="Size.Large" Background="Background.Primary" Theme="Theme.Dark">
    <BarBrand To="">Home</BarBrand>
    <BarToggler For="@barMenu">
        <span class="navbar-toggler-icon"></span>
    </BarToggler>
    <BarMenu ref="barMenu">
        ...
    </BarMenu>
</Bar

@functions{
    private BarMenu barMenu;
}
```
In my BarToggler I have this code for button onclick event:

```
[Parameter] private BarMenu For { get; set; }

protected void ClickHandler()
{
    For?.Toggle();
}
```
and in BarMenu:
```
public void Toggle()
{
    IsOpen = !IsOpen;
    Toggled?.Invoke( IsOpen );

    StateHasChanged();
}
```

Now the problem is that this only works if I place the Bar **inside** of MainLayout component. If I try to place it inside of any other component/page it is not working. The **For** attribute is always null in the BarToggler component and because of that the Toggle function will never be called.

**Comment by SteveSandersonMS** [comment]
This approach isn't valid because you're trying to pass `@barMenu` to `<BarToggler>` before the `<BarMenu>` has even been instantiated. It gets instantiated *after* `<BarToggler>`, because in your code, `<BarToggler>` comes before `<BarMenu>`.

It probably would work if you swapped the order of those two components, but that would be a fragile (and a bit hacky) solution.

If you really want to use the host component to orchestrate passing one child a reference to a different child, you could do it something like this (haven't tested, might contain syntax errors):

```
<Bar Expand="Size.Large" Background="Background.Primary" Theme="Theme.Dark">
    <BarBrand To="">Home</BarBrand>
    <BarToggler ref="barToggler">
        <span class="navbar-toggler-icon"></span>
    </BarToggler>
    <BarMenu ref="barMenu">
        ...
    </BarMenu>
</Bar

@functions{
    private BarMenu barMenu;
    private BarToggler barToggler;

    protected override void OnAfterRender()
    {
        barToggler.AssociateWith(barMenu); // Make this a public method on BarToggler
    }
}
```

Longer term, it will be possible to do this much more cleanly when we implement either `context` (#1) or templated components. The longer term solution would put this orchestration logic in your `<Bar>` component so that `Bar`-consumers don't have to know about this orchestration logic.

**Comment by SteveSandersonMS** [comment]
BTW maybe a simpler short-term solution for you would be:

```
<Bar Expand="Size.Large" Background="Background.Primary" Theme="Theme.Dark">
    <BarBrand To="">Home</BarBrand>
    <BarToggler OnClick=@(() => barMenu.Toggle())>
        <span class="navbar-toggler-icon"></span>
    </BarToggler>
    <BarMenu ref="barMenu">
        ...
    </BarMenu>
</Bar>

@functions{
    private BarMenu barMenu;
}
```

... so that BarToggle doesn't have to know about BarMenu at all. It would just expose an `OnClick` (of type `Action` or `Func<Task>`).
