### ISSUE TITLE
Subscribing to data changes

### ISSUE THREAD

**Issue by LaurenceFrost** [aspnet/Blazor#1406]
Coming from a Knockout background, I am used to creating properties (observables) in my view models, and then creating subscriptions to them so that an event automatically occurs when a value changes (regardless of how that value change happens).

Is there something similar in Blazor (either already, or in the pipeline)?

Taking the inbuilt "counter" example, I want SetDataAsChanged() to be called whenever there is a change to the currentCount variable, keeping in mind that there could be multiple ways that the variable could be updated, and I do not want to have to manually call SetDataAsChanged() each time.

```
@functions {
    int currentCount = 0;
    bool dataChanged = false;

    void IncrementCount()
    {
        currentCount += 2;
    }
    
    
    // I want this called whenever currentCount changes (from anywhere)
    void SetDataAsChanged()
    {
        dataChanged = true;
    }
}
```

Is this possible, or does it conflict with Blazor's design intentions?

**Comment by Lupusa87** [comment]
```
private int _currentCount;

public int currentCount
{
      get
        {
         return _currentCount;
        }
      set
        {
         _currentCount = value;
         SetDataAsChanged();
        }
}
```

**Comment by SteveSandersonMS** [comment]
This opens up the whole question of state containers, observability, and so on. It's certainly an area we're interested in (#27) but it will be a while before we consider doing anything built-in.

Right now you might want to look at [this MobX clone for Blazor](https://github.com/aspnet/Blazor/issues/27#issuecomment-417856705), which provides essentially the same observability you'll recognize from Knockout. It may be that in the long run, community-built state containers are the best solution and we choose to recommend that instead of building anything in. It remains to be seen, depending on what the community finds works best in practice.

**Comment by LaurenceFrost** [comment]
Great stuff - thank you for the response.
