### ISSUE TITLE
Blazor rewrite rule is far too broad

### ISSUE THREAD

**Issue by masonwheeler** [aspnet/Blazor#1410]
URL rewriting is important for making a SPA work, but the standard ASP.NET rewrite rule for Blazor is completely broken.  It essentially says "take any request that doesn't exist and treat it as a request for index.html", which means that requests for things that *should exist but don't* also return index.html instead of generating a 404, making debugging much more difficult.

What's needed is an analyzer that looks at the various `@page` directives and extracts a set of precise rewrite rules from them.

**Comment by csnewman** [comment]
Some people may want the 404 to be handled inside the client web app and either display a local 404 page or do some special behaviour. So it would need to be easily configurable.

**Comment by csnewman** [comment]
It's also worth noting that the rewrite rule is often set on nginx proxies etc (as advised by the docs).

**Comment by masonwheeler** [comment]
> Some people may want the 404 to be handled inside the client web app and either display a local 404 page or do some special behaviour. So it would need to be easily configurable.

Sure, but for this to happen, there needs to be a 404 in the first place.  Right now, there isn't.  What this means is that if your page references a resource (image, JS file, CSS file, etc) that you forgot to upload to the server, you don't get a proper error for it; you get a copy of index.html.  And no matter what the right solution is, that's simply wrong.

**Comment by csnewman** [comment]
I don't think the analysis of the routes is the best method, and instead you should be able to exclude paths instead (Like don't redirect /resources/ for example), as already happens with "/_framework/".

By doing path analysis, you only exclude unknown routes, but then what about unknown resources, such as an "/thread/{id}" endpoint. This would then require two separate 404 implementations, one at the serverside, and then only locally.

**Comment by masonwheeler** [comment]
I'll freely admit I'm no expert on the intricacies of rewriting rules, but is it truly a difficult thing to put a wildcard in one of them, so you can have a rule that rewrites "/thread/*" to index.html?

**Comment by SteveSandersonMS** [comment]
It's a good suggestion, and relates to suggestions that often come up in the context of ASP.NET Core's SPA templates (Angular, React, etc.).

However, we could only do this when the app was executing on the server. We can't (even theoretically) do it when you're running on WebAssembly, because you can use arbitrary code to determine URL matching on the client - you're not limited to static `@page` directives. The server has no way to know what the client-side logic is going to decide about the URL matching.

As such if this is really important to you, you could write some ASP.NET Core server-side middleware to inspect the incoming requests and preemptively return a 404 if you know it's not going to match any of your client-side routes (based on your own knowledge of your app's routing conventions). If it turns out to be really important to a lot of people, we could try to find ways to simplify that. Hope that's OK!

**Comment by masonwheeler** [comment]
> We can't (even theoretically) do it when you're running on WebAssembly, because you can use arbitrary code to determine URL matching on the client - you're not limited to static `@page` directives.

Really?  How's that done?

**Comment by SteveSandersonMS** [comment]
#293 includes allowing you to subclass `Router` and override the URL matching logic arbitrarily.

Shorter term, it's possible (though harder) to subscribe to the `IUriHelper`'s `OnLocationChanged` event to make your own router from scratch.

**Comment by masonwheeler** [comment]
So apparently if you go well out of your way to mess with the way routing works, then this idea won't work.  But if you have the technical knowledge to do so, you'll also know how to update the rewrite rules to compensate for it.  In the meantime, this proposal is still a good solution to 99% of the problem.  Please reopen.

**Comment by SteveSandersonMS** [comment]
Thinking about this more, the one realistic way we'd attempt this is as part of #24, so I'll add a note about it there.
