### ISSUE TITLE
Blazor is not re-rendering component when field is changed by mediator message handler

### ISSUE THREAD

**Issue by stanac** [aspnet/Blazor#1413]
### Functional impact
DOM is not updated

### Minimal repro steps
Repro repo here: https://github.com/stanac/BlazorNotRendering

### Expected result
DOM is updated when field changes.

### Actual result
DOM is not updated.

### Further technical details
For cross component messaging I have created a simple mediator class and registered it as singleton. One component is sending a message and the other one is handling it. Recipient of the message should update DOM from message handler, however it doesn't, field is changed (confirmed from log) however component is not re-rendered. First I thought the problem occurs when updating field from closure, however updating field from `Task.Run(() => { ... })` seams to work fine.

Button component that is sending the message:
```
@inject Mediator _mediator

<button onclick="@Increment">Increment</button>

@functions  {
    private async Task Increment()
    {
        Console.WriteLine("Button clicked, sending int message");
        await _mediator.Invoke<int>(1);
    }
}
```

Component that is handling the message:
```
@inject Mediator _mediator

<span>@counter</span>

@functions { 

    private int counter = 3;

    protected override Task OnInitAsync()
    {
        _mediator.Subscribe<int>(msg =>
        {
            counter++;
            Console.WriteLine($"int message recieved, counter value: {counter}");
            return Task.FromResult(0);
        });

        return Task.FromResult(0);
    }
}
```

Mediator (and repro project) are [here](https://github.com/stanac/BlazorNotRendering/blob/master/BlazorNotRendering.Client/Mediator.cs).

### Further technical details
- Blazor: 0.5.1
- Firefox: 62.0
- Chrome: 69.0.3497.92

Is there a workaround for this? Can we force Blazor to re-render component by invoking a method from base class?

**Comment by stanac** [comment]
It looks like there is a workaround, calling `base.StateHasChanged();` will re-render component.

**Comment by MarkStega** [comment]
> It looks like there is a workaround, calling `base.StateHasChanged();` will re-render component.

I don't think that is a workaround. I believe that is expected. As an example, your closure method basically creates an async task on the thread pool and then the handler completes and creates a re-render but nothing has changed so the UI remains static. Some time later that task increments the counter; there is no way that the UI will react to that if you don't tell it that the state has changed. I didn't look at the mediator example but I suspect the same issue exists.

**Comment by SteveSandersonMS** [comment]
Yes, as @MarkStega comments, this is expected. There isn't anything in your code that tells "Component that is handling the message" to re-render. You need to add a call to `StateHasChanged()` after your line that logs *int message recieved*.

Also you should beware that your code as-is probably leaks memory. You are calling `_mediator.Subscribe`, but there's no corresponding call to `_mediator.Unsubscribe`. You should probably do some kind of unsubscription in the component's `Dispose` method, otherwise `_mediator` will hold on to a reference to the subscriber forever. (I might be wrong about this since I haven't read the implementation of `_mediator` - I'm just guessing based on the pattern it looks like you're using).

Longer term we intend to provide better guidance around state management (#27) to eliminate the need to call `StateHasChanged` manually. Shorter term there are already some community-provided efforts to achieve this, such as the Blazor port of the MobX pattern at https://github.com/aspnet/Blazor/issues/27#issuecomment-417856705

**Comment by stanac** [comment]
@MarkStega interesting thing is that changing state from `Task.Run(() => { ... })` works fine, in this case there isn't a need to call `base.StateHasChanged();`

@SteveSandersonMS thank you for feedback on mediator and for pointing me to NObservable, it looks interesting (wasn't aware of MobX either).
