### ISSUE TITLE
await throws an exception

### ISSUE THREAD

**Issue by schovan** [aspnet/Blazor#142]
Await doesn't work, it always thows the same exception (it doesn't matter what I await).

Exception:
`MonoPlatform.ts:167`
`WASM: WASM doesn't support threading`
`WASM: Unhandled Exception:`
`WASM: System.TypeInitializationException: The type initializer for 'System.Threading.Timer' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Scheduler' threw an exception. ---> System.SystemException: Thread creation failed.`
`MonoPlatform.ts:167 WASM:   at System.Threading.Thread.StartInternal (System.Security.Principal.IPrincipal principal, System.Threading.StackCrawlMark& stackMark) <0x19838a0 + 0x00028> in <1463ae4ffad443ad96b6f1e233743309>:0 `
`WASM:   at System.Threading.Thread.Start (System.Threading.StackCrawlMark& stackMark) <0x1982db8 + 0x00052> in <1463ae4ffad443ad96b6f1e233743309>:0 `

Sample code:
@using System.Threading.Tasks
@(Layout<StandaloneApp.Shared.MainLayout>())
<h1>Hello, world!</h1>
<button onclick="@{ GetData();}">Run</button>
<p>Result: <strong>@result</strong></p>
@functions
{
    string result;
    public async void GetData()
    {
        await Task.Delay(1000);
        result = "ahoj";
    }
}

**Comment by muqeet-khan** [comment]
Yes, its a known issue as stated in #140

**Comment by danroth27** [comment]
We'll track this with #140.

**Comment by SteveSandersonMS** [comment]
Note that `async`/`await` itself does work. You can use them with `TaskCompletionSource`, for example. What doesn't yet work on Mono for WASM is any task whose implementation involves a timer (which is most of the useful ones).

**Comment by schovan** [comment]
Thank for the response.
Any idea how to download data as string over http in the current state?
@SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
> Any idea how to download data as string over http in the current state?

Yes, it's possible to implement your own `HttpClient`-equivalent, using a combination of `TaskCompletionSource` and the existing JS interop APIs. Until you're used to the existing low-level JS interop APIs this is very tricky so we wouldn't expect people to figure this out on their own. Here's an example of how it can be done: https://gist.github.com/SteveSandersonMS/ba34011dd4ee8bb3021c8837ff68ef28

Notes:

 * There isn't yet a public JSON-parsing API in the Blazor .NET package. There is an internal one that we will make public later as part of implementing built-in HttpClient support. So for now, you're limited to fetching plain strings. Some third-party JSON parsing packages *might* just plug in and work, but I doubt that Json.NET will do because it has such sophisticated dependencies on low-level reflection.emit features (and even if it does work, it will be slow because of that).
 * You might want to put a `try/catch` around any calls to `GetStringAsync` (and log any exception to the console) because otherwise if there's an exception, it will just silently do nothing. There isn't yet a built-in global event handler for async code.

**Comment by Terricide** [comment]
This might be a good json parsing library to use in Blazor.
https://github.com/facebook-csharp-sdk/simple-json
