### ISSUE TITLE
HTTP Error 502.5 - Process Failure

### ISSUE THREAD

**Issue by RudyMeijer** [aspnet/Blazor#1424]
Hi, 

I Installed the latest Blazor Language Services extension from the Visual Studio Marketplace in VS2017 15.8.4 and created a new project.
![image](https://user-images.githubusercontent.com/17112368/45570253-4e042380-b862-11e8-9295-fe3b8f30493b.png)

When i run the Blazor application (Ctrl+F5) without modifications i get the error:

![image](https://user-images.githubusercontent.com/17112368/45569911-4a23d180-b861-11e8-96fb-78aaf030047a.png)

![image](https://user-images.githubusercontent.com/17112368/45569725-acc89d80-b860-11e8-8ecc-843566443642.png)

The eventlogger shows:
![image](https://user-images.githubusercontent.com/17112368/45570060-b9012a80-b861-11e8-88c9-f6ce84846805.png)

**Comment by danroth27** [comment]
Yes, this is known issue with the global.json file included with the Blazor templates. It pins the SDK version to 2.1.3xx. If you don't that version installed on your machine (ex you have a newer version), then you get this error. This will be fixed shortly when we release 0.6.0, but for now you can workaround the issue by remove the global.json file from the project or by [installing SDK version 2.1.302](https://www.microsoft.com/net/download/dotnet-core/2.1). Sorry about the inconvenience!

**Comment by RudyMeijer** [comment]
About my VS info:
![image](https://user-images.githubusercontent.com/17112368/45570692-dc2cd980-b863-11e8-8c4b-05ba713f6a48.png)

**Comment by OzBob** [comment]
@danroth27 - sorry to bring this up too, but I'm following along with you on Ignite 2018 https://www.youtube.com/watch?v=tAa6fQQ5Ro4 and getting the same error.

Removing the global.json file as you suggest kills the project.

Putting the locally installed hightest SDK version in the global.json works.

@RudyMeijer  
I've got dotnet 2.1.3 (not 2.1.300) installed, and am getting the same error, but it turns out I've got '2.1.500-preview-009297' of the dotnet **SDK**.

To find the highest version of the dot net SDK run this script in the Powershell ISE:

```
  $runtimes = [Collections.Generic.List[string]];
  $runtimes = (ls "$env:programfiles/dotnet/shared/Microsoft.NETCore.App").Name
  $runtime = $runtimes[$runtimes.Length-1]
  $runtime
  cd $env:programfiles/dotnet/shared/Microsoft.NETCore.App
  cd $runtime
  dotnet --version
```

copy and paste the last string into your global.json file:

```
{
  "sdk": {
    "version": "<<highest sdk version>>"
  }
}

```

**Comment by deanchalk** [comment]
Quick note for anyone still struggling with this, I followed all of the advice. Added a correctly configured global.json (because one no longer comes in the blazor templates) which still didn't work.
Out of desperation I uninstalled .NET Core v3.0 (preview) that I had installed in order to checkout some new WPF stuff, removed global.json, and suddenly it just worked
