### ISSUE TITLE
NRE exception with Newtonsoft.Json

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Blazor#1433]
Hi

This PR was raised for Newtonsoft.Json - https://github.com/JamesNK/Newtonsoft.Json/pull/1828
I thought this issue was fixed with a linker configuration change - https://github.com/mono/mono/issues/8872

Can you double check that this fix is shipping with Blazor so it Just Works for users.

**Comment by danroth27** [comment]
Hi @JamesNK. 

We had originally planned to relax our IL linker config to link less stuff so that Json.NET would just work, but that has the downside of significantly growing the app size. Instead, the mono folks are working on some runtime changes to [how LINQ expressions are handled](https://github.com/aspnet/Blazor/issues/1316#issuecomment-421060433) that we hope will address the issue. 

@marek-safar can provide more details on the proposed changes.
