### ISSUE TITLE
Solution isn't opened properly in Visual Studio for Mac

### ISSUE THREAD

**Issue by godrose** [aspnet/Blazor#144]
Steps to repro:

1. Clone the repo
2. Open `Visual Studio for Mac`
3. Open the `Blazor.sln`

**Expected**: Solution opens correctly with all projects loaded properly
**Actual**: The following error message is displayed *Error while trying to load the project '/Users/{user}/Workspace/Blazor/src/Microsoft.AspNetCore.Blazor.Razor.Extensions/Microsoft.AspNetCore.Blazor.Razor.Extensions.csproj': Project does not support framework '_,Version=v0.0'*

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know. Could you please report this to Visual Studio for Mac? My guess is that the issue is that they aren't recognising how Microsoft.AspNetCore.Blazor.Razor.Extensions.csproj declares its target framework .

Although it's important that Blazor apps themselves can open in VS for Mac, it's much less important that `Blazor.sln` works there, because you only need that when working on Blazor itself, so it's not something we'd prioritise trying to work around.

There will be a project template you can use on any development platform within the next few weeks. Hope that's OK!
