### ISSUE TITLE
Select is having issues

### ISSUE THREAD

**Issue by KnottStudios** [aspnet/Blazor#1446]
VS 2017 15.8.4
<Select> causes a page not to load.
Tested with code directly from this github site.
See attached file.
![snippet](https://user-images.githubusercontent.com/17166749/45720595-6af26c80-bb6a-11e8-8eea-490012f7beae.PNG)

**Comment by KnottStudios** [comment]
![snippet](https://user-images.githubusercontent.com/17166749/45720631-878ea480-bb6a-11e8-8a8d-b249ae95cbbe.PNG)

**Comment by danroth27** [comment]
I think you're hitting a naming conflict with the HTML `<select>` element and your `select.cshtml` component. For each component file we generate a component class that has the same name as the name of the file. You can see that the `<select>` element is showing up as purple, which means Blazor thinks it's a component instead of a normal HTML element. Try renaming `select.cshtml` to something else, like `Selector.cshtml`. If that doesn't fix the issue let me know.
