### ISSUE TITLE
Authentication / Authorization for server side Blazor

### ISSUE THREAD

**Issue by awesomeaaron** [aspnet/Blazor#1449]
Hi,
I would like to implement authentication/authorization for a server side Blazor app. For MVC app, we use session/cookie and for api we can use oauth / openid. What is the preffered way of doing authentication / authorization for a server side Blazor app.

**Comment by SteveSandersonMS** [comment]
You could either:

* Use authentication to control access to *all* routes to your server (with the exception of login pages, which might be rendered server-side rather than as a Blazor app). Traditional session/cookie methods will work.
* Or, use authentication to control access to API endpoints only. This is more typical for SPA-type apps, whether it's Blazor or React or Angular or anything else like that. You can implement a Blazor UI for logging in which sends credentials to a server-side API endpoint, which in turn returns some kind of auth token that the client will send with subsequent requests. There are many options for how to do this ([examples](https://jonhilton.net/2017/05/03/login-authentication-asp-net-core-web-api-big-picture/)).

**Comment by danroth27** [comment]
Duplicate of #64
