### ISSUE TITLE
JsonConvert.SerializeObject fails

### ISSUE THREAD

**Issue by mercersoft** [aspnet/Blazor#1451]
I am trying to serialize a simple class to JSON (using Newtonsoft.JSON) using the code below, but the request fails with the following error: 

**WASM: [Newtonsoft.Json.JsonSerializationException] Error setting value to 'Name' on 'Blazor1.Client.Pages.Index+Foo'.**

I have added the following block to the default Blazor (0.5.0) Project:

```
@functions
{
    protected override async Task OnInitAsync()
    {
        string content = "{ \"name\" : \"PHS\" }";
        Foo foo = JsonConvert.DeserializeObject<Foo>(content);
        var bar = JsonConvert.SerializeObject(foo);
    }

    public class Foo
    {
        public string Name { get; set; }
    }
}

```

**Comment by danroth27** [comment]
There currently are issues with using Json.NET in a Blazor app due to how we use the IL linker to try to strip out unused code. Can you try disabling the linker and see if that fixes the issue for you? In your project file add `<BlazorLinkOnBuild>false</BlazorLinkOnBuild>`.

We are working with the mono runtime time on a better long term fix for this issue.

**Comment by mercersoft** [comment]
Thanks - that did the trick! Looking forward to a long term fix. How do I find out if/when it is fixed?

**Comment by SteveSandersonMS** [comment]
@mercersoft Each release is published with release notes. When Json.NET works out of the box (hopefully in 0.7.0), we will definitely mention that.
