### ISSUE TITLE
Microsoft.JSInterop.d.ts not available

### ISSUE THREAD

**Issue by OmarTawfik** [aspnet/Blazor#1452]
I looked through the codebase, npm, and nuget, but couldn't figure out where it is published to.
I want to write my client side interop in TypeScript, and I want to refer to `DotNet.invokeMethod` and other functions in that file, but I cannot figure out where to reference the `.d.ts` from. Is that a WIP?

https://github.com/aspnet/Blazor/blob/0.5.1/src/Microsoft.JSInterop/JavaScriptRuntime/src/Microsoft.JSInterop.ts

**Comment by RyoukoKonpaku** [comment]
It's still not done yet. You can track the issue here #661. For now what I do is generate custom ```d.ts``` for it for now since I myself use Typescript for interop as well.

**Comment by SteveSandersonMS** [comment]
As @RyoukoKonpaku mentions, it's not yet published. It will go onto NPM (since it's a JS package), and will include TypeScript typings in the conventional way so you don't have to install any `.d.ts` file manually. As it happens, #661 is really for a different matter though (typings for the Blazor APIs rather than the Microsoft.JSInterop ones).

As a stopgap measure, you can clone the https://github.com/dotnet/jsinterop repo and build it yourself. That will generate the `.d.ts` file in its `dist` output directory.
