### ISSUE TITLE
Code obfuscation in Blazor

### ISSUE THREAD

**Issue by BenjaminLinus1964** [aspnet/Blazor#1463]
The code obfuscation helps us convert source code into completely unreadable form, preventing it from analyzing and theft etc. What tool or approach offers Blazor? Thanks in advance.

**Comment by Lupusa87** [comment]
I am interested too, I had case in the past when I wanted to protect source code from disassembling and this was very sensitive.
This is not relevant for Server Side Blazor because code never reaches client but for Client side blazor I would love to have option to protect my app's code form anyone's eyes.

**Comment by RyoukoKonpaku** [comment]
If I remember there's a bunch of .Net obfuscator tools out there, it'll probably work at the moment since it's still .Net dlls and when AOT gets done I'd assume if you really want to obfuscate it'll be going through two phases which might make it really hard to disassemble easily.

I'd assume it'd be like this: .Net IL > Obfuscate > AOT > wasm. The result prolly won't be easy to reverse at least compared to JS minifying.

**Comment by danroth27** [comment]
We don't plan to provide built-in support for code obfuscation, but as @RyoukoKonpaku mentioned you should be able to use existing .NET obfuscator tools, since Blazor apps are normal .NET dlls. Hope this helps!

**Comment by BenjaminLinus1964** [comment]
thank you all
