### ISSUE TITLE
Asp.Net hosted template solution only contains shared project

### ISSUE THREAD

**Issue by MBotman** [aspnet/Blazor#1468]
When generating a new Blazor project using the "Blazor (ASP.NET Core hosted)" template, a solution is generated with only the shared project in it. The other projects are created but not included in the solution.

Win10, VS2017 15.8.5, dotnet 2.1..402

**Comment by tusharparik** [comment]
Similar issue 
![image](https://user-images.githubusercontent.com/4800894/45994000-4426bf80-c0af-11e8-8894-abd260b12043.png)

**Comment by tusharparik** [comment]
Thanks for the help. Will check it today and get back.

**Comment by MBotman** [comment]
Hi ZeoxZeos,
Thank you for your answer. I do however not see how this is related to the global.json issue, could you explain? Although it is possible to load the projects into the solution by hand, I still think this is a bug.

**Comment by tusharparik** [comment]
Hi ZeoxZeos,
The problem seems to be same when creating project from Visual studio for Blazor Hosted & Server Sider project. But creating in CLI with dotnet new and then deleting the .json file is a workaround found.

**Comment by ZeoxZeos** [comment]
Hi Tushar,
Your suggestion is good one.
But Just to inform you there is 0.6 preview of blazor.
https://github.com/aspnet/Blazor/releases/tag/0.6.0-preview1

The issue is resolved
https://github.com/aspnet/Blazor/pull/1386


Regards,
Zenon Iwanicki
New Tel:00447944648249
SKYPE: zeoxzeos
TWITTER: @ZIwanicki
http://www.linkedin.com/in/zenoni

________________________________

**Comment by tusharparik** [comment]
Thanks and noted
