### ISSUE TITLE
TimeZone in Blazor server-side

### ISSUE THREAD

**Issue by cores-system** [aspnet/Blazor#1480]
Hello, how do I install a single TimeZone in Blazor.Client ?
Blazor server-side 5.1

```
<div>
    @DateTime.Today<br />
    @Json.Serialize(DateTime.Today)
</div>
```
**output**:
25.09.2018 0:00:00 
2018-09-24T21:00:00Z

**Comment by SteveSandersonMS** [comment]
Could you clarify what you're trying to do? Sorry but I'm unsure what you mean by "install a TimeZone".

**Comment by cores-system** [comment]
@SteveSandersonMS, I'm in `ua-UA`, in order to pass the time through `Json.Serialize(DateTime.Today)` it should have a format `2018-09-25T00:00:00+03:00` instead of `2018-09-24T21:00:00Z`

Writing in mssql `2018-09-24T21:00:00Z` I get `2018-09-24T21:00:00` instead of `2018-09-25T00:00:00`

**Comment by cores-system** [comment]
```
<div>
    @Newtonsoft.Json.JsonConvert.SerializeObject(DateTime.Today)<br />
    @Json.Serialize(DateTime.Today)
</div>
```

**output**:
`2018-09-25T00:00:00+03:00` - That's it
`2018-09-24T21:00:00Z` - Wrong

**Comment by SteveSandersonMS** [comment]
The timestamps `2018-09-25T00:00:00+03:00` and `2018-09-24T21:00:00Z` both represent the same moment, so technically they are both correct (the `Z` prefix on the latter means `+00:00`). However I guess you want to format the timestamp using some specific timezone.

Since specific timezones matter to you, you should [use DateTimeOffset instead of DateTime](https://blogs.msdn.microsoft.com/davidrickard/2012/04/06/datetime-and-datetimeoffset-in-net-good-practices-and-common-pitfalls/).

Example: `Microsoft.JSInterop.Json.Serialize(DateTimeOffset.Now)`
Output: `"2018-09-26T11:26:01.2811526+01:00"` (for me, since I'm currently on BST, i.e. +01:00).

The `DateTimeOffset` structure is unambiguous about your preferred timezone representation, so that's the one to use for this kind of scenario.
