### ISSUE TITLE
Wrong source code formatting in cshtml file

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/Blazor#1482]
In any cshtml file write this (note there is no space between `@functions` and `{`):
```c#
@page "/"
<h1>Hello</h1>
@functions{
    protected override void OnInit()
    {
        base.OnInit();
        int i = 1;
        if (i != 0)
        {
            Console.WriteLine(i);
        }
    }
}
```
`OnInit` function is correctly indented. Now add space between `@functions` and `{` or move `{` to new line (which is more natural C# formatting) and reformat document.
```c#
@page "/"
<h1>Hello</h1>
@functions
{
protected override void OnInit()
{
    base.OnInit();
    int i = 1;
    if (i != 0)
    {
        Console.WriteLine(i);
    }
}
}
```
This time `OnInit` function is not indented which is wrong.

**Comment by danroth27** [comment]
Hi @Andrzej-W.

Thanks for reporting this! The formatting in cshtml files is actually not handled by Blazor at all, but it performed by the Razor editor in VS. To get this feedback to the correct team could you please submit this feedback through the VS feedback tool or on https://developercommunity.visualstudio.com/?

Since this issue is really external to Blazor I'm going to go ahead and close. I hope that's ok!
