### ISSUE TITLE
Strange excption in OnInit

### ISSUE THREAD

**Issue by kant2002** [aspnet/Blazor#1506]
I following scenario in 0.6.0 preview
```
protected override void OnInit()
    {
        this.scoreOptions = new API.GetScoreOptions();
    }
```

This is results in the 
```
WASM: 13
```

This is quite a magic for me. I understand that this may be not an issue with Blazor itself but with Mono, but trying anything in OnInit always give me all kind of funny errors.

**Comment by RemiBou** [comment]
Do you have any call to Console.WriteLine in GetScroptOptions ? They are prepend by "WASM" and put on the browser console

**Comment by kant2002** [comment]
No, I have only AutoRest generated client there. It is called synchronously.

**Comment by SteveSandersonMS** [comment]
Sorry for the bizarre error message. I don't know what that means either.

Can you supply a minimal and self-contained repro so we can investigate?

**Comment by kant2002** [comment]
@SteveSandersonMS See issue here: https://github.com/kant2002/BlazorWasm13

**Comment by SteveSandersonMS** [comment]
Ah, I see. Thanks for posting the repro!

The issue is that you're trying to block the UI thread, which is not possible. The entire JS runtime doesn't allow the thread to be blocked. In .NET terms, if you have a task, you can `await` it, or you can `ContinueWith` after it, but you *cannot* call `.Wait()` or `.GetAwaiter().GetResult()` or evaluate `.Result` for tasks that aren't yet completed.

Specifically, it's this line:

```csharp
var x = GetTaskAsync().GetAwaiter().GetResult();
```

This is why there's an async version of `OnInit` (i.e., `OnInitAsync`), so you can do things asynchronously.

Separately, the error message `13` is clearly bizarre. If you'd be willing to report this to http://github.com/mono/mono, pointing out that it's a strange error for Mono WebAssembly to throw if you try to block on a task, then hopefully they will be able to make it easier to understand.
