### ISSUE TITLE
support help in Blazor cli

### ISSUE THREAD

**Issue by Meir017** [aspnet/Blazor#1513]
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RunCommand>dotnet</RunCommand>
    <RunArguments>blazor serve</RunArguments>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Browser" Version="0.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="0.6.0" PrivateAssets="all" />

    <DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli" Version="0.6.0" />
  </ItemGroup>

</Project>
```
using blazor `0.6.0`

after running `dotnet new blazor` and then `dotnet blazor -h`
an `InvalidOperationException` is thrown.

is there any reason why blazor does not use the `CommandLineApplication`?

**Comment by SteveSandersonMS** [comment]
> is there any reason why blazor does not use the CommandLineApplication?

The `blazor` CLI was one of the very first parts of the system we built, and is mostly intended to be an internal implementation detail. There aren't currently any reasons why developers need to run it manually, since it only has one feature, "serve", and that's done for you automatically when you execute `dotnet run`. So, adding a help system has never been a high priority.

If this is something you feel strongly about, we'd certainly consider a PR for this if it followed the same patterns as the other `Microsoft.Extensions.CommandLineUtils`-based tools in the repo, e.g., `Microsoft.AspNetCore.Blazor.BuildTools`. Thanks!
