### ISSUE TITLE
Components could expose properties using public instead of Parameter 

### ISSUE THREAD

**Issue by mattd73uk** [aspnet/Blazor#1521]
Hi,
As per the VS template project, to be able to assign to a component
`<SurveyPrompt Title="How is Blazor working for you?" />`

currently the child component needs Title to have the Parameter attribute:
```
 [Parameter]
 string Title { get; set; } 
```

I am new to the project, so forgive any newbie foolishness, but can't we drop the ParameterAttribute and simply say that child component properties which are _public_ can be assigned to by the parent?
To me this is the intention of C# public/private access modifiers.

I'd like to contribute to the project & have a go at this if it was thought sensible.
Thanks
Matt

**Comment by vertonghenb** [comment]
The attribute is used for multiple purposes but the main one is encapsulation a component should not expose it's properties as public. Since it breaks the entire idea of manipulating state.

On the other hand, if we use the attribute we can set the parameter as Required or optional in a later stage.

**Comment by Andrzej-W** [comment]
In this sample project a constant string is assigned to a parameter but in more real world scenario you will want to pass different values depending on user actions. When you change parameter value component will be rendered automatically and you will see a change on the screen. You can change public property but component **will not** rerender automatically and you will have to implement property setter and call `StateHasChanged()`.

**Comment by SteveSandersonMS** [comment]
Thanks for the answers, @vertonghenb and @Andrzej-W!

**Comment by mattd73uk** [comment]
Hi, @Andrzej-W thank you for your response, I do appreciate you taking the time to help me understand.   But can I ask, isn't it the case that the reason that parameters auto update (but public properties don't) is because of the StateHasChanged() call within the implementations of IComponent SetParameters(ParameterCollection parameters) ?  For public properties to be auto updated on change, all it would require is changing ParameterCollectionExtensions GetBindableProperties to just look for public properties, not ones flagged with the ParameterAttribute?  There may be good reasons for not doing this, I'm just making sure I'm right on the mechanics.

@vertonghenb thank you for the response, as you can see I need all the help I can get :-).  However, I am unclear on what you mean.  The purpose of the ParameterAttribute is to expose a member of a component so it can be bound to.  Can you help me understand how exposing a component member through the ParameterAttribute doesn't "break the entire idea of manipulating state and rerendering", but exposing it through a public property does?  To my limited understanding the Blazor ParameterAttribute and C# "public" access modifier are simply keywords saying "expose me".  The only difference (to me) is that the former is Blazor framework specific, and the latter is a C# / .Net standard.

**Comment by demigor** [comment]
@mattd73uk exactly my thoughts. However I would go further and allow fields as well. 

Because properties are needed only if you want to do some extra in setter or getter. Otherwise, field is enough. 

Moreover, setting a field was like 20 times faster than setting a property last time I measured. (Of course, via reflection setting both properties and fields is equally slow and should be avoided).

**Comment by sven5** [comment]
@demigor 
Using public fields has never been a good idea. Read [here](https://softwareengineering.stackexchange.com/questions/161303/is-it-bad-practice-to-use-public-fields)

You are better with never ever use public fields.

**Comment by demigor** [comment]
Not convinced, because:
1) if one needs to inspect in setters, feel free to opt in as a property. Not needed for Razor components.
2) Databinding? Not relevant for Razor components.
3) Different accessibility? Not relevant for public attributes of your component. They must be public anyway.
4) Reflection? It work the same way for props and fields anyway. Fast delegates for field setter and getter are easy to implement.
5) Use best practices from different problem field is just wrong.

Kind regards

On Jan 11, 2019 17:10, Sven Glöckner <notifications@github.com> wrote:

@demigor<https://github.com/demigor>
Using public fields has never been a good idea. Read here<https://softwareengineering.stackexchange.com/questions/161303/is-it-bad-practice-to-use-public-fields>

You are better with never ever use public fields.
