### ISSUE TITLE
 cshtml as script template

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#153]
Please consider how a blazor page/view and or function could be used to generate output as a HTML script template of a given type handlebars,knockout,jquery etc.

**Comment by muqeet-khan** [comment]
I had put the following in gitter, but, I think this issue is kind of asking along the same lines. 
 
Trying to figure out what the recommended strategy is to include a `<script>` or a `<script>` dependency in a Blazor component. For example,
```
<div class="col-lg-12 col-md-12">
    <div class="jumbotron">
        <h3> This is a header component.</h3>
    </div>
</div>

@*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>*@
<script>
    var jq = document.createElement("script");
    jq.onload = function () {
        if (window.jQuery) {
            console.log('jQuery is loaded, so now go do something cool with it.');
            runJqueryStuff();
        } else {
            console.log("jQuery is not loaded");
        }
    };
    jq.src = "https://code.jquery.com/jquery-3.3.1.min.js";
    jq.integrity = "sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=";
    jq.crossOrigin = "anonymous";
    document.getElementsByTagName("head")[0].appendChild(jq);
</script>
<script>
    function runJqueryStuff() {
        $('.jumbotron > h3').append("Updated from jquery, loaded from a Blazor component.");
    }
</script>
``` 
the 1st  `<script>`tag does not work as jQuery is not defined properly when called later. The only way I have it working for now is to load it through javascript and run my jQuery code through the onload event. Is there a better way to do this?

**Comment by SteveSandersonMS** [comment]
Normally you should put your `<script>` tags in `index.html` so they load up front in the normal way. Putting one in a Blazor component is not a typical scenario, though for now at least is stopping you. This works:

    <script>function doStuff() { alert(jQuery) }</script>
    <script onload="doStuff()" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

To have a successful experience with Blazor you should think of it like other SPA frameworks such as React or Angular. That is, you should use Blazor itself to present and update your UI. If you modify the Blazor-controlled DOM via an external tool like jQuery then you're in a world of unsupported weirdness. Blazor can't necessarily update your UI correctly if it doesn't match the state it expects (just like React or others can't in the same situation).

I'll close this because I hope it's resolved the question, but please let me know if not.
