### ISSUE TITLE
Suggestion: Have BlazorComponent Implement INotifyPropertyChanged, Expose Protected OnPropertyChanged Method

### ISSUE THREAD

**Issue by legistek** [aspnet/Blazor#1532]
In all my experimenting with Blazor the very first thing I always do is add `INotifyPropertyChanged` implementations to my components so I can engage in two way data binding (I use a home-grown .NET Standard-friendly data binding scheme that uses reflection and `INotifyPropertyChanged`) and otherwise subscribe to state changes without having to be inside the component itself.

It would be really convenient if `BlazorComponent` implemented `INotifyPropertyChanged` and exposed a `protected void OnPropertyChanged([CallerMemberName] string name = null)` method for derived classes to invoke.

Any thoughts on this? I'd be happy to take this on as it should be a fairly trivial task. 

Thanks!

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. We're not planning to bake in `INotifyPropertyChanged` as a required pattern within Blazor, because various other patterns are also used and considered preferable depending on your overall architecture.

However if you do want all your components to have the same infrastructure around this, you can create your own component base class that inherits from `BlazorComponent`, and then make all your components inherit from that. Then you won't have to keep repeating your infrastructure. Hope that helps!

**Comment by Lupusa87** [comment]
I use INPC in my blazor apps and it works great, simpler code and more control.
