### ISSUE TITLE
Define routeable components in a library

### ISSUE THREAD

**Issue by jmezach** [aspnet/Blazor#1570]
So I'm not even sure if this is supposed to work, but I was expecting it would. I have created a new Blazor application hosted in an ASP.NET Core application. I then added a Blazor library project to my solution and added a reference to that library from the Client project. Now I've defined a component with an @page attribute and was expecting to be able to route to that component, but that does not seem to work.

I can see that the library is being loaded over the network, but when I try to navigate to the route of the component I get an error in the console stating that no component could be found at that route. So I'm guessing it's not finding the component with the @page attribute. Is this by design?

**Comment by enetstudio** [comment]
I believe you can embed your component in a parent component. This should work...
As far as I know, components should be placed in the Pages folder and have a @page directive with a route template to be part of the routing mechanism... Your poor component is not a routed component.

**Comment by danroth27** [comment]
@jmezach It should work. Routable components are just component classes that have a generate route attribute based on the `@page` directive (the folder is actual inconsequential). But there is one additional step: you need to add `@addTagHelper *, BlazorLib1` in the app for the components in that library to get picked up. We hope to improve Blazor in the future to make this step unnecessary. I hope this helps!

**Comment by SteveSandersonMS** [comment]
@jmezach Currently it's intentional that routing only looks for components in the main application assembly. TBH I'm not 100% sure that's enforced completely, but that is the intention, so if you do find some workaround that routes to a class library, you'd be relying on a bug that might get fixed. The reason is that longer term, we want to have a comprehensive feature for mounting subapplications from external assemblies on specific URL prefixes, so any way of doing it now might break later.

About dynamically loading components, that should be viable as far as I know, but haven't directly tried it. Certain things such as routing cache information about all the components they know about, so for example routing will not discover any newly-added components after it has built the initial route table, but as discussed above, that's not a supported scenario today anyway. As for writing your own `OpenComponent<T>` calls inside a `RenderFragment` and having them referencing components in dynamically-loaded assemblies, that *should* work.
