### ISSUE TITLE
Request: ability to write Blazor component libraries

### ISSUE THREAD

**Issue by conficient** [aspnet/Blazor#158]
One feature I'd love to see is the ability to write Blazor component libraries, where the code and UI (using the Razor pages) can be compiled to a DLL which can be packaged (e.g. Nuget) and re-used as a library.

This would
  1 Make application development more modular than it currently is
  1 Encourage an ecosystem of web components (both open source and commercial tools) which would also then foster greater adoption of Blazor

Hence it would be good to see both a Blazor web application template and a Blazor library template.

**Comment by RyoukoKonpaku** [comment]
I think that's somewhat possible already on the new preview builds of the Razor engine. If I remember the new Razor Engine now allows to be compiled to a .Net standard library along with all its pages/cshtml and assets. The best part about the new build for that engine is that you have the ability to override the library page/views for more possibilities on how a vendor would make his component flexible.
[Here's the ASP.NET Video discussing the it.](https://www.youtube.com/watch?v=6eVdRyXADaw&list=PL1rZQsJPBU2StolNg0aqvQswETPcYnNKL&index=0)

So I do think i'd be possible here since it uses the Razor engine for it's rendering for Blazor.

**Comment by SteveSandersonMS** [comment]
This is already the case. When Blazor's build system compiles your `.cshtml` files, they just turn into types in the application's .NET assembly. At runtime we don't see `.cshtml` as a concept at all - it's all just .NET types.

So if some of those .NET types happen to be in referenced assemblies (e.g., from NuGet packages), it makes no difference - that just works equally well.

**Comment by conficient** [comment]
Thanks for the clarification - is there a reason I could not see the generated types in a unit test assembly? All I could see was Program.cs.

Good work on Blazor by the way - I might have to stop using KnockoutJS if this becomes a product!

**Comment by muqeet-khan** [comment]
Do we need to "register" a component coming from a library into the Blazor app for it to be discoverable? or are all components found automatically at runtime?

I am trying to access a sample component from a library and cannot.

**Comment by SteveSandersonMS** [comment]
Currently it's necessary to add the following to your root `_ViewImports.cshtml` if you want components from external projects/packages to show up:

    @addTagHelper *, AssemblyNameOfProjectOrPackage
