### ISSUE TITLE
Is there any roadmap for Blazor?

### ISSUE THREAD

**Issue by a3diaz** [aspnet/Blazor#1602]
I'm thinking about to use blazor for a new requiriment in the job, but since it's an experimental technology I would like to know if is there any roadmap or planning for the product; for example, It's already an offical Microsoft Product? and It's a fact that Blazor reach any stable versión (I guess that I and thousands of developers really hope so)?

**Comment by enetstudio** [comment]
Do you know who's Daniel Roth ? If you don't then you should know...
The following was said by him: 
Razor Components to ship with ASP.NET Core in .NET Core 3.0
We announced last month at .NET Conf that we've decided to move forward with shipping the Blazor server-side model as part of ASP.NET Core in .NET Core 3.0. About half of Blazor users have indicated they would use the Blazor server-side model, and shipping it in .NET Core 3.0 will make it available for production use. As part of integrating the Blazor component model into the ASP.NET Core we've decided to give it a new name to differentiate it from the ability to run .NET in the browser: Razor Components. We are now working towards shipping Razor Components and the editing in .NET Core 3.0. This includes integrating Razor Components into ASP.NET Core so that it can be used from MVC. We expect to have a preview of this support early next year after the ASP.NET Core 2.2 release has wrapped up.

Our primary goal remains to ship support for running Blazor client-side in the browser. Work on running Blazor client-side on WebAssembly will continue in parallel with the Razor Components work, although it will remain experimental for a while longer while we work through the issues of running .NET on WebAssembly. We will however keep the component model the same regardless of whether you are running on the server or the client. You can switch your Blazor app to run on the client or the server by changing a single line of code. See the Blazor .NET Conf talk to see this in action and to learn more about our plans for Razor Components:

Source: https://blogs.msdn.microsoft.com/webdev/2018/10/02/blazor-0-6-0-experimental-release-now-available/
