### ISSUE TITLE
Is there any local database for Blazor?

### ISSUE THREAD

**Issue by a3diaz** [aspnet/Blazor#1603]
Actually is there any local database implemetation for Blazor? For example, WebSQL, IndexedDB or some EntityFramwork implementation (such as SQLite)

**Comment by enetstudio** [comment]
See this: https://github.com/wtulloch/Blazor.IndexedDB

**Comment by 3x0dv5** [comment]
Take a look at this please. 
https://blazor.net/community.html 

Creating issues to ask questions doesn't seem very helpful.

**Comment by RyoukoKonpaku** [comment]
A lightweight EF provider for IndexDb might be a neat idea in the future for some web apps.

**Comment by lohithgn** [comment]
@RyoukoKonpaku any pointer to developing custom EF providers ?

**Comment by SteveSandersonMS** [comment]
Thanks for the answers, everyone!

**Comment by RyoukoKonpaku** [comment]
@lohithgn sadly documentation is still a bit lacking for writing providers on EF Core, the best place to get a picture of how it's done is checking the existing implementations for providers on the ef core GitHub repo. Here's the SQLite provider for EF core for an example [GitHub link](https://github.com/aspnet/EntityFrameworkCore/tree/release/2.2/src/EFCore.Sqlite.Core
).

**Comment by danroth27** [comment]
@lohithgn I'm sure the EF Core folks would be happy to point you in the right direction if you want to try to create an EF Core provider for IndexdDB that works in Blazor. @divega @ajcvickers

**Comment by lohithgn** [comment]
@RyoukoKonpaku @danroth27 thanks … will see what i can come up with. will wait for what @divega and @ajcvickers - if they have any pointers for me :)

**Comment by Reshiru** [comment]
@RyoukoKonpaku a bit late to the party but i'm currently trying my best to implement something like this. Because of the nature of IndexedDb i'm not using EFCore but try to make anything look and feel like it. 
_Except the async part, which is neccessary (instead of using(var db = Func<>) you have to use it in an async context using(var db = async Func<>))_
It currently supports some basic stuff and will be expanded in the upcoming weeks c:
[Reshiru.Blazor.IndexedDB.Framework](https://github.com/Reshiru/Blazor.IndexedDB.Framework)
Maybe this helps :)
