### ISSUE TITLE
Build failed - v 0.60 with Microsoft.EntityFrameworkCore.SqlServer

### ISSUE THREAD

**Issue by IyyappanAmirthalingam** [aspnet/Blazor#1664]
Hi,
When I tried to build the Blazor (standalone) Version 0.6.0 after installing Microsoft.EntityFrameworkCore.SqlServer the build is failing. 

> Steps to reproduce
> 1. Create a new Blazor (standalone) app
> 2. Install Microsoft.EntityFrameworkCore.SqlServer
> 3. Build the solution to see the error.

Verified in Visual Studio 2017 and Visual Studio code . Please help.
Thanks.

**Comment by MovGP0** [comment]
the user interface may not have any dependency on the database.

https://youtu.be/_lwCVE_XgqI

**Comment by SteveSandersonMS** [comment]
Indeed, I don't expect `Microsoft.EntityFrameworkCore.SqlServer` to be supported under WebAssembly. 

Generally it wouldn't be applicable to use that directly from the client, because doing so would imply your database allows direct incoming connections from arbitrary clients. This is typically a serious security risk.

The normal architecture is to have your clients invoke API endpoints on a web server, and for the web server in turn to make connections to your SQL database.
