### ISSUE TITLE
Update FAQ "Q: What about older browsers that don't support WebAssembly? For example, does Blazor work in IE?"

### ISSUE THREAD

**Issue by IvanJosipovic** [aspnet/Blazor#1665]
> Q: What about older browsers that don't support WebAssembly? For example, does Blazor work in IE?
For older browsers that don't support WebAssembly Blazor will fallback to using an asm.js based .NET runtime. Using asm.js is slower and has a larger download size, but is still quite functional.

> 

Wiki Faq needs to be updated to remove reference of asm.js

**Comment by SteveSandersonMS** [comment]
Thanks - done.

**Comment by binki** [comment]
Where is the rationale for this removal and which commit removed it from the README?

**Comment by SteveSandersonMS** [comment]
@binki We found that the performance of the asm.js fallback was unlikely to be adequate, and it was expensive to maintain. Since all recent browsers support WebAssembly, and since people who need IE11 support can consider server-side Blazor, we felt that our time was better spent in other areas than maintaining this.

> commit removed it from the README

Not sure, but you could check the git history.

**Comment by binki** [comment]
Thanks.

In stumbling around myself, I found https://github.com/aspnet/Blazor/commit/4006cd543900fcc1cf76cd75a1b24007e60c8a67 . According to the commit message, the asm.js fallback was removed because the project switched to mono’s binary distribution which provides wasm but not asm.js.
