### ISSUE TITLE
Using Blazor serverside and HttpWebRequest I get service not available

### ISSUE THREAD

**Issue by clemenslinders** [aspnet/Blazor#1707]
LS,

As I understand using the serverside Blazor there is a lot more possible.
I want to transfere a MVC solution into Blazor.

This MVC solution uses HttpWebRequest to get data from a server.
But when I use this in my Blazor server side solution I get the error 503: Service not available.

Of course the service is available and up and running.

Is there something I can do so that I do not get this error??

Kind regards,

Clemens Linders

**Comment by enetstudio** [comment]
Where is your code, mate ?
Did you try HttpClient ? server-side Blazor or client-side
Still better (server-side Blazor) use HttpClientFactory Directly (is supposed to be supported in the future)

**Comment by clemenslinders** [comment]
Hi EnetStudio,

Thanks for your reply. I tried this debugging on a client-side Blazor application. After that I tried the same application server side (which gave me the error 503 service cannot be reached).

Here is my code:

            private Stream Post_Data(string _uri, byte[] _postDataArray, List<KeyValuePair<string, string>> _headers)
            {
                HttpWebRequest _request = (HttpWebRequest)HttpWebRequest.Create(_uri);
                _request.KeepAlive = false;
                _request.Timeout = myRequestTimeOut;
                _request.Method = "POST";
                _request.ContentType = "application/x-www-form-urlencoded";
                _request.ContentLength = _postDataArray.Length;

                if ((_headers != null))//Added 25-11
                {
                    foreach (KeyValuePair<string, string> _kv in _headers)
                    {
                        _request.Headers.Add(_kv.Key, _kv.Value);
                    }
                }

                Stream _dataStreamRequest = _request.GetRequestStream();
                _dataStreamRequest.Write(_postDataArray, 0, _postDataArray.Length);
                _dataStreamRequest.Close();
                HttpWebResponse response = (HttpWebResponse)_request.GetResponse();
                return response.GetResponseStream();
            }
The line where I get the 503 error "Service unavailable" is this line: HttpWebResponse response = (HttpWebResponse)_request.GetResponse();

As mentioned the service is available. The code is a straight forward copy out of a MVC solution and all passes values are as they should be.



Kind regards,




Clemens Linders

**Comment by enetstudio** [comment]
@Clemens Linders,
Try to use HttpClient instead of HttpWebRequest and see if the error is persisted...

**Comment by clemenslinders** [comment]
Hi EnetStudio,

I do not have a lot of experience using HttpClient.

When I use HttpClient I have two problems. I want to pass a header: 
_request.Headers.Add(_kv.Key, _kv.Value); 

And I want to pass some filedata: 
Stream _dataStreamRequest = _request.GetRequestStream();

(I might need to set the content type: _request.ContentType = "application/x-www-form-urlencoded";)

The way I see it HttpClient does not have an option to set headers (there is a get defaultheaders) and HttpClient does have a PostAsync, but I see no option to pass this filestream.


How would I rewrite my code above to use HttpClient???



Kind regards,



Clemens Linders

**Comment by enetstudio** [comment]
@Clemens Linders, first off you can't use HttpWebRequest on client Blazor. Secondly, Microsoft recommend to use HttpClient instead of HttpWebRequest in new projects. If you want to be a Blazor developer, you must learn how to use HttpClient. It's a thirty minute's reading time... Additionally, you'll be able to switch from client Blazor to server-side Blazor easily, if you use HttpClient. 
Read this:
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-2.1
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage?view=netcore-2.1
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpmessagehandler?view=netcore-2.1

Now, if you want to use client Blazor, you must do the following: 
 * Create an extension method similar to SendJsonAsync (line 96) defined in the class HttpClientJsonExtensions (https://github.com/aspnet/Blazor/blob/3e062cdefe334be161c8c5f8b3df25283a2fb8d6/src/Microsoft.AspNetCore.Components/HttpClientJsonExtensions.cs). In line 99, this method calls httpClient.SendAsync, providing it with a new HttpRequestMessage object. In your extension method, create this object (HttpRequestMessage ), and set the properties you want to set, such as Headers, etc. The rest of the code should be similar. Now, you should call this method from your code instead of the other methods defined in the HttpClientJsonExtensions class.

If you wish to use server-side Blazor, read the following and act accordingly:
https://github.com/Suchiman/BlazorDualMode
Hope this helps...

**Comment by clemenslinders** [comment]
Hi EnetStudio,

Thanks I will read this and implement it.

**Comment by xclud** [comment]
@clemenslinders 

In "server" project Startup.cs add the following:

```
using System.Net.Http;
...

services.AddHttpClient();
services.AddScoped<HttpClient>();
```

And in "App" project in any .cshtml file you want, add the following code after `@page` directive:

```
@inject System.Net.Http.HttpClient client

//Use client object
```

Hope this helps you.
