### ISSUE TITLE
Any plans to support VB?

### ISSUE THREAD

**Issue by Nukepayload2** [aspnet/Blazor#171]
Are there any plans to support VB?
I want to rewrite some of my old WebForm VB projects to modern MVC websites. Compared with asp.net MVC 4, Blazor is closer to WebForm, because events can be handled in .NET codes rather than Javascript. 
With VB+Blazor support, I can reuse more VB codes during the project upgrade.

**Comment by SteveSandersonMS** [comment]
In the long term we might well do, but for this first experimental phase we're keeping our project scope focused and are only looking at C# right now. Hope that's OK!

**Comment by jesperhoy** [comment]
This thing (Blazor) sounds absolutely amazing - if only it supported VB.NET.

I have no problem with C# in general - but because we have a huge code base in VB.NET  it is just not practical for us to move everything to C#.

And if I have to use one language on the server (VB.NET) and another for the client (C#) - then I might as well use one of the established and proven JS frameworks (Angular, React, Vue) + TypeScript since I loose the benefits of code re-use anyway.

In the docs you write "the purposes of this initial experimental phase are to ... Gauge interest and to listen to feedback."

We are still a lot of VB.NET developers out here, and I am sure that the "interest" you are looking for would increase if you prioritized VB.NET support.

Blazor with VB.NET would allow us to move our VB.NET WinForm based U.I. stuff to the web so much faster and easier than anything else.

I for one would go into production with this immediately - if it supported VB.NET.

**Comment by danroth27** [comment]
@jesperhoy Blazor runs on a WebAssembly based .NET runtime, which runs normal .NET assemblies. So if you can compile your VB to .NET Standard libraries I believe they should work in a Blazor app. The Razor syntax (.cshtml) used to author the component rendering logic is C# based, and there is no plans to change that, but all of the rest of your app logic I believe could be written in VB.

**Comment by jesperhoy** [comment]
@danroth27 - Thank you so much for responding.
That solution might just work for us!
I had all but written of Blazor - but now I'm all excited again  :-) :-) :-)
I'll go give it a try...

**Comment by jesperhoy** [comment]
@danroth27 - I tested your suggestion - and it works very nicely indeed :-)

Now can you remove that "experimental" label please ? :-)

**Comment by Martin-Andersen** [comment]
Why support VB, its high time to move on

**Comment by davidacrook** [comment]
You can try a VB to C# Converter, such as vbconversions or instant C#.

**Comment by mixfede** [comment]
please support VB !. I try to left asp webform to blazor..... but.... c# ..... no thanks...
