### ISSUE TITLE
_framework/blazor.server.js disable javascript HTMLCollection-array access

### ISSUE THREAD

**Issue by UrielMhezzek** [aspnet/Blazor#1785]
I wan't add a event to html-Element by use this JavaScript-Code.
```
var classnameasdf = document.getElementsByClassName("jsAddOnKeyEvent");
console.log(classnameasdf);
console.log(classnameasdf.item(0));
//for (var i = 0; i < classnameasdf.length; i++) {
//    classname[i].addEventListener('click', myFunction, false);
//}
```
My Console wrote this

> key.js:20 HTMLCollection(1)
> key.js:21 null

My Index.html
```
<body>
    <app>Loading...</app>
    <script src="javascript/key.js"></script>
    <script src="_framework/blazor.server.js"></script>
[...]
```
My Component
```
@page "/test"
<h1>Test</h1>
<p>TestString: @TestString</p>
<input bind="TestString" class="jsAddOnKeyEvent" />a
```
I think there is something in blazor.server.js that prevents me from getting access to the array, a HTMLCollection to be precise.

**Comment by xclud** [comment]
You should run the script after blazor load finishes. Unfortunately blazor does not fire any events for us. So what you want to do currently has no solution.

Maybe a trick works for you. Put all you js code in a function and use setTimeout to call your function after 3 seconds. This is not a good solution because it may take longer than 3 seconds for the client to load.

**Comment by UrielMhezzek** [comment]
Thank you. This help. I hope blazor fix the problem.

**Comment by danroth27** [comment]
This issue was moved to aspnet/AspNetCore#7430
