### ISSUE TITLE
WebRTC Interop 

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#187]
Please consider implementation an interop layer using https://github.com/webrtc/adapter for WebRTC

**Comment by SteveSandersonMS** [comment]
This is certainly a valid thing to want, but it's too early to say which specific JS APIs we want to bake in special support for, versus which ones we'd get from Mono's JS API wrappers, versus which others are provided by third-party packages.

I'll close for now because it's too early to make this decision, and there isn't any reason to have a special issue tracking it for WebRTC as compared with dozens of other groups of APIs. Hope that's OK.

**Comment by grahamehorner** [comment]
@SteveSandersonMS understand, I’d hope that an interop with WebRTC could/would be similar to a SignalR type interop ?
