### ISSUE TITLE
Q: UIEventArgs mapping to DOM

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Blazor#194]
Q: are the UIEventArgs and derived classes used to map W3C DOM events into .NET classes? If so do these classes need fleshing out with the properties as documented on the W3C site ? happy to do this unit of working if this is the case & if needed.

**Comment by SteveSandersonMS** [comment]
> are the UIEventArgs and derived classes used to map W3C DOM events into .NET classes

They carry the specific information we want to surface in .NET. We'll certainly add more information as time goes on, but the aim isn't to mirror DOM events exactly, because in a lot of cases the full set of properties would either make no sense (because they are weird historical oddities that don't even behave consistenly across browsers) or would be useless (because you can't do anything with them from NET code). We'll figure out the detailed semantics we want in due course.
