### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#2]

**Comment by grahamehorner** [comment]
please consider areas, that map to a wasm enterypoint

**Comment by SteveSandersonMS** [comment]
This is done sufficiently for 0.0.1 (and didn't require DI yet). The routing system is deliberately very simple: it's just a way of integrating with the browser's client-side routing (pushState) mechanism.

The built-in `BrowserRouter` uses the convention that URLs match the corresponding component type name. For example `http://yoursite/products/list` might match `MyApp.Pages.Products.List`. If you want to change that convention, you can subclass `BrowserRouter` and override the method that finds the component for a given URL.

There's also a `NavLink` component that can be used in place of `<a>` elements. It behaves the same as an `<a>` element (accepts arbitrary attributes, child markup, etc.), except it toggles its own `active` CSS class based on whether it matches the current URL. This is so you can highlight the active navigation position.

Future things we might consider:
 * URL pattern matching (e.g, `/products/{id}`)
 * Some equivalent to attribute routing, so components can specify their own URL patterns instead of it all being in a central location
 * Outbound URL generation (e.g., `<a page=@About />`)
 * Multiple nested routers
