### ISSUE TITLE
Doc content for 0.1.0

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#223]
Tracking bug for adding docs for the 0.1.0 release.

**Comment by guardrex** [comment]
I listed a few suggestions below. I'd be happy to assist.

Whatever direction you decide to go, I hope you'll at least permit me to submit a small PR against the README ... stomp around with my big dinosaur feet a bit and fix it up! :smile: (The Wiki FAQ could use a light pass as well. I can send you a corrected text file.)

### Description Recommendation

Consider changing the repo description to ...

> Blazor is an experimental .NET web framework using C#/Razor and HTML that runs in the browser with WebAssembly.

### Hosting Recommendation

@danroth27, you mentioned using the repo Wiki. I suggest using a separate repo and GH Pages so that PRs are possible. After all, I can't help *if I can't help.* :smile: ... nor can anyone else.

"Steal" the official docs/DocFX theme so that it brands with .NET products/docs. I'm not talking about building docs ... I'm just referring to the layout and style of the static content. I can help (or lead) on setting this up if you like.

### Content Recommendations

#### Landing page content

Sidebar: TOC

* Define and describe Blazor (Ref: README)
* Experimental note
* Why use Blazor? (benefits and features; link to FAQ)
* List work-in-progress (link issues if possible)
* List upcoming features (link issues if possible)
* Seek to enlist the aid of the community
* Next steps: Link to *Introduction*, *FAQ*, and *Get started*

#### TOC

Use official TOC structure to simplify transitioning to the official docs later if Blazor becomes a *real thing* :crossed_fingers:. For example, use folders with an index pages for area expansions, `_static` asset folders, `sample` sample folders, etc. Follow the official style and grammar guidelines throughout. This will vastly simplify things later. Besides, u want this to :guitar: *ROCK!* :guitar:, right? :+1:

* Introduction (Ref: [Steve's post](http://blog.stevensanderson.com/2018/02/06/blazor-intro/)).
* FAQ (Ref: Wiki FAQ)
* Get started (Ref: README): Prereqs, Build, Run tests, Run end-to-end tests, Run all tests, Build VS tooling, Use VS tooling
* Tutorials
  * Build a Blazor app with Visual Studio
  * Build a Blazor app with Visual Studio Code (possible today?)
  * Build a client-server Blazor solution with Visual Studio
  * Build client-server Blazor projects with Visual Studio Code (possible today?)
* Fundamentals
  * TBD: Subjects such as configuration, app startup, Razor concepts, functions, routing, app state, logging, error handling, etc.
* Test and debug
* Data access
* Security
* Performance
* Host and deploy
  * Host on the Azure CDN
  * Host on a file server
  * Host on Azure App Service or on an IIS/Linux server
    * Hosting app configuration
    * Link to the *Servers*, *Hosting*, and *Host and deploy* topics in ASP.NET Core docs
  * Directory structure (of Blazor assets)
* Common errors reference
* Release notes
* Contribute

**Comment by rstropek** [comment]
@guardrex FYI I started a small docs project for Blazor at [https://learn-blazor.com/](https://learn-blazor.com/) (work in progress!). It should help people as long as no official documentation is available. Later, I will probably use some of the content in trainings and workshops that I will do. Feel free to reuse content and/or contribute.

Greetings,
Rainer.

**Comment by guardrex** [comment]
@rstropek Great job! I fleshed out the *Fundamentals* list with some of your content areas.

Was your intention to maintain a parallel doc set, or were you interested in moving that content into topics in the doc set that they might establish?

Note that I don't currently have anything to do with this project. I'm a contractor working on the ASP.NET Core docs team. However, I would like to work on this doc set in my spare time. At this point, I'm just offering my services to @danroth27, @SteveSandersonMS, and the gang.

**Comment by dragnilar** [comment]
@rstropek

Awesome site and great examples. I think this will definitely help for people who want to get started with Blazor.

**Comment by danroth27** [comment]
We've decided to go ahead and put the Blazor preview documentation on docs.microsoft.com with the ASP.NET Core docs under the [client-side development section](https://docs.microsoft.com/en-us/aspnet/core/client-side/). Moving this issue to the https://github.com/aspnet/docs repo.

The Blazor node and pages should clearly indicate that these are preview docs for an experimental framework.

@guardrex If you want to go ahead and start working on this that would be great!

**Comment by danroth27** [comment]
This issue was moved to aspnet/Docs#5678

**Comment by jonathanperis** [comment]
Nice!!!

**Comment by jerriep** [comment]
Great work on that website @rstropek !!
