### ISSUE TITLE
[Question] Is it possible to bind custom events from a component?

### ISSUE THREAD

**Issue by alaatm** [aspnet/Blazor#236]
I know this project is still very early in development and I can't find any docs. My question is if I have a component that is consumed from a parent component. Is it possible to have the parent component respond to events from the child component?

Like the following ReactJS example:

    // In child component
    interface Props {
        someEvent: (data: any) => void;
    }

    // In parent component
    <Child someEvent={this.handleSomeEvent} />

**Comment by rstropek** [comment]
I am also just learning Blazor but I want to try an answer. If somebody thinks or knows that my answer is incorrect, please correct me. BTW regarding docs: I started a side project with some early Blazor docs at [https://learn-blazor.com/](http://learn-blazor.com/). Hope it helps.

What you want to write is currently not easily possible. On [this page](https://learn-blazor.com/getting-started/what-is-blazor/#razor) I describe how Blazor compiles Razor templates into C# at compile-time. Therefore, an event handler like `onclick` written as `<button type="button" @onclick(() => ShouldRender())>` would result in the following C# code: `builder.AddAttribute(8, onclick(() => ShouldRender()));`. Note the call to `Microsoft.AspNetCore.Blazor.Components.BlazorComponent.onclick` here.

Currently, `BlazorComponent` only has three methods for handling events: `bind` (two-way data binding), `onclick`, and `onchange`. If you try something else (e.g. `@myevent(...)`), this currently results in invalid C# code.

As far as I know, there is currently also no way to get a reference to the child component with which you could add the event handler in C# code instead of the Razor template. The corresponding members in `BlazorComponent` are private.

However, you could create a child component like this:

```
<p>Child Component</p>

<button @onclick(OnClick)>Click me</button>

@functions {
    public UIEventHandler SomeEvent { get; set; }

    private void OnClick()
    {
        SomeEvent?.Invoke(null);
    }
}
```

In the parent component, you could do this:

```
<c:ChildComponent SomeEvent=@(MyHandler) />
...
protected void MyHandler(UIEventArgs _) => Console.WriteLine("Received");
```

This solution is by far not optimal and it also shows an error in the Visual Studio editor. However, it compiles and works. I guess we will see improvements in this area in the future that make it more straight-forward to handle custom events in child components.

Hope this helps,
Rainer.

**Comment by SteveSandersonMS** [comment]
Currently the simplest way to do this is to have a property of type `Action<...>` on your child component, e.g., 

    public Action<MyData> OnSomeEvent { get; set; }

The child component can call `OnSomeEvent(myDataInstance)` whenever it wants to raise the event, and the parent can pass in a handler, e.g.,

    <SomeComponent OnSomeEvent=((Action<MyData>)MyHandler) />

The `(Action<MyData>)` typecast is only needed temporarily. #228 makes this much cleaner and will be merged into `dev` soon.

**Comment by rstropek** [comment]
Thank you @SteveSandersonMS for the tip. I think it currently has to be `<c:ChildComponent OnSomeEvent=@((Action)ChildEventClicked) />` (with an `@` in the binding), right?

I added a sample in the [data binding chapter on learn-blazor](https://learn-blazor.com/pages/data-binding/#event-binding).

**Comment by SteveSandersonMS** [comment]
Oh yes you're right. I was thinking about the next iteration of the tooling that simplifies the syntax in various ways (and will get simpler still shortly).
