### ISSUE TITLE
Move static files (asmjs, wasm, blazorjs) to use Content

### ISSUE THREAD

**Issue by javiercn** [aspnet/Blazor#248]
Declaring all static blazor files (asmjs, wasm, blazor.js) as content instead of using a custom itemgroup and manually copying them to output might allow us to save some msbuild code and also leverage already built in features of Content.

If we can express them as content and use either linkbase or link, it would be better (that way we don't have to handle the copy).

**Comment by SteveSandersonMS** [comment]
Is this really possible? AFAICT if you use native `<Content>` in NuGet packages then:

1. You can't stop them from appearing in Solution Explorer for the recipient project (which is very misleading for the developer, as even lets you "edit" the content, but your edits go nowhere useful)
2. There isn't any way to pass through MSBuild metadata about the files

If you have a pattern that doesn't suffer from these issues that would be great as we could use it for external content packages too.

**Comment by rstropek** [comment]
As a web developer, I would prefer to load static JS files from NPM or from a well-known CDN location. I would love it if you generated CDN references and/or a *package.json* file. I am not sure if that fits into your product design. However, that would feel natural at least for me as a developer familiar with .NET and web technology.

**Comment by SteveSandersonMS** [comment]
@rstropek This issue is about how the Blazor build process works internally (for the framework's own built-in static resources) rather than about the programming model for developers adding their own static resources.

Regarding your point, I totally agree. We definitely want to have a nice suggested model for projects to pull in NPM packages and have an arbitrary build process for static resources (today that's probably with Webpack, but in the future no doubt other front-end build mechanisms will gain popularity too). I have some rough ideas about how this will work but it will be a while before we get to it. It's being tracked as #15.

**Comment by SteveSandersonMS** [comment]
Since it's not clear that we can do this without cluttering Solution Explorer in end-user projects, and the existing mechanism works OK, I'll close this.

We can certainly reopen and reconsider if anyone has more details on how it could be done.
