### ISSUE TITLE
Compile error if project name is equal to a known type name

### ISSUE THREAD

**Issue by rstropek** [aspnet/Blazor#271]
Repro:
* Generate a new stand-alone Blazor project called `Router`
* Try to compile -> `The type name 'Shared' does not exist in the type 'Router'` in *MainLayout.g.cs*

Reason:
*.g.cs* files contain beside others a `using Microsoft.AspNetCore.Blazor.Routing` statement. For a child component, the code `builder.OpenComponent<Router.Shared.NavMenu>(10);` is generated. This leads to an error because `Router` is ambiguous.

Fix:
Don't call your project/your project's directory `Router` or any other existing type name of a namespace that is included in the generated code.

Suggestions:
* Don't fix it but mention it in the docs (probably good for v0.1.0)
* Change code generation to prevent the error (is the `using Microsoft.AspNetCore.Blazor.Routing` absolutely necessary?)
* Enhance error message so that it becomes easier for developers to find the root cause
* Forbid certain project names in Visual Studio (not a feasible/very good solution in my opinion)

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this.

It's a good thing to bear in mind, but probably not something for us to directly address immediately.

We *could* remove the default *using Microsoft.AspNetCore.Blazor.Routing*, but would prefer to have it there since:

1. We're likely to add types to that namespace that people will want to reference, and want to minimise friction for that
2. Removing it doesn't really fix the broader category of issues anyway

The "broader category of issues" isn't specific to Blazor. It applies to all .NET projects. For example, if you create an ASP.NET MVC project called "Controller", then you'll get similar compilation errors right out of the box. It isn't even mentioned in docs, because it's not the sort of thing that people commonly do. Impressively, you *did* come up with the idea of calling your project "Router", but I don't expect many others will do so :)

Since this is a very general .NET issue I think we should close for now and review later if others run into similar issues by accident. Hope that's OK.

CC @danroth27 for info - please reopen if you disagree!

**Comment by rynowak** [comment]
@SteveSandersonMS if we wanted to fix this, we could do so by using `global::Router.Shared.NavMenu` instead.
