### ISSUE TITLE
Use libs .net standard

### ISSUE THREAD

**Issue by Mun1z** [aspnet/Blazor#281]
I can not use standard .net libs, eg refit used for rest

**Comment by SteveSandersonMS** [comment]
Most `netstandard` packages will work fine, but there will be some cases where they rely on platform features that don't make sense in a browser (e.g., TCP listeners, file I/O, Win32 methods, etc.) In those cases you'll get a `PlatformNotSupported` exception or similar.

If you have a case where you think a specific library should work but doesn't, could you post more precise details? Specifically we'd need to know the code you're running, the error you're getting, and preferably info on what underlying .NET API the library is trying to use that doesn't work.

I'll close this because it's too general, but if you can obtain the above info about "refit" specifically I'd be happy to take a look!
