### ISSUE TITLE
Blazor CLI

### ISSUE THREAD

**Issue by struks93** [aspnet/Blazor#285]
Hi, I started playing around with the project (great work by the way), and I found that I miss some of the creature comforts of other SPA development tools, mainly the CLI. It somehow takes me out of it to write `dotnet blazor serve` instead of a Blazor specific command `blazor serve`. (Think Angular cli `ng serve` etc.)

So, long story short, I started working on a [blazor-cli](https://github.com/struks93/blazor-cli). I'm definitely not the most qualified person to do this, but if anyone is interested, there it is :). Currently it is a bit of a mess and only allows `blazor serve` command. You can also check out the npm [package](https://www.npmjs.com/package/blazor-cli)

P.S.
Chose node because NPM should be somewhat familiar to SPA developers. Also cross platform.

**Comment by danroth27** [comment]
@SteveSandersonMS Now that global tools support is available in .NET Core 2.1, should we consider building the blazor CLI tool as a global tool? I think that would be our preferred approach instead of using npm and requiring a node dependency during development.

**Comment by SteveSandersonMS** [comment]
If it becomes common to need to run the Blazor CLI tool then yes, it would be nice to have a global tool that just runs whatever local version of the CLI tool you have installed in your project.

Currently there isn't yet any scenario where you need to run `dotnet blazor ...` directly. For example, instead of running `dotnet blazor serve`, it would be more normal to run `dotnet run` (which does the same thing).

So for now I don't think this is something we need to do anything about, but in the future it's quite possible that we will do.

Thanks for the idea, @struks93!
