### ISSUE TITLE
Tag helpers doen't work

### ISSUE THREAD

**Issue by gingters** [aspnet/Blazor#310]
I created a tag helper and wanted to use that in my Blazor sample project. However, when I want to use the tag helper, the compiler complains about that:

`CS0103 The name 'StartTagHelperWritingScope' does not exist in the current context FirstBlazorApp.`

What is additionally required to make tag helpers work in Blazor?
I have the `@using` for the namespace of my tag helper in place and also the `@addtaghelper` directive. As soon as I add the new tag to my html (it is picked up correctly by the editor highlighting) the compiler barfes about it.

**Comment by SteveSandersonMS** [comment]
I understand why this seems confusing.

Tag helpers aren't applicable, because all the server-side tag helper APIs are about generating HTML strings, which is not something you do in a SPA where there's a live DOM that needs to be updated via DOM APIs.

We should find a way of improving the tooling so it's clearer in the editor that this isn't applicable, rather than just giving the obscure-seeming compile-time error you've seen.

Thanks for letting us know!

**Comment by gingters** [comment]
Thank you for your swift answer.

Maybe I don't fully understand, but when looking at i.e. Angular works, you have both Components and Directives. Components are the equivalent of our Blazor components, providing logic and a template that renders the SPA's html. In Angular you would use Directives in your html template to influence the actual rendered html a bit more, in a reusable way, and to interact with the DOM. As someone who worked a bit both with server-rendered apps and Razor as well as SPAs with Angular 2+, for me this would be a perfect fit for tag helpers.

Let's take Angulars [appHighlight](https://angular.io/guide/attribute-directives) directive as an example.
A component, imho, is way too overweight to use for a case like this, where I only want to apply a single change to the DOM (i.e. change background color), especially if I don't really care about the actual DOM element I want to work with (write a reusable tag helper that can be applied to pretty much all elements).

In some SPAs you have practical requirements i.e. applying one-time tokens to links to images so that its not possible to copy the link to an image from the app and send that to others etc., which would also be something I'd see tag helpers in.

How would I do something like this in a reusable way without the use of tag helpers?

**Comment by SteveSandersonMS** [comment]
Those are good points. We'll certainly contemplate this as the design progresses.

It's worth noting that React doesn't have anything like Angular's notion of directives, and yet it's not something that React developers miss. In the `appHighlight` example, React developers would of course solve that by applying a CSS class rather than needing any special machinery.

This is not intended to diminish the importance of your suggestion! Rather, if you have other examples of cases where you think it would be important I'd love to hear more. In each case I'd probably test out the design by thinking of how a React developer would solve it too, so as to give a more rounded evaluation that in the context of Angular alone. Hope that's OK!

**Comment by SteveSandersonMS** [comment]
> In some SPAs you have practical requirements i.e. applying one-time tokens to links to images so that its not possible to copy the link to an image from the app and send that to others etc., which would also be something I'd see tag helpers in.

If I understand the scenario correctly, that sounds a perfect fit for a component, by the way.

**Comment by rstropek** [comment]
A library that I really like is [Angular Flex Layout](https://github.com/angular/flex-layout). It consists of very useful Angular Directives. I am wondering how somebody could implement something like this with Blazor?
