### ISSUE TITLE
Page is not displayed when pressing Reload button in browser

### ISSUE THREAD

**Issue by kganil** [aspnet/Blazor#324]
Steps to reproduce:
- Create stand alone app "WebApplication1"
- Publish the app
- Install "Web Server for Chrome" extension
- Conigure the path to \WebApplication1\WebApplication1\bin\Release\PublishOutput\WebApplication1\dist
- Go to the home page in browser
- Navigate to "Counter"
- Press the Reload button, The browser shows the message "entry not found: /counter". Please refer the screen shot
![untitled](https://user-images.githubusercontent.com/36897812/37746269-4b0a4f56-2dde-11e8-9749-e59e2e5f6eab.png)

**Comment by rstropek** [comment]
I am not familiar with *Webserver for Chrome* but your problems still sounds familiar to me. The route `/counter` is a client-side route. Your webserver does not know about it. This problem applies to any SPA (Single Page App) framework (e.g. Angular).

You have to configure your webserver so that all e.g. extension-less requests lead to returning *index.html*. There, the SPA framework will take control and do its client-side routing logic. A quick look in *Webserver for Chrome* showed me that it has a setting for that:

![image](https://user-images.githubusercontent.com/2341573/37760707-be072000-2db7-11e8-8b4f-275de9bc73e7.png)

See also [this GitHub issue](https://github.com/kzahel/web-server-chrome/issues/86) in the *Webserver for Chrome* sample.

Hope this helps.

**Comment by rstropek** [comment]
BTW - [here is an example](https://gist.github.com/szarapka/05ba804dfd1c10ad47bf) for a SPA-configuration of a professional webserver (*nginx*). Maybe it helps to understand the problem and points you to possible solutions.

**Comment by kganil** [comment]
Thank you very much Rainer. The solution worked.

**Comment by SteveSandersonMS** [comment]
Thanks for answering @rstropek - this is really helpful! "How to host on a static-files webserver" would make a great page for https://learn-blazor.com/ :)

**Comment by rstropek** [comment]
@SteveSandersonMS Great idea, [here it is](https://learn-blazor.com/getting-started/static-hosting/)
