### ISSUE TITLE
 Bootstrap hamburger menu is not working

### ISSUE THREAD

**Issue by SIkebe** [aspnet/Blazor#329]
Bootstrap hamburger menu is not working.
Adding `jquery.min.js` and `bootstrap.min.js` resolves it.

### How to repro
1. Select File -> New Project -> Web -> ASP.NET Core Web Application
2. Pick the Blazor template
3. Press Ctrl + F5
4. Reduce the browser width and show hamburger menu

**Comment by camou23** [comment]
Can i ask you how you added them?
I tried to add them in the idex.html but it seems im doing something wrong

**Comment by SIkebe** [comment]
@camou23 Nothing special 😄 
```
<body>
    <app>Loading...</app>

    <!-- add these js files-->
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>

    <script src="css/bootstrap/bootstrap-native.min.js"></script>
    <script type="blazor-boot">
    </script>
</body>
```

**Comment by FabriDamazio** [comment]
I'm investigating it and appears be an issue with the `bootstrap-native.min.js`
Maybe something related with [this](https://github.com/thednp/bootstrap.native/issues/136)

**Comment by SteveSandersonMS** [comment]
Adding them to `index.html` should work fine. Just remember to rebuild your application after (because the `index.html` file is *built* so we can perform the replacement on the `blazor-boot` script tag).

I expect we won't fix this issue in isolation, because instead we'll soon move to Bootstrap 4 in the templates, so the issue will no longer apply. Hope that's OK!
