### ISSUE TITLE
Question: Future css strategy?

### ISSUE THREAD

**Issue by johot** [aspnet/Blazor#358]
I come from a C# and React background and I am really curious if you plan to support "CSS-in-C#" to solve the many issues that comes with CSS such as global scopes, setting runtime values and so on. In your samples you seem to use just regular css.

It would be so cool if we could have something similair to CSS-in-JS and inline styles in the form of C# objects. Theres a great talk about why CSS-in-JS is so great (https://speakerdeck.com/vjeux/react-css-in-js) and I think the same would hold true for having a CSS-in-C# solution.

**Comment by SteveSandersonMS** [comment]
We're definitely open to a future enhancement like that!

The best thing would be if you or someone else in the community was able to prototype one or more solutions and we could see what a good design for it would be. Bonus points if it can be done just as a NuGet package that can be installed into Blazor projects without needing to change the Razor compiler internally (though I appreciate it might turn out to be necessary to do stuff inside the compiler).

I'll close this because hopefully I've answered the question. If anyone would like to post a concrete design proposal, preferably with a running prototype (no matter how hacky), please do :)

**Comment by xyun52** [comment]
Component.cshtml, Component.css, Component.cs

**Comment by alexandrereyes** [comment]
Here is a proposal https://github.com/alexandrereyes/BlazorScopedCss
