### ISSUE TITLE
Question: How do Blazor determine when to re-render a component? Can we make it smarter?

### ISSUE THREAD

**Issue by johot** [aspnet/Blazor#359]
Is there any docs explaining how Blazor knows when to re-render a component? I am guessing it will be done when a property is changed but it seems to magically work when setting internal component state also.

From doing some console logs it looks to me that running any method or setting any property located in the `@functions` block will cause a re-render, (even if no data was changed). Is that how it is solved currently?

I also noticed that if I inject a singleton object, for example a state "store" other components will not re-render if I change data in the store. I need to create event handlers etc to solve this and run StateHasChanged() in all components. Are there any plans to make this smarter? I would love for some kind of observable strategy similar to how we can use MobX in React.

**Comment by danroth27** [comment]
Blazor will ask a component to render itself after any event that's handled by that component. Blazor will then compare the new render tree with the previous one and update the DOM only as needed.

If you want your component to render based on state changes you have to provide events so that the component knows to do so. See the [Flight Finder](https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor) sample app for an example of how you might set this up.

**Comment by mrpmorris** [comment]
@johot I had to go with this approach for my Blazor Store library. I am hoping there will in future be a way to signal to all Blazor components that there may be an update.

https://github.com/mrpmorris/blazor-fluxor/blob/master/src/Blazor.Fluxor/Temporary/FluxorComponent.cs
