### ISSUE TITLE
Support handling window events

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor#381]
Customer feedback in survey response.

**Comment by grahamehorner** [comment]
IMHO the event system/dispatching needs to be relocated in a class 'Browser' and not as (currently) is within the BrowserRendering class; as events can be raised from non UI rendering actions like Window, Server Side Events, Workers, Storage; the BrowserRendering should inherit/user the browser event dispatcher to inform .NET of the UI and other UI related events eg. Focus, Drag, Wheel events etc.

**Comment by SteveSandersonMS** [comment]
I think this would come from general JS interop, either by developers writing their own JS interop code to register an event handler, or in the simpler and more common case by using a package (perhaps supplied by Mono) that offers access to common browser APIs.

So I'll close this because I don't think it's something for us to take action on, but we can reconsider that in the future if it turns out that Mono isn't going to provide access to these APIs via their brower APIs package.
