### ISSUE TITLE
onchange only fires once

### ISSUE THREAD

**Issue by davidnmbond** [aspnet/Blazor#431]
In this CSHTML file, it is only possible to make FormChanged() execute once (see attached file).

[Login.cshtml.txt](https://github.com/aspnet/Blazor/files/1860503/Login.cshtml.txt)

**Comment by SteveSandersonMS** [comment]
It's because your `@bind` registers its own `onchange` event handler, and currently we only support having a single event handler with a given name. There's a "todo" in the code about this: https://github.com/aspnet/Blazor/blob/dev/src/Microsoft.AspNetCore.Blazor.Browser.JS/src/Rendering/BrowserRenderer.ts#L178

I'll file a dedicated issue about fixing the event handling properly.

**Comment by davidnmbond** [comment]
Ah - thanks @SteveSandersonMS - keep up the great work :)

**Comment by SteveSandersonMS** [comment]
@davidnmbond Update: please see workaround I posted above.
