### ISSUE TITLE
Is blazor can be used for developing desktop application ?

### ISSUE THREAD

**Issue by anirugu** [aspnet/Blazor#449]
I am looking for a way so I can convert my winforms apps to something web (where I can use html, css for ui kind of stuff).

Is blazor can be used somehow to do this things. I have seen this https://github.com/ElectronNET/Electron.NET  earlier which does help developer to make the app in dotnet core like electron.

I am not sure about technical aspect so someone can check this.

**Comment by rstropek** [comment]
Electron.NET will only solve your problem partly. You will be able to write your business logic in C#. However, for the UI you need some browser-based technology (e.g. Angular, React, plain JS). Blazor is also such a browser-based alternative **but** you use C# instead of JavaScript or TypeScript. Therefore, it might be an interesting solution if you do not want to dive into a new language but use existing skills and tools.

However, you have to have time and patience. Blazor is at an early stage and it will take a while until the platform reaches the stability of e.g. Angular. So if you aren't in a hurry, Blazor could become a great option for modernizing your existing WinForms app in the future. Now its a great time to play with it, give feedback, and contribute.

Does this help?

**Comment by SteveSandersonMS** [comment]
I've heard that some people have experimented with putting Blazor inside Electron, so in theory at least that should be possible. To be clear though, our primary focus is on web apps (delivered into regular browsers via HTTP).

**Comment by anirugu** [comment]
Thanks for reply :)
