### ISSUE TITLE
Pure HTML template syntax

### ISSUE THREAD

**Issue by Thaina** [aspnet/Blazor#517]
Like `angular` and `vue` that work on pure html and mostly use custom attribute along with `{{}}` symbol. I wish blazor should have the same feature in addition to static compile `cshtml`

It could be dynamic compile blazor or DOM replace, but could this feature also contain in this project?

**Comment by danroth27** [comment]
I think that's pretty much what we already do today. The cshtml files are pure HTML combined with a C# based templating syntax called Razor. These files get compiled into .NET assemblies much in the same way that components in other frameworks get bundled into a JavaScript bundle. 

I'm going to go ahead and close this as I think we're already pretty much doing what you're asking for, but if I've misunderstood feel free to reopen and clarify. Hope that's OK!

**Comment by Thaina** [comment]
@danroth27 Unlike `cshtml` that was recompile into C# render tree function at compile time. What I ask for is that we should be able to write `html` file (real html that not compiled into anything) and have blazor oversee DOM's attribute directly in runtime

**Comment by rstropek** [comment]
@Thaina Angular works very similar to Blazor. You do not write pure HTML. HTML is compiled by the Angular compiler (JIT or AOT) into JavaScript just like Blazor compiles HTML into C#. The only thing that Blazor is missing is the JIT compiler. However, Angular moves very much in the direction of AOT because of perf reasons. Therefore, I think Blazor's approach can be compared to Angular's preferred AOT approach.

**Comment by Thaina** [comment]
@rstropek Sorry that I don't mention about version but I meant angularjs (1.0 , and also current vuejs) that heavily run on direct html instead of AoT. Which I favor over current angular 2

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion @Thaina but this is definitely not something we want to do. The world has moved on a long way since Angular 1 and we don't plan to go back to that kind of architecture. Angular 2+, React, and Vue AoT all show significant benefits of compiled templates - we're also benefitting from that approach.
