### ISSUE TITLE
Output Blazor version info in blazor.js or similar file

### ISSUE THREAD

**Issue by humbersoft** [aspnet/Blazor#613]
I don't think this is super important, but it would be nice to know what version of a Blazor my website is running by inspecting via view source code

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion.

Technically it is already possible to determine the version (e.g., by using ILDasm or ILSpy on the `Microsoft.AspNetCore.Blazor.dll` file delivered to your browser). I appreciate this isn't as convenient but it is an option if you need it.

Since this is a very obscure requirement, I hope you don't mind but I'm going to close it as "probably not, at least for now". We can always reconsider if more people keep asking for it in the future.
