### ISSUE TITLE
[PROPOSAL] Use Razor directives as class attributes when using code-behind pattern.

### ISSUE THREAD

**Issue by montyclt** [aspnet/Blazor#620]
Hello, I propose the use of razor directives as class annotations when using then code-behind pattern.

An example, turn the `@page "/todo"` directive into class attribute:

```
[Page("/todo")]
class TodoPage
{
}
```

**Comment by brunopbarrote** [comment]
Would be great, since we have been doing this since mvc

**Comment by SteveSandersonMS** [comment]
There is an attribute for this exact scenario:

    [Route("/todo")]

That's all the `@page` directive does - it adds this attribute to the generated class. You can add the attribute manually (e.g., on an inherited class) if you want.

Similarly if you want, you can add `[Inject]` to properties on classes manually if you want to have the same effect as `@inject`.

In general where it makes sense, the implementation for directives will be something you can do manually in your classes if you want to.

There are also cases where it doesn't make sense, e.g., `@using`, which only affects the code in the associated Razor file. So it doesn't work to have a general rule where all directives have equivalent same-named attributes, but for things where it does make sense there will always be a way to do it directly on the C# class manually, since a Blazor component literally is a C# class after Razor compilation so that always needs to be possible.
