### ISSUE TITLE
Rendering component through binding to div

### ISSUE THREAD

**Issue by mikoskinen** [aspnet/Blazor#626]
Is there plans to extend binding support so that one could bind the whole component to a div element?  

Meaning, one could define component like this:

```
@page "/"
<h1>Hello, world!</h1>
Welcome to your new app.
<SurveyPrompt Title="How is Blazor working for you?" />

<div bind=@counter/>

@functions {
    Counter counter = new Counter();
}
```
I think this could be solved without binding too, with something like:

```
@page "/"
<h1>Hello, world!</h1>
Welcome to your new app.
<SurveyPrompt Title="How is Blazor working for you?" />

<div>
@counter
</div>

@functions {
    Counter counter = new Counter();
}
```
Currently this doesn't render the component, only its type name.

Or maybe with a custom tag helper:

```
@page "/"
<h1>Hello, world!</h1>
Welcome to your new app.
<SurveyPrompt Title="How is Blazor working for you?" />

<component bind=@counter/>

@functions {
    Counter counter = new Counter();
}
```

The idea here is that we could compose component (for example Shell) from multiple child components (News, Customers, Invoices) through DI / inject attribute. 

This would also allow one to define some of the components singleton and inject them where needed.

**Comment by SteveSandersonMS** [comment]
It sounds like your goal is to be able to programatically represent which other component should be rendered, along with its parameters, and possibly to pass that information between different parts of your application. The intended way to do this is using the `RenderFragment` type. A `RenderFragment` represents an entire block of UI, which may include other components, and can be passed around and ultimately rendered wherever you choose.

Currently the main way to create a `RenderFragment` is by including child content on a component reference: http://blazor.net/docs/components/index.html#component-parameters. The code sample at that link shows passing static HTML, but with the same syntax you can pass content that includes other components.

Technically you can also [define a `RenderFragment` through procedural C# code](https://learn-blazor.com/pages/dynamic-content/#render-fragments) though that's quite advanced and we hope to expand the scope of what you can do with Razor so you'd never have to drop down to low-level code like that.

We want to make `RenderFragment` much more powerful and easier to work with (e.g., to read/write its contents programmatically) and have ideas for how to do that.

> I think this could be solved without binding too, with something like...

The approach you've suggested of manually instantiating component instances is something we considered seriously back in the beginning. Eventually we realised that if we did that, then the whole component lifecycle model would stop being reliable, because there'd be no way to ensure that "init", "dispose", etc. were called at the correct time (how do we know when you're finished with an instance?), or even what should happen in the case where someone renders the same component instance in multiple places simultaneously and the instance wants to do some interop that acts on its DOM element. So we concluded that, for the model to be robust, the framework needs to have sole responsibility for actually instantiating and destroying the component instances, and developers should instead have methods for specifying which components and parameter values should be used. Interestingly it's the same in React, which I'm guessing they designed that way for similar reasons.
