### ISSUE TITLE
Instantiating/enumerating components

### ISSUE THREAD

**Issue by DanielProgrammer007** [aspnet/Blazor#646]
Hi,

Couple of questions:

1. How can I instantiate a component at run-time and attach it to a container?

2. Is there a way to list all components in a given container?

3. I'm not sure I understand how components can interact with each other. I read the docs section on parent/child components, but how can two completely independent components talk to each other? A common scenario is when there are multiple components inside a TabPage component where a component inside tab A needs to notify a component in tab B about some change. Also, I'm assuming components can trigger their own events?

4. I've noticed that the initial load takes a few seconds even on localhost, is this going to improve once the entire app is compiled directly to WASM? Is this something that you are actively working on? I don't think the initial load time matters that much for an SPA, but I'm looking at potentially integrating Blazor into my existing WebForms app. I think if users attempt to access a simple page (containing some Blazor components) that takes a few seconds to interpret, that could be a problem.

Admittedly I'm not too familiar with other SPA frameworks (React etc), so maybe questions 1-3 have obvious answers. I think it would be very beneficial if in the future releases (once Blazor somewhat matures) your team can provide guidance on how to tackle more complex UI cases, including best practices for creating custom reusable components (e.g. GridView, TreeView etc) - ideally, this would be packaged as a NuGet library of Microsoft's set of basic components.

Anyway, this project is awesome!

Thank you,
Daniel

**Comment by Daddoon** [comment]
I'm not yet a Blazor expert, but in my opinion:

1. If you want to put it absolutly without any child/parent hierarchy rendering logic, you may juste use your BrowserRenderer object you have at start in Program.cs

```
br = new BrowserRenderer(serviceProvider);

//Your custom component
br.AddComponent<DaddoonBlazorExtensionScripts>("daddoon");

br.AddComponent<App>("app");
```

The argument is a CSS dom selector.

Otherwise, if you want to instanciate a component in an other component as a child dynamically, you may try to use a RenderFragment in your parent component, and just instanciate your child component with the builder.OpenComponent. Don't forget to then call builder.CloseComponent.

Here a code snipped on my project for a "GenericModal" when only the child component given as attribute is the content to render in the modal, this way, only having one file to manage my modals rendering. Of course, there should be better strategy for this:

```
@addTagHelper *, Daddoon.Blazor
<!-- Modal -->
<div id="@Id" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header modal-app">
                <button type="button" class="close" data-dismiss="modal">
                    <RenderSVG src="/Images/resources/svg/times-circle.svg" class="modal-close-button-time"></RenderSVG>
                </button>
            </div>
            <div class="modal-body">
                @BodyFragment
            </div>
        </div>

    </div>
</div>

@functions {
    public string Id { get; set; }

    public Type Body { get; set; }

    private Microsoft.AspNetCore.Blazor.RenderFragment BodyFragment;

    protected override void OnInit()
    {
        BodyFragment = builder =>
        {
            //If invalid type of object, there is nothing to append
            if (Body == null)
                return;

            builder.OpenComponent(1, Body);
            builder.CloseComponent();
        };
    }
}
```

**Comment by SteveSandersonMS** [comment]
1. In the parent markup, just specify the child by name, e.g.,

    // Inside parent.cshtml
    <MyChildComponent />

2. Your question suggests you're expecting there to be a component tree that can be mutated procedurally, like WebForms or the browser DOM. There isn't. The programming model is that the UI is projected from some data, like other more modern web UI frameworks. So instead of trying to read/write a component tree procedurally, you should instead have some other domain-specific data model (which can itself be a tree structure if you want, or a list, or anything else) and read/write that plus use `cshtml` to project it to some visible UI.

3. The primary mechanism is that a parent supplies parameters to child components. Conceptually those parameters can be in the parent->child direction by being regular values that can be changed over time, or in the child->parent direction by being callbacks that the child can invoke whenever it wants. In #1 we're also planning some additional ways of capturing references to child components so you can invoke methods on them directly, but this would still be a secondary technique compared with using parameters. BTW this is all the same as in other recent web UI frameworks.

4. Yes, we have ongoing plans to keep shrinking the payload size. We have various techniques planned in issues in the backlog here.

Hope that helps!

**Comment by DanielProgrammer007** [comment]
@SteveSandersonMS thank you for taking your time to answer my questions. This is quite a paradigm shift from the more traditional (obsolete?) approach and hopefully I will see some nontrivial examples soon enough as more people start producing apps with this technology.

Regarding question #1, I think I need to explain better what I'm after and make sure that this is possible in Blazor.

Think of a wizard that drives the user through a series of steps (each step is a component). Application can have multiple "wizards", each having multiple components. The idea is that when user selects say "Wizard A" from the menu, the app needs to call a (Web API) service to retrieve data needed to construct the wizard dynamically (and create multiple components on the fly). Is there (going to be) an easy way to implement this in Blazor? There are many applicable real-world scenarios. Your previous answer suggests that the implementation of "Wizard A" is known at the design time, but that's not the case here.

One more question, is there some concept of "global/shared" object that all Blazor pages can access (e.g. user settings loaded on start up)? Is this supposed to be handled by injecting an object into each page?

**Comment by danroth27** [comment]
> One more question, is there some concept of "global/shared" object that all Blazor pages can access (e.g. user settings loaded on start up)? Is this supposed to be handled by injecting an object into each page?

Yup, you can make these settings available as a service through [dependency injection
](https://blazor.net/docs/dependency-injection.html)

**Comment by SteveSandersonMS** [comment]
> Application can have multiple "wizards", each having multiple components. The idea is that when user selects say "Wizard A" from the menu, the app needs to call a (Web API) service to retrieve data needed to construct the wizard dynamically (and create multiple components on the fly)

You'd call your Web API service and get back some data structure describing which wizards should be displayed, and your Razor logic would loop over it and have a `<MyWizard>...</MyWizard>` for each one.
