### ISSUE TITLE
RenderTreeBuilder - Make methods virtual

### ISSUE THREAD

**Issue by SergeySeleznyov** [aspnet/Blazor#679]
Let's suppose I have markup as shown below:

```
<MyComponent>
    <RowTemplate>
        <div>"@SomeExpression"<div>
    </RowTemplate>
    <SomeSettings Mode="Auto"/>
</MyComponent>
```

Currently, it is possible to manage where to render the nested markup:

```
public class MyComponent : BlazorDataComponent 
{
	public RenderFragment ChildContent { get; set; }
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
        	// ...
        	// Some render tree building 
        	// ...
            ChildContent(builder); // here
            // ...
            // Some render tree building 
            // ...
        }
}
```

If methods of the RenderTreeBuilder class (the type of "builder" in the example above) were virtual, it would allow us to affect Blazor's process of tree building.
Derive from RenderTreeBuilder and override all required methods:

```
public class MyRenderTreeBuilder : RenderTreeBuilder
{
    public MyRenderTreeBuilder(Renderer renderer) : base(renderer)
    {
    }

    public override void OpenElement(int sequence, string elementName) 
    {
    	if(elementName == "SomeSettings") { ... }
    	if(elementName == "RowTemplate") { ... }
    	...
    }

    public override ...
}
```

Inject the derived MyRenderTreeBuilder into BuildRenderTree method:

```
public class MyComponent : BlazorDataComponent 
{
	public RenderFragment ChildContent { get; set; }
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
        	var myBuilder = new MyRenderTreeBuilder();
            ChildContent(myBuilder); // Process the tree internally and pass the processed tree to the Blazor
        	
        	// ...

        }
}
```

Process the tree internally and pass the processed tree to the Blazor.

If this were done, we would be granted a powerful capability to build rich components.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion!

We're already working on an alternative, more high-level approach to customize how a component deals with any child content it's been supplied. This is part of the work on #1, and should be more convenient to work with than having to override virtual methods. There isn't a committed ETA on that work but probably during the next month.

I'll close this because I think it's being taken care of. Once you get to try out the new APIs, please let us know what you think. Hope that's OK!
