### ISSUE TITLE
Is there any plan for MVC like Html Helpers?

### ISSUE THREAD

**Issue by babula38** [aspnet/Blazor#693]
Is there any plan for MVC like Html Helpers? as those are really handy and a developer need not to worry about all the implementation of HTML. A developer like me who is more comfortable in c# can write code very much easily. 
It is my view only.

**Comment by SteveSandersonMS** [comment]
We're focused on making it nice to create and use components declaratively with Razor syntax rather than C# method calls. Hopefully when you get used to it you'll agree it's much more natural!

That said, you can absolutely create your own C# methods that return a `RenderFragment` (a block of UI) and invoke them inside Blazor component output if you really prefer to do so.

**Comment by philipri** [comment]
@SteveSandersonMS  one thing that might be helpful though is the Html label and form helpers from razor. It's not a deal breaker though (definitely not 1.0 criteria).

**Comment by danroth27** [comment]
@philipri We have a separate item tracking adding a first class forms and validation solution: #17
