### ISSUE TITLE
Unable to run your project. the "RunCommand" property is not defined.

### ISSUE THREAD

**Issue by uopeydel** [aspnet/Blazor#716]
I do follow this guid.
=> https://blazor.net/docs/get-started.html

![image](https://user-images.githubusercontent.com/12793024/39457191-43a96ce0-4d16-11e8-99c0-3f1383d0d822.png)

At step 4 > Press Ctrl-F5 to run the app without the debugger. Running with the debugger (F5) isn't supported at this time.

When i do it , then dialog pop.

-------

When try "dotnet run"
result is 

![image](https://user-images.githubusercontent.com/12793024/39457699-ef24670c-4d19-11e8-984d-8f422f1ffbb5.png)

How can i do for run blazor?

**Comment by danroth27** [comment]
Looks like your using the ASP.NET Core hosted Blazor template. When hosting in ASP.NET Core you actually need to run the Server project instead of the Client project. It looks like your solution is setup to run the Client project as the Startup project. You should switch the startup project to be the Server project.

The same thing goes for running the app form the command-line. Instead of running `dotnet run` from the Client project directory, you should run it from the Server project directory.

I hope that helps!

**Comment by McHeff** [comment]
THANK YOU DAN!
