### ISSUE TITLE
Make a standard way (in BlazorComponent) to pass arbitrary attributes

### ISSUE THREAD

**Issue by chanan** [aspnet/Blazor#735]
In @SteveSandersonMS Bootstrap branch @SteveSandersonMS added a way to pass arbitrary attributes down to a Component. Every Component should have that by default such that a component doesn't have to implement every single attribute imaginable. For example in react I would do that with the spread operator on props: <button {...props} />

See code in the bootstrap branch here:

https://github.com/aspnet/Blazor/blob/stevesa/bootstrap-components-library/src/Microsoft.AspNetCore.Blazor.Bootstrap/BootstrapComponentBase.cs
Used here: https://github.com/aspnet/Blazor/blob/stevesa/bootstrap-components-library/src/Microsoft.AspNetCore.Blazor.Bootstrap/Components/bsAlert.cshtml#L5
and rendered here: https://github.com/aspnet/Blazor/blob/stevesa/bootstrap-components-library/src/Microsoft.AspNetCore.Blazor.Bootstrap/DynamicElement.cs 

IMO, this should be part of Blazor itself.

**Comment by SteveSandersonMS** [comment]
All components can already receive arbitrary attribute without declaring them up-front (it's only the default `OnPropertiesSet` base class implementation that throws if it doesn't recognize a value because that helps developers know what's going wrong if they have a typo - you can override that and then do what you want with the incoming `ParameterCollection`).

The harder part is that Razor syntax doesn't have a mechanism for expressing that you want to "spread" a dictionary of attributes into an element. This is something we've talked about adding to Razor generally. Would you be willing to file an issue requesting that feature in Razor at https://github.com/aspnet/razor?

I'll close as this would be a Razor feature if (or hopefully *when*) implemented.

**Comment by chanan** [comment]
Done, in the meantime I am taking your code for my bootstrap lib :)
