### ISSUE TITLE
Duplicated Render while using child component

### ISSUE THREAD

**Issue by hungdluit** [aspnet/Blazor#738]
Version 0.3.0

CommandButton.cshtml

```
@using Microsoft.AspNetCore.Blazor
<div class="@GetClassNames()" ref="Root">
    @ChildContent
    @Text
</div>

@functions {

    public ElementRef Root;

    [Parameter]
    protected RenderFragment ChildContent { get; set; }

    [Parameter]
    protected string Text { get; set; }

    [Parameter]
    protected ItemStyle Style { get; set; } = ItemStyle.None;

    [Parameter]
    protected bool IsOutLine { get; set; }

    [Parameter]
    protected ItemSize Size { get; set; } = ItemSize.Default;

    private string GetClassNames()
    {
        IconButton a;
        string buttonStyle = string.Empty;
        if (Style != ItemStyle.None)
        {
            buttonStyle = Enum.GetName(typeof(ItemStyle), Style).ToLowerInvariant();
        }

        string outline = IsOutLine ? "outline" : string.Empty;

        return ClassNames.Get("button", buttonStyle, outline);
    }
}
```

IconButton.cshtml

```
@inherits CommandButton
<CommandButton Text=@Text Style=@Style>
    <span class="@Icon"></span>
</CommandButton>

@functions {

    [Parameter]
    private string Icon { get; set; }
}
```

`<IconButton Icon="mif-checkmark" Text="Click Me"></IconButton>
`
Rendered HTML

![image](https://user-images.githubusercontent.com/5623089/39587013-be4e213a-4f22-11e8-9a7e-ae0c24c94952.png)

**Comment by dlr1** [comment]
I think the base classes should be abstract and not have a template of their own

**Comment by SteveSandersonMS** [comment]
As far as I can tell, the render output is correct.

Your `IconButton` both inherits from *and* contains a `CommandButton`. So your render output will produce the output from `CommandButton` twice.

As @dlr1 comments, you should either not be inheriting from `CommandButton`, or `CommandButton` should not produce output.

We might change the APIs at some point to prevent people from doing this if it turns out to be a common mistake.
