### ISSUE TITLE
Some questions about milestones

### ISSUE THREAD

**Issue by boukenka** [aspnet/Blazor#769]
First of all, thank you for that great project. It is opening so many new possibilities.
Here are my questions:

1. Why not remove the 2 remaining requests (SignalR and Events) and assign then to the milestone 0.4? I guess they will take some time.
2. Do you plan to have more than 2 points for the milestone 0.4?
I am just curious what will contain the next milestones.
Also I can see the number of issues/questions rapidly increasing in the last days.
I guess it becoming more difficult to process/analyze all of them.

**Comment by SteveSandersonMS** [comment]
> Why not remove the 2 remaining requests (SignalR and Events) and assign then to the milestone 0.4? I guess they will take some time.

TBH I don't know. We'll figure that out next time we review the plans.

> Do you plan to have more than 2 points for the milestone 0.4?

We tend to add more items to milestones as we progress, so yes I'm sure more will land during the 0.4.0 cycle. However all but one of the team members have other commitments (conferences) during the next 10 days and this will cut into the amount we can deliver. It might be that less than usual fits into this cycle.

> Also I can see the number of issues/questions rapidly increasing in the last days.
> I guess it becoming more difficult to process/analyze all of them.

Yes, it is increasingly taking a lot of time. It does unfortunately reduce the available time to make progress on the code. However it's still important because getting feedback is an essential part of this experimental phase.
