### ISSUE TITLE
Render custom Element

### ISSUE THREAD

**Issue by hungdluit** [aspnet/Blazor#778]
```
protected override void BuildRenderTree(RenderTreeBuilder builder)
{
          base.BuildRenderTree(builder);

            builder.OpenElement(0, "div");
            BuildContentRenderTree(builder);
            builder.CloseElement();
 }

 protected virtual void BuildContentRenderTree(RenderTreeBuilder builder)
 {
            if (ChildContent != null)
            {
                ChildContent(builder);
            }
   }
```

```
@page "/usercontrolsample"

<UserControl>
    <a>This is a User Control</a>
</UserControl>
```
Result:

![image](https://user-images.githubusercontent.com/5623089/39675253-a89e1ebe-5182-11e8-8499-bcaff2db793e.png)

I'm following same samples on the internet. But it does not work in my case.
I think 'div' should be rendered instead of 'usercontrol'

**Comment by GoldenCrystal** [comment]
From what I understand, instead of calling the ````RenderFragment```` delegate yourself, you are supposed to call ````AddContent(int, RenderFragment)````, as in the code below:

````csharp
protected override void BuildRenderTree(RenderTreeBuilder builder)
{
    base.BuildRenderTree(builder);

    builder.OpenElement(0, "div");
    builder.AddContent(1, ChildContent);
    builder.CloseElement();
 }
````

This way, you're letting the ````RenderTreeBuilder```` [manage its state correctly](https://github.com/aspnet/Blazor/blob/dev/src/Microsoft.AspNetCore.Blazor/RenderTree/RenderTreeBuilder.cs#L83).
What likely happened in your case, is that the ````ChildContent```` delegate messed up the sequence numbering when you called it by yourself (because it can't know about your own sequence numbers), which confused Blazor during rendering.

I've actually used ````AddContent```` for that [there](https://github.com/GoldenCrystal/UnicodeBrowser/blob/master/UnicodeBrowser.Client/Components/MarkdownView.cs#L48) so I'm pretty confident that it works. 🙂

**Comment by hungdluit** [comment]
thanks @GoldenCrystal , that helps me alot :)
