### ISSUE TITLE
Create a VSCode extension for the razor files used by Blazor.

### ISSUE THREAD

**Issue by PaulOst** [aspnet/Blazor#814]
Most modern web developers use VS Code, which should provide a first class experience for developing Blazor applications, including IntelliSense for the Razor syntax and C# objects.

**Comment by sannysc** [comment]
>Most modern web developers use VS Code

Where are you getting this from? And Blazor has no commitment from Microsoft yet. It is an experimental project. Creating an extension right now isn't a good idea.

**Comment by danielabbatt** [comment]
This might help a bit? Razor+ -  https://marketplace.visualstudio.com/items?itemName=austincummings.razor-plus

**Comment by chrissainty** [comment]
I'm using VS Code and the Razor+ extension @danielabbatt mentioned above and its fine for testing out Blazor.

**Comment by SteveSandersonMS** [comment]
We'd love to! All of us have it in mind to do this and have discussed it many times.

For the short term, however, this is not something we can even start looking into. It will be a huge engineering investment that could only begin if the project was committed and given more resources.

I'll close because there's nothing more we can do or say on this subject, but please be assured that we very much would like to do it.

**Comment by PaulOst** [comment]
Thanks for the reply, Steve.
