### ISSUE TITLE
Native Electron/Cordova Support

### ISSUE THREAD

**Issue by kstewart83** [aspnet/Blazor#826]
One thing that I think would be valuable and would help broaden the use cases and appeal of Blazor would be first class integration with Electron and Cordova. This would include things like tooling in Visual Studio, debugging support, etc. A tight integration with these two other platforms would allow a high degree of code-base sharing across Web (backend / frontend), Desktop, and Mobile in a single language and programming paradigm. I think this would be a great boost to productivity.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. 

Yes, I agree these are interesting scenarios. In fact we are already looking into them. For the time being we don’t have definite plans but I hope we will at some stage.

I’ll close because it’s not something we currently have as an active deliverable but please feel free to continue discussing below if desired.

**Comment by kwakuduahc1** [comment]
I came here just for this discussion. I strongly suggest some significant effort is made to have a cordova project  with Blazor. Indeed i can not wait to stop writing sql scripts. <code>Who does not love context.Books.Add(book);</code> instead of writing that long sqlite script.

I am currently afraid of desktop development because i cannot do <code>if(ModelState.IsValid)</code>. For the love of c#, kindly put in some efforts into that and i can see a whole new shift in mobile and web technologies.

It can actually serve as a killer blow to JavaScript and bring sanity to web development. 

I just cannot finish typing enough

**Comment by jzabroski** [comment]
This would be completely awesome.

**Comment by jzabroski** [comment]
@SteveSandersonMS  I could throw away most Xamarin stuff if this was supported.  The idea of having Blazor, AutoFixture, Microsoft.Extensions.DependencyInjection, SignalR, etc. all available in a mobile app would significantly reduce my development costs.

**Comment by stavroskasidis** [comment]
Blazor "Native" is the next logical step and it could be huge. But let's get blazor wasm right first.

**Comment by jzabroski** [comment]
Hi Stavros,

I think, for me, next step is adapting Uber's RIBS architecture I'm a fan of to Blazor. Let me know if you want to discuss offline on gitter or elsewhere.

**Comment by GoranHalvarsson** [comment]
@stavroskasidis Yes I agree, it will be huge. Another thing, I think progressive web apps will outcompete the "simple" native apps. In other words, Blazor will be your perfect "Swiss Army Knife" tool :)

**Comment by Suchiman** [comment]
Redirect your feedback here https://github.com/aspnet/AspNetCore/issues/11082#issuecomment-501424063
This repository is deprecated as far as issues go
