### ISSUE TITLE
Why ASP.NET Core sample has 2 separate projects?

### ISSUE THREAD

**Issue by jonathanperis** [aspnet/Blazor#83]
What prevents ASP.NET Core project from having the entire structure in just one project?

**Comment by grahamehorner** [comment]
Nothing; these are just samples

**Comment by danroth27** [comment]
A Blazor app is built into an assembly which is the downloaded into the browser along with the runtime so that it can be executed. Your ASP.NET Core project is also built into an assembly and executed on the server. Typically you have one project for each .NET assembly that you're trying to build, hence two projects.

Blazor doesn't technically require an ASP.NET Core backend. You can just host Blazor as a bunch of static files. For this "stand-alone" case you only need one project with a pre-built host during development.

**Comment by jonathanperis** [comment]
So the benefits of using ASP.NET project is to use things like Dependency Injection and Entity Framework? in the example I saw that the ASP.NET project is who references the Blazor project. how would the use of ASP.NET resources in Blazor project in this case?

**Comment by danroth27** [comment]
The ASP.NET Core project serves a few purposes:
- It hosts the static files for your Blazor app so they can be downloaded
- It provides a framework for exposing services and data to your Blazor app over HTTP
- It provides integrations with Blazor (development middleware) to make developing your Blazor app easier and more productive (live reloading, prerendering, etc.)
