### ISSUE TITLE
Why are we messing around with html when we have .net?

### ISSUE THREAD

**Issue by Bartolomeus-649** [aspnet/Blazor#840]
How do you get winforms or a wpf application to run in the browser with Blazor?

Or Silverlight, that's a framework even smaller than .NET/Mono, why not use that?  Just about anything is better then doing GUIs in HTML.

**Comment by chrissainty** [comment]
Blazor is supporting web standards. If you are more interested in XAML then the [Ooui](https://github.com/praeclarum/Ooui) project would probably be more to your liking.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @chrissainty!

**Comment by taori** [comment]
@chrissainty This reply isn't really helpful. It was my first thought too, when i heared about blazor. Silverlight was scrapped because it required an external plugin - it's the result which matters. If i want a SPA, silverlight would be amazing if it were built on top of webassembly. I would not even spend a second thinking about using blazor then. If i want to write HTML i'd just go with mvc, instead of learning another hybrid with new syntax.

**Comment by chrissainty** [comment]
@taori I’m struggling to see why my response wasn’t helpful. I clearly restated what the Blazor team have said from day 1, that the framework will support web standards. I.e. HTML and CSS. I also provided a link to a project which is looking at things from a more desktop/Silverlight angle. I’m failing to see your issue.

**Comment by chrissainty** [comment]
Well, I pointed out a framework that appears to be developing the thing you seem to be longing for so much. 

Seems pretty helpful to me.

**Comment by humbersoft** [comment]
Anyone who has spent over 10 years in IT will recognize that, like many things in life, it is just one big cycle. Old ideas always come back as new. I 100% agree with @Bartolomeus-649 points and comments. Microsoft made a huge mistake by killing Silverlight. However, please remember that the industry was moving away from the plugin-based model that Silverlight and Flash was. People hated being forced to use IE or Windows OSes. People love choices. They want to run their apps on Windows/Linux/MacOS/Android/iOS or whatever else. It was either run with the crowd or be left behind. 

HTML and CSS are web standards. Apps built to this standard will have much further reach and shelf life than any app built to run only on Microsoft browsers or OSes. Silverlight and Flash were horrible from security and mobile standpoint. We still do not know what to expect from Blazor with respect to mobile battery life and security. I hope Blazor pays attention to these concerns. 

IT is a cycle so Silverlight may be resurrected to run on WebAssembly. @chrissainty gave some examples of some different approaches WPF-based and Silverlight-like. Blazor doesn't take away from those approaches. Blazor just wants to build the UI layer using HTML and CSS. I think it is a good choice.

**Comment by JeffMushmo** [comment]
I went ahead and started building a Xaml engine that runs natively in the browser. You can check it out here: [https://github.com/XamlEngine/Samples]

**Comment by Bartolomeus-649** [comment]
Rendering XAML in the browser might be cool, but it just HTML on steroids, brings very little to table when what we really need is an Application Development Framework. A framework that connects the front-end to the back-end in a structured highly productive typesafe way, as well as providing a way to write native .NET/C#/XAML in a fully supported way in Visual Studio that can run in a browser as well as a native application on most devices and platforms.

**Comment by JeffMushmo** [comment]
XamlEngine isn't HTML on steroids. It has it's own parsing engine, layout engine, rendering engine. It's build on top of WebGL and renders pixels in an HTML canvas.

The reason I started building this is because of exactly what you're saying. .NET already runs on all platforms. The one thing that doesn't exist on all platforms is natively rendered Xaml. XamlEngine is compiled from C++ (so it can run natively on any platform) and it targets OpenGL thanks to Emscripten (so it can theoretically run on any device). But the current priority is to getting it working for the browser.

Technologies like this, paired with all the cool stuff the .NET Core team is doing will (hopefully) someday create the ideal platform for development.

**Comment by Bartolomeus-649** [comment]
What I meant with HTML on steroids is that you replace one XML GUI definition (HTML) for another XML GUI definition (XAML).
And as long as you are not satisfied with static pages, you need code to run together with the XAML, code that hopefully is written in C#.

Blazor is so close to what could be a first step to something wonderful....all Blazor need is to just fully support .NET and draw stuff just like you do on a canvas in HTML. If they did that, then all Silverlight applications, WinForms and WPF applications would just work in the browser with none or very little adjustment.

**Comment by JeffMushmo** [comment]
Well that's just how I'm currently parsing the source Xaml. The important part is that I have a function that can be invoked where I pass it Xaml and it renders that Xaml on the screen. Exporting that function call (and the DOM tree) from my WASM package would allow the ported DotNetAnywhere runtime to hook into those calls.

But this is still experimental. There are a lot of features that still need to exist. It still doesn't yet support mouse + keyboard input. And while I share your love for C#, I think this Xaml technology should be available to any language, including Javascript. Hence, why the simplest form of rendering Xaml in the browser is the example I've created. That way you could render Xaml from an app you authored in notepad if you wanted to. With that low barrier for entry, I don't have to create a bunch of build tools to get my engine up and working.

What I still need to build in though is the ability to compile the Xaml at build time. WPF does this and I think they call it BAML. In that scenario, raw xaml would never be transmitted from the web host. This would be pretty easy to do. If it gets to the point where this is integrated with the ported DotNetAnywhere, then we can talk about an ideal package format.

**Comment by zwcloud** [comment]
Why not just write a WebGL-based or Canvas-based rendering backend and render XAML on top of that? ;)

**Comment by JeffMushmo** [comment]
Because if it remains compatible with OpenGL, C++ can be compiled for Android, iOS, Linux, Max, Windows, etc. One codebase, same Xaml engine everywhere. ;) ;)

**Comment by arkadiuszwojcik** [comment]
> Because if it remains compatible with OpenGL, C++ can be compiled for Android, iOS, Linux, Max, Windows, etc. One codebase, same Xaml engine everywhere. ;) ;)

And how do you think, what this "one codebase" is using to render on Android and iOS? :)

**Comment by vibhoretanwer** [comment]
People who have always worked on web using HTML/CSS can't appreciate the power and simplicity of XAML. Blazor does add a lot of value by enabling C#/.NET instead of JavaScript, but I agree with @taori that it might not survive because it goes back to old WebForms like approach instead of clean MVC/MVVM like approach. If Microsoft can unify the world with XAML for UI and C# for logic it can become single greatest platform for software development and we as developer can focus on developing great features rather than learning a new web technology. JS framework every few months. XAML is far more mature and stable then web stack (HTML/CSS/JS) and its already proven by these new frameworks every now and then which are just trying to copy features like bindings/commands etc. from frameworks like XAML/WPF.

**Comment by GoranHalvarsson** [comment]
I have to disagree with previous speaker. Please stick to html and css. This will be the new standard for mobile apps. Progressive web apps will grow and outcompete classic native apps. And if we you want to build native apps (using blazor), it will be possible with electron.

**Comment by Arshia001** [comment]
@GoranHalvarsson that, and python's quick rise through the ranks, has me seriously worried about the future of software development. I don't know why the general public seems to only like horrible technologies. I mean, who takes a single-threaded, type-unsafe language with no compile-time checks (`0 + [] + "" = "0"`) and creates servers with it? What, aside from the number of people using a technology justifies that? And when people use something, it's not because it's better (or we'd all be writing Haskell), but because it's more accessible or easier to learn at an elementary level. Blazor is a ray of hope, because it lets people break free of the hell that is javascript development. I have my fingers crossed for an alternative to HTML that's well-supported and optimized next.

**Comment by vibhoretanwer** [comment]
@GoranHalvarsson HTML/CSS was developed years back to design newspaper like web pages and its still the same. It has not really evolved the way other technologies has. So no I don't agree, HTML/CSS is a thing of past not future.

**Comment by Telavian** [comment]
I personally love xaml and think WPF is amazing from a development perspective.
WPF + MVVM makes developing applications almost easy.

With Blazor we no longer need to worry about the horrible mess of JS and can focus on logic and UI. This makes web development almost the same as desktop development.

HTML is certainly not as nice as XAML however they are honestly very close and I don't see why they can't be the same eventually. CSS is definitely a pain when it doesn't work however component vendors (Telerik!!!) massively simplify things like this.

I see Blazor as a huge step in the right direction and I think Blazor 2.0 will merge desktop and web development into a unified approach.
