### ISSUE TITLE
Html meta tags, page title 

### ISSUE THREAD

**Issue by GoranHalvarsson** [aspnet/Blazor#842]
Hello people

You guys are doing a wonderful job with Blazor :-)

I have a question regarding Html meta tags. The app itself will be placed in the app element on the page. But how about stuff in the header? Like meta tags and so on. 
Let say I would like to change/update meta tag data depending on what page (in the app).  Or just update the page title. 
How to do this? By Javascript interop?

**Comment by Andrzej-W** [comment]
Good question. I was thinking about this problem in my own application and so far I have no solution. Think about server side rendering in the future. Correct meta tags are essential for SEO, for integration with Facebook/Twitter, etc.

I hope that we will be able to create multilingual Blazor applications in the future. To do it correctly we have to handle lang attribute in html element.

We have to be able to modify main index.html file from Blazor application and selected solution have to be compatible with server side rendering.

**Comment by GoranHalvarsson** [comment]
Yes exactly. My vision/hope is that Blazor will be "the new way" of doing web pages. Like replacing the "old way" of doing server-rendered pages. If we(you) could find a way how to handle stuff outside the app element, like Meta tags, title etc. Then the game is afoot :-)

**Comment by Andrzej-W** [comment]
I have found yet another example why we need a way to modify HTML page elements outside of out Blazor application tag. We can have an application with multiple pages and someone can add a link to Favourites in the web browser. Link should have proper title - otherwise links to different pages are indistinguishable.

**Comment by SteveSandersonMS** [comment]
For most nontrivial Blazor apps, you'll want some notion of a data store that issues notifications when its state changes. There's an example of this in the FlightFinder sample: https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor/FlightFinder

With this kind of architecture, you can have "page title" as one of the data items tracked in the store, and can subscribe to that in your layout to change the `<title>` element's contents whenever that changes.

**Comment by DNF-SaS** [comment]
@SteveSandersonMS How do you change the content of the <title> element located in <head> in index.html?

**Comment by SteveSandersonMS** [comment]
@DNF-SaS Yes

**Comment by Andrzej-W** [comment]
@SteveSandersonMS Thank you for suggestion. Of course we can use data store and modify what we want in JavaScript (title, metatags, etc.). But in the future we will have server side rendering. It would be nice to find a solution which will work on the client and on the server.

In ordinary ASP.NET Core application I have a base ViewModel for all my pages. I use this base class in _Layout.cshtml like this:
```html
@model ViewModelBase
<!DOCTYPE html>
<html lang="@Model.Language" prefix="og: http://ogp.me/ns#">
<head>
<title>@Model.Title</title>
@if (!string.IsNullOrEmpty(Model.OgVideo))
{
    <meta property="og:video" content="@Model.OgVideo" />
}
```
As you can see I assume that some model properties (Language, Title) are always available and I render them unconditionally. On the other hand not every page has video which can by shared on social sites and og:video metatag is rendered conditionally.  It would be nice to have similar experience on the client. Maybe it is possible to add some event to the router (for example OnHeadRender). In that event we should be able to render at least the opening `<html>` tag and `<head></head>`. This event probably should be executed after OnParametersSet - page component should have a chance to set some state in global data store (similar in concept to my base ViewModel in ASP.NET Core application).

I understand that it is not a high priority task at this stage of Blazor development, but I think it should be tracked somewhere.

**Comment by desalbres** [comment]
If would be great if you had a namespace (or helpers) to manage header's metadata (such as title, meta keywords), and also a set of helpers to manage Cookies, and also a wrapper to the windows javascript namepace !

**Comment by danroth27** [comment]
@topnguyen Correct, the story is pretty much the same.

**Comment by evrenunal** [comment]
Still no solution?

**Comment by evrenunal** [comment]
I have similar problem for seo purposes,
I need to be able to modifiy title and description tags for every "page"

**Comment by andras-ferencz** [comment]
I used a bunch of ugly JS-Interop and pre-rendering pages as static HTML to get crawlers working around; but it's definitely not ideal. 

It would be really great to see a "MetaHelper" built into Blazor akin to UriHelper where I can just call `MetaHelper.Links["en"].href = "XYZ";` or `MetaHelper.Title = "XYZ";`

**Comment by chrdlx** [comment]
Is there an official recommended way to solve this yet?
The only way possible right now seems to build the whole site with .cshtml + .razor pairs, for example:

Home.cshtml (which renders the home component)
Home.Razor
Products.cshtml (which renders the products component)
Products.razor
etc...etc...

This way you create a hybrid approach, in which everything in the page is interactive (without postbacks), except links to other pages which would trigger the browser redirect to another .cshtml razor page, each one with its custom head tags.

Is there a known better solution?

Also even this solution doesn't work since `<a href="etc">`  link tags seem to be catched by the framework blocking the browser to properly redirect. 
(issue which is being tracked here https://github.com/aspnet/AspNetCore/issues/9834 )

Regards!

**Comment by SteveSandersonMS** [comment]
Currently the simplest and cleanest solution is to use JS interop to modify the document state.

We are planning to improve this, though we don't have a final design or ETA yet.

**Comment by honkmother** [comment]
JS Interop? What? No! 

You don't even need anything sophisticated to do this.
This is terrible code made one late night in 0.9 but it should give you an idea on how to do this; you can probably do this more way efficiently.

Basically, create an html component, a body component, and a head component; render the html component in Index.cshtml; put a reference to the Head Component inside a Metatag Container; set the reference to "this" from the Head component upon init, and also pass this container into the Body component and whatever is inside of the body. 

From there you can update the Head component, which will update the SEO tags as expected.


Here's what my **Index.cshtml** looks like
```
@page "{*clientPath}"
@using dao.Server
<!DOCTYPE html>
<html>

@(await Html.RenderComponentAsync<html>())

</html>
```


Then I have two classes called "html" and "metatags".

```
    public class html : ComponentBase
    {
        public static string HeadTXT = File.ReadAllText("head.htm");
        Metatags meta = new Metatags() { Title = "some title" };
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder builder)
        {

            builder.OpenElement(0, "head");
            builder.AddMarkupContent(1, HeadTXT);
            builder.OpenComponent<Head>(2);
            builder.AddAttribute(3, "MetaInfo", meta);
            builder.CloseComponent();
            builder.CloseElement();

            builder.OpenElement(4, "body");
            builder.OpenComponent<Body>(5);
            builder.AddAttribute(6, "MetaInfo", meta);
            builder.CloseComponent();
            builder.AddMarkupContent(7, "<script src=\"_framework/components.server.js\"></script>");
            builder.CloseElement();

        }
    }

    public class Metatags
    {
        public string Title { get; set; } = "example.nyc — weirdest hack ever";
        public string Description { get; set; } = "testing";
        public Head Component;
    }
```






A "body" Component.

```
<DetectPrerender MetaInfo="@MetaInfo">
    <Router AppAssembly="typeof(Startup).Assembly" />
</DetectPrerender>


@functions {

    [Parameter]
    private Metatags MetaInfo { get; set; }

}
```






And a "head" component.
```
@using example.Shared

<title>@MetaInfo.Title</title>
<meta name="description" content="@MetaInfo.Description">
@{
    MetaInfo.Component = this;
}
@functions {

    [Parameter]
    private Metatags MetaInfo { get; set; }
    private bool ShouldRend = false;
    protected override bool ShouldRender()
    {
        if (ShouldRend)
        {
            ShouldRend = false;
            return true;
        }
        return false;
    }

    public void ShouldRe()
    {
        ShouldRend = true;
        base.Invoke(() => base.StateHasChanged());
    }

}
```

**Comment by TheFanatr** [comment]
That's a nice way to do it where Blazor has full control over most of the document, but it could pose a mild load time issue in certain cases and still requires interop implicitly.

**Comment by smartprogrammer93** [comment]
@honkmother does this work for client side blazor or only server side. And if it does work for client side blazor, can you provide a git repo showing your configuration?

**Comment by honkmother** [comment]
@AlexYes it requires some minimal interop between the components; but doesn't need any Javascript. 
I think this is close to as good as we can get in terms of patterns that already exists within Blazor. I wouldn't mind seeing a default HTML, Body, and Head tag with Dictionary structures, and having those references passed down a cascade or something.

@smartprogrammer93
It should work for both, but I would have to double check because for all I know <app>...</app> could be a hard coded hook into the DOM; but I am almost certain if you rename App.razor to Html.razor, it will allow you to use the HTML element instead. 
Client side might be a little different because you need the script tag in the document for Blazor to even boot up (where as serverside renders the components for you). I am 99% certain you can just throw the script tag inside of the loading placeholder.

After I'm done working today I will set up a repo with an example that works with preview4/5 for both the client and server.
