### ISSUE TITLE
Need a way to access a layout from a page

### ISSUE THREAD

**Issue by masonwheeler** [aspnet/Blazor#857]
Currently, if a page has a layout, there doesn't appear to be any way for the page to get a reference to it.  This can be very frustrating if you want to pass parameters from the route data to the layout, for example.

Is there a way to do this that isn't obvious?  If not, can it get added to the next release?

**Comment by kiyote** [comment]
Ideally the page could pass parameters to the layout.  Or vice-versa, but then the layout would need to be able to get [Parameter] injection and then pass parameters to the rendering of the body.

**Comment by SteveSandersonMS** [comment]
In general the parameter flow goes downwards, i.e., from parent to child, not in the other direction, because the rendering flow goes in that direction. That's why there isn't a way to pass parameters upstream (e.g., to a layout), because then there's be no single defined render order.

So for what you're trying to do I'd recommend using a regular component with `ChildContent` instead of a layout. For example, in the default template, change `MainLayout.cshtml` by removing `@inherits BlazorLayoutComponent` and adding a `ChildContent` parameter, e.g.:

```
<div class="sidebar">
    <NavMenu />
</div>

<div class="main">
    <div class="top-row px-4">
        <a href="http://blazor.net" target="_blank" class="ml-md-auto">About</a>
    </div>

    <div class="content px-4">
        @ChildContent
    </div>
</div>

@functions {
    [Parameter] private RenderFragment ChildContent { get; set; }
    [Parameter] private string SomeOtherParameter { get; set; }
}
```

Since this is no longer a native layout, also go to your `Pages\ViewImports.cshtml` and remove the `@layout MainLayout` directive.

Then for each page that wants to use the layout, you can wrap its output in `<MainLayout>`, e.g.:

```
@page "/"

<MainLayout SomeOtherParameter="HOME">
    <h1>Hello, world!</h1>

    Welcome to your new app.
</MainLayout>
```

I'd be interested to know how you get on with this approach since it is quite unusual.

**Comment by kiyote** [comment]
Before I get in to a more thorough response: Thank you for taking the time to look at this issue and to comment so extensively on it.  I know your time is precious and I wanted you to know it's appreciated.  You did even answer my own internal question of "does the page own the layout, or does the layout own the page", so much appreciated there too!

Anyway....

I found the Blazor/Redux component (https://github.com/torhovland/blazor-redux) and this suits my needs, so far.  I don't really agree with your assertion that what I'm doing is "quite unusual", though.  (I don't want to devolve in to an argument, I'd just like to state my case)  I suppose it could be unusual in the Razor style of page building, which I admit I'm not terribly up to date on.

I come from a React/Redux world, where the router is an explicit component like any other, rather than the somewhat implicit routing we have here in Blazor. (Not knocking it!  Just saying it's different!)  When you have the control to declare the router and the routes as a custom component, it's quite trivial to implement the top-down flow of props for your pages.

With Blazor I'm able to fake that ability through a common root custom component that injects my store rather than each component receiving it, but it works well enough.

Incidentally, if the routing is going to be made more flexible to be a component we can declare and implement, then that would help tremendously in supporting those transferring over from ReactLand.

**Comment by SteveSandersonMS** [comment]
> I come from a React/Redux world, where the router is an explicit component like any other, rather than the somewhat implicit routing we have here in Blazor.

The router is also an explicit component in Blazor. In the default template, you'll find it in `App.cshtml`. The thing that's more different between Blazor and `react-router` is that Blazor has a layout system whereby a component can nominate its own layout. With `react-router` you don't really have layouts as a build-in notion; instead you just create a hierarchy of components where you vary the render output at some point in the tree based on the current route. We could do the same in Blazor but have designed the current system to be more familiar to Razor Pages developers. Maybe we'll end up changing it. I'd appreciate any feedback you come up with about advantages and disadvantages of different possible approaches.

**Comment by sven5** [comment]
I'd like to add a comment on this topic. 

In MVC I used ViewBag in the _Layout to dynamically show the title depending on the current page. The ViewBag's title property is set in the page. 
So now in Blazor there is no ViewBag. I tried to use a simple service class injected by DI to accomplish this but was unsuccessful. 

It seems there is currently no way to modify a property in a layout component from a page.

**Comment by sven5** [comment]
Hi @SteveSandersonMS ,

thanks for your fast reply. I currently got it working as you described. I will post my demo code here:

**Edit:**
I found a possible workaround. I only wanted to pass a headline/title from the page to the layout.

Define a simple ViewData class that implements INotifyPropertyChanged (I call it ViewDataService):

    public class ViewDataService : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        private string _caption;

        public string Caption
        {
            get => _caption;
            set  {
                _caption = value;
                OnPropertyChanged();
            }
        }
    }

Register this class as a singleton service to the DI container in Startup.cs:
`services.AddSingleton<ViewDataService>();`

Inject the service into your page:
`@inject Services.ViewDataService ViewDataService` 

And set the title in the page's code accordingly:
     
      protected override void OnInit()
      {
         base.OnInit();
         ViewDataService.Caption = "Caption set from Page";
      }
   


Now inject the service into your layout (MainLayout) with `@inject Services.ViewDataService ViewDataService`

Usage of property Caption:
`<h2 class="header-caption">@ViewDataService.Caption</h2>`

And attach the PropertyChangedHandler to register for property changes:

    protected override void OnInit()
    {
        base.OnInit();
        ViewDataService.PropertyChanged += OnPropertyChanged;
    }

    private void OnPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
          StateHasChanged();
    }

That's it.

**Comment by aaronhudon-ts** [comment]
Does this apply to parameters as well?  I have a need to access the current page's route parameter when rendering navigation links from the layout.  I really don't think this is unusual.

**Comment by danroth27** [comment]
@Yen Thanks for the feedback! Unfortunately, this is a closed issue in a repo that we're aren't using to track future Blazor work. Could you please provide this feedback through an issue on the https://github.com/aspnet/aspnetcore/issues repo?

**Comment by GoranHalvarsson** [comment]
@Yen you can use cascadingparameters for this. Setting/updating cascadingparameter on a child component works(you get a warning, but it is possible)
