### ISSUE TITLE
Blazor uses old version of .NET Core SDK

### ISSUE THREAD

**Issue by SIkebe** [aspnet/Blazor#870]
Blazor 0.3.0 requires dotnet core SDK 2.1.300-preview2-008533 or later.
https://blogs.msdn.microsoft.com/webdev/2018/05/02/blazor-0-3-0-experimental-release-now-available/

However, Blazor itself uses 2.1.300-preview2-008367 to build.
https://github.com/aspnet/Blazor/blob/efc737b21492d5b74157b447256396d752a5d598/global.json#L1

Is there any reason to use prior version? Not RC1?

**Comment by rynowak** [comment]
The ASP.NET Core repos will almost always use a prerelease SDK to build. This is how we flow arbitrary builds of the SDK and tools through our build system. Even is we did update this repo to target a specific version, that would be a temporary situation and we'd end up with a prerelease again very soon. 

Since Blazor is part of the ASP.NET Core project, we don't want to deviate from the tools and practices that the shipping repos use. Let us know if this is causing you problems in any specific way. 

You're right that in this case we haven't updated this repo in a while, I'll do that.

**Comment by SIkebe** [comment]
Thanks for clarifying!

**Comment by rynowak** [comment]
I don't really understand the question. What are you trying to do and why?

**Comment by rynowak** [comment]
Closing this because it's updated and I've answered the original question. @ncarandini if you still have something you want to discuss relevant to Blazor feel free to open an issue or reply here.

**Comment by ncarandini** [comment]
@rynowak, sorry, I'll try to clarify:
Using VS 2017 Preview (15.8.0 Preview 1.1) and CI Blazor (version 15.7.10293), after creating a new Blazor app the project will contain a `global.json` file that contain a reference to .NET Core SDK version `2.1.300-preview2-008533` that is not the latest, and you have well explained why.

If I delete the `global.json` file, the project will automagically use the latest installed (in my case, the version `2.1.300-rc1-008673`).

My question is: is this a good practice?

**Comment by SIkebe** [comment]
@ncarandini It depends. IMHO, you might want to have your `global.json` and pin the SDK version to avoid unexpected behavior in future.

**Comment by rynowak** [comment]
It's not in general a *good practice* to delete the global.json - if you're the only one working on your codebase then it probably won't matter what you do since you control your environment. The tooling about SDK versions is going to improve during 15.8 - and I hope we'll eventually be at a place where VS tells you if you have an older or mismatched SDK than that the global.json indicates.

If you want to update the global.json to track a newer SDK version that would be fine. SDKs are intended to be backwards compatibile.

**Comment by ncarandini** [comment]
@rynowak @SIkebe thanks for the good advice. From now on, I will not delete it anymore but change it to the desired version.
