### ISSUE TITLE
data-* attribute, unexpected behavior

### ISSUE THREAD

**Issue by shumas** [aspnet/Blazor#941]
Steps to reproduce:
1) Create new blazor project
2) Add component:

```
<div data-tab="@TabId">@ChildContent</div>
@functions
{
    [Parameter]
    string TabId { get; set; }
    [Parameter]
    RenderFragment ChildContent { get; set; }
}
```

3) Modify index.cshtml, add following lines:

```
<TabHead TabId="main">Main</TabHead>
<TabHead TabId="cat">Category</TabHead>
```

Result:
```
<!--!-->main<div data-tab="">Main</div>
<!--!-->cat<div data-tab="">Category</div>
```

Expected result:
```
<!--!--><div data-tab="main">Main</div>
<!--!--><div data-tab="cat">Category</div>
```

**Comment by SIkebe** [comment]
@shumas Did you check this?
https://github.com/aspnet/Blazor/issues/297

**Comment by SteveSandersonMS** [comment]
@rynowak Unfortunately this does still repro in the 0.4.0 RC (with VS 15.7.3 and .NET Core 2.1.0 rtm).

It's hard to understand why it's still happening, because we have a unit test for it (`SupportsDataDashAttributesWithCSharpExpressionValues`) where it does work correctly and passes. But if you paste the same code from that unit test into a real project, the compiled result is not correct. Somehow the unit test isn't reflecting the real behavior.

Ryan, would you be able to look into this before we release? Maybe it's something we can put in a quick fix for, or failing that, bring back the `data_` workaround.

**Comment by rynowak** [comment]
Fixed by https://github.com/aspnet/Blazor/pull/949

**Comment by rynowak** [comment]
Thanks for the report @shumas
