### ISSUE TITLE
CLI command for changing base href tag

### ISSUE THREAD

**Issue by chrissainty** [aspnet/Blazor#971]
I don't think this is covered by another issue, apologies if it is. This might be one for a bit further down the line. But it would be good to be able to change the base tags href via a CLI command, similar to how Angulars CLI works. This will be really useful in CI pipelines or just in any scenario where prod requires a different base path to a development environment.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. That's definitely interesting, and we'll bear this in mind.

Closing as it's not something we will necessarily do, but if it becomes a common request we'll definitely consider it.

> This will be really useful in CI pipelines or just in any scenario where prod requires a different base path to a development environment

As a general point, I'd strongly recommend you *don't* set yourself up in a situation where prod differs from dev in that way. It will create many opportunities for bugs that you don't notice early in development. It's usually worth making sure your dev environment reflects prod more closely than that.

Please don't take that as dismissive of your request. I know there may be cases where you decide to have that difference. I'm just posting this comment so that when others read this issue they don't get the impression that it's normal to be in that situation. Hope that's OK!
