### ISSUE TITLE
TypeLoadException: System.Threading.Tasks.Task

### ISSUE THREAD

**Issue by juanfranblanco** [aspnet/Blazor#98]
Hi,

I am experimenting and trying to reference netstandard1.1 libraries (Nethereum), but I am getting the following error:
```
System.TypeLoadException: Could not resolve type with token 01000017 (from typeref, class/assembly System.Threading.Tasks.Task`1, System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
```
I have not followed the progress of the project, but is there a specific requirement to use System.Threading.Tasks (and other libraries) as per the one included AngleSharp? Just trying to figure out the source of the error.

Thanks

J

**Comment by SteveSandersonMS** [comment]
It's because your project is targetting `netcoreapp2.0` when it needs to target `netstandard2.0`. Info is at https://github.com/aspnet/Blazor/blob/37a8cbc32d3797d807749f863d882838375186eb/samples/HostedInAspNet.Client/HostedInAspNet.Client.csproj#L4

We will certainly sort this out by the time the first project template ships. In the meantime you might be able to change it to `netstandard2.0` but would have to figure out the details yourself. I'll close this because it's already known as a thing we need to do as part of #7.

**Comment by juanfranblanco** [comment]
Many thanks
