### ISSUE TITLE
Create new issue template

### ISSUE THREAD

**Issue by fileman** [aspnet/Blazor#999]
Since many issue was related to slow performance, blank screen due to wrong sdk version, server pkg in blazor proj, why not create e issue template with something like:

**Read this before post new Issue**
1. dotnet -version = 2.1.300
2. runtime was not optimized yet so performance can be slow
3. nuget pkg for server side should not work in blazor client proj (ex. EFCore)
4. other recurrent question

**Comment by Andrzej-W** [comment]
In this short instruction add link to #969 or simply copy part of it.

**Comment by SteveSandersonMS** [comment]
We'll definitely consider that as time goes on.

Part of me would prefer to avoid it, because:

1. It doesn't feel very friendly when you're just getting to know a new project and have a question if it feels like there's a wall set up to keep you out.
2. On a lot of GitHub repos, the issue template is just boilerplate nonsense. Maybe it started out making sense, but they kept adding more and more bits to it over time.

So I'm not sure it's time for that right now, but CC @danroth27 / @rynowak for their input too.

**Comment by rynowak** [comment]
I'm a skeptic - because normally a low-effort poster isn't going to read your FAQ or fill out your template. It's a bit like the anti-piracy adverts on DVDs, you're punishing the people who are making an honest effort. But, I think there's some value to squeeze out if you're willing to tailor it to your needs.

You have to ask, what problem are you solving? It sounds like @fileman just wants to reduce the amount of noise here. Generally that's much more of a problem for the maintainers rather than someone who's subscribed. @SteveSandersonMS is kinda the captain for issues here, and he keeps up pretty well I think - to me his opinion matters the most.

---

We recently took this on over in aspnet/Mvc. Specifically we were buried in really low quality 'issues' - many of them just questions about things that are covered in documentation. We also attract a lot of issues about other areas of .NET. Some developers see MVC in their project so they think that everything they use was provided by the 5-6 people who work on MVC - they are paying us quite a compliment 😆 

Anyways, @kichalla mostly drove this, and I helped a little. We came up with something optimized for the problems we wanted to solve. https://github.com/aspnet/Mvc/issues/new

To me the most valuable part was this part: `Is this a Bug or Feature request?:` - we need to know if this is a bug, or feature request. Bugs get assigned for investigation, features go to the backlog to be triaged later, and *other* largely just gets closed if it can't be addressed quickly.

Notice that you don't find any of the usual junk here. We don't care what operating system you're using and what CPU you have installed - those details are just homework that doesn't help us investigate.

**Comment by fileman** [comment]
Yes, my proposal was to have a reduction in new issue due to not having carefully read the system requirements.
As a subscriber is not a problem to receive notifications for these problems, it is more to my heart that you have as much time as possible to develop Blazor :-)

**Comment by SteveSandersonMS** [comment]
Thanks again for suggesting this. Following the discussion here I think we're OK with continuing as-is for the time being. We can always reconsider in the future if we want. Thanks!
